### ISSUE TITLE
zidoo x6 pro

### ISSUE THREAD

**Issue by grummel2005** [koying/SPMC#100]
is zidoo x6 pro running with 16.1.1 and will it be supported?

**Comment by koying** [comment]
I don't know. 
I don't have it, so it will surely get no specific support.

**Comment by grummel2005** [comment]
oki so lets have a look what you will give to us :)
thx in advance

**Comment by grummel2005** [comment]
at the moment zidoo is changing always the version of kodi bythemself instead to fix the operating system android to be fully confirmed to android system
it will be interesting how long they will do it
because in germany the guarantee is 2 years they have to do it this time!
