### ISSUE TITLE
Nvidia Shield not showing any recommendations from SPMC

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#102]
The changelog for 16 states:

"Android TV recommendations and voice search (experimental)"

However, my shield does not show any recommendations from SPMC with SPMC running in the background for numerous hours.

SPMC is also not listed in System --> Home Screen --> Customize Recommendations

Also I have tried many ways to try voice search but nothing related to SPMC is ever shown and again is not listen in the apps used within search.

I understand both features are "Experimental" but i'm just looking for some clarity on what to expect with these functions on the shield.

Thanks in advance.

**Comment by Turingoo** [comment]
Same here, on Android 6.0.0, SPMC 16.1.1, Nvidia Shield 16Gb.

kudos and thxs.

**Comment by mattsch** [comment]
Log entry for the search issue:
03-17 20:43:03.724  3429  3600 W Search.SearchableSources: com.semperpax.spmc16/.XBMCSearchableActivity has bad suggestion authority com.semperpax.spmc.media

Recommendations are working fine for me, same systems and specs so I can't really help there.

**Comment by ghost** [comment]
Koying, would it help if I launched SPMC up for a few minutes and provided a log?

As in the OP Recommendations and voice search are not working here on the Shield MM 6.0 so not sure if the log will help you in any way?

**Comment by ghost** [comment]
Recommendations are working fine here - they currently show the recently added movies from Kodi's library.

**Comment by koying** [comment]
Forgot to say that you have to enable the web server in Settings-Services to Recommendations and Search (currently broken) to work ;)

Default port/user/password, for now.

**Comment by ghost** [comment]
Yup working great now koying, for some reason I had added a password to the webserver. Thanks

**Comment by Turingoo** [comment]
Once enabled web server, I see Recommentations.

**Comment by koying** [comment]
Please try http://download.semperpax.com/spmc/android-arm/SPMC-20160318-d85375b-fix_search-armeabi-v7a.apk for search

**Comment by ghost** [comment]
Yep voice search works great in that apk koying. Thanks again!

**Comment by mattsch** [comment]
Test version works for me as well.

**Comment by koying** [comment]
Ok, thanks. Will be in 16.1.2.

**Comment by bobbs204** [comment]
Hey guys I'm try this feature out and not getting any SPMC results still.  Im on 16.4.2.  It works with in SPMC in things like exodus-search but on home screen nothing is popping up at the bottom of the recommendations.  Any help thanks

**Comment by paulsavo1** [comment]
folks did anyone solve this i have 16.6 spmc installed on 2017 shield tv with web server on but no recommendations or global serach

**Comment by Turingoo** [comment]
It was fixed a long time ago. I Have 16.6 installed on the old Shield with  7.0 and everything works fine.

Port 8080, username kodi.

Maybe the 2017 Shield is to blame?
