### ISSUE TITLE
Any chance for a new 17.4-based alpha release?

### ISSUE THREAD

**Issue by maxiauer** [koying/SPMC#1023]
Hi Koying

First of all thanks a lot for sharing your SW !!!

Now that 17.4 has been released, and taking into account that the latest SPMC Krypton-based alpha is a month old, it would be great to be able to test an updated alpha release.

Thanks in advance

Max

**Comment by oOflyeyesOo** [comment]
Released earlier!

**Comment by maxiauer** [comment]
Great !!!
