### ISSUE TITLE
TVDB Library Info in Alpha 9

### ISSUE THREAD

**Issue by thomfam** [koying/SPMC#1028]
Taken from #936.

Maybe just me but I added Series 3 of Narcos to my Files and the new SPMC 17.4a9 failed to pick up any episode info via TVDB website. Maybe a TVDB problem, I am not sure. Worked fine on Krypton 17.4 and added to the Library but would not do it on SPMC 17.4a9.

Have refreshed and removed from library then re-added it, Deleted everything then put the files back again. Only a partial recognition from TVDB, it sees the series, adds the 'cover' and basic series summary but not the individual episodes. Switched over to Krypton and did a "Refresh" from "Information" Context Menu and all the info there for all 10 episodes in a couple of seconds.

Comment from Roy 2810:  I also have this problem

**Comment by thomfam** [comment]
Reverted to Alpha 8, and removed "Narcos" from the Library, Then in Alpha 8 did a rescan to Library and Narcos was added perfectly.

**Comment by Michelasso** [comment]
I confirm the issue in v17.4a9. I have been trying all yesterday to make the TV shows appearing. The first two levels of folders (<TV Show/Season #>) get indexed, all subsections (like Genres, Studio etc.) get filled but then clicking on anything I just get the "Back" ("...") folder. It sees them like if the season folders are empty.

I've just downgraded to v17.4a8 and finally all episodes are appearing. And also playing!

**Comment by Kr1ss-XD** [comment]
Same issue w/  _The Last Ship_ Season 1-4.
Can confirm it's being scraped as expected in 17.4a8. Thank you @thomfam for mentioning this.

**Comment by koying** [comment]
Should be fixed in alpha10 (just out)
