### ISSUE TITLE
SPMC-16.7.1 crash/won't load after reboot. Stuck on Loading Database

### ISSUE THREAD

**Issue by TweekDash** [koying/SPMC#1030]
not sure if any of these details help but I was running SPMC-16.4.2 for the longest time with no issues on all 3 of my systems. I am still running it on one of my systems (FireTV gen 1 FireOS3) and not having issues.

I updated 2 of my systems (nvidia shield TV and FireTV gen1 FireOS5) to SPMC-16.7.1 I used the same advancedsettings.xml I used before and during initial install everything works great, the database loads and I can access files. After a reboot or closing of SPMC when you go to launch SPMC again it gets stuck on the splash screen saying Loading Database. I updated the advancedsettings.xml removing the MySQL db settings and manually entered them under Services hoping that would fix the problem but after you shutdown SPMC when you go to reload it the problem comes up again.The new systems are also running a stock version of Krypton Kodi because there is 1 add-on I use that requires it but I preferred the stable SPMC.

I am accessing the same MySQL db that I always have and it's still accessed fine on the older 16.4.2 version. I am willing to go back to 16.4.2 for now if that will fix the issue.

[spmc log nvidia](https://pastebin.com/eWGj0KW5)
[spmc old log nvidia](https://pastebin.com/8FzDs3nu)
[spmc log firetv gen1 os5](https://pastebin.com/CkDU9vV7)
[spmc old log firetv gen1 os5](https://pastebin.com/Cs3pSQjM)

**Comment by ziggy73701** [comment]
I have seen this to on my NVidia Shield... can't post a log at moment as am away from home. System will work, then get a random crash and will loop on loading database. Also running MySQL. The PROBLEM seems worse if I have more than 1 instance accessing the database... I had put it down to a MySQL thing but wonder if there is some kind of time out in SPMC?

**Comment by ziggy73701** [comment]
As a update... I made the change to MariaDB a couple of days ago which pretty much resolved all my issues!! My SPMC would close over night, often crash and not re open or just get in to a loop. All of that has now stopped. System been totally stable since, sooo maybe worth a look!

**Comment by TweekDash** [comment]
Hi @ziggy73701 was the change you made from MySQL to MariaDB? I'm already using MariaDB 5 and have been forever.

Also what version of SPMC are you on?

**Comment by koying** [comment]
Could you detail which log produce which symptoms?

Yous basically should see
> 09:44:18.616 T:18446744072500848272    INFO: MYSQL: Connected to version 5.5.54-MariaDB

On each of them, and I don't see it in some

**Comment by TweekDash** [comment]
Sorry about that. This is what I can remember the symptoms of each of the logs showed.

"spmc old log firetv gen1 os5" worked great no problems, I did another scan for new content and then to see if the problem would occur I turned on debugging in GUI and rebooted the system

"spmc log firetv gen1 os5" went to splash screen for Loading Database showed the debug menu text on the top left, got past the splash screen but was a black screen with the debug menu jumping around slightly, then after hitting the back button on the remote that menu text starts to tile the screen more and more until most of the screen was covered with the same debug menu text. If I launch SPMC on that system now it does the same thing.

"spmc old log nvidia" goes to splash screen for Loading Database and stays there indefinitely.

"spmc log nvidia" goes to splash screen for Loading Database and stays there indefinitely I think I eventually force closed it through Android OS.

**Comment by TweekDash** [comment]
Not sure if this matters at all but here are some other notes:

My FireTVgen1 running FireOS3 and SPMC-16.4.2 is on the same network accessing the same DB with no problems. I planned on upgrading this one too but thought I would get the other system working first. If somehow having this system access the same DB could be causing issues I will upgrade ASAP (also open to downgrading the other SPMCs)

I upgraded the FireTV that I provided logs on to FireOS5 and to SPMC 16.7.1 and have been having these problems. I also installed Kodi 17.4 onto this system because I could not get SPMC 17.4a9 to scan in my sources for TV and Movies from my database. I connected to the shares fine but when I tried to set content nothing happened. Thus I wanted to run Kodi 17.4 on the same system so I can use a single add-on, if you think this could some how be causing issues please let me know. 

The nvidia shield worked fine on 16.4.2 for over a year, because I couldn't get SPMC 17.4a9 working I decided to load 16.7.1 + Kodi 17.4 like the system above. It worked fine at first and then after a crash would not get past the splash screen.


Sorry in advance for the long posts just want to provide as much background info as possible in case any of it is important.

**Comment by TweekDash** [comment]
Resolved: Ok, sorry this was a really stupid problem but I finally figured it out.

The problem was related to a setting under the Skin regarding: Startup Window
https://i.imgur.com/uWXdgeZ.png

I had it set to TV rather than Home Window and it caused the system to hang when loading.
