### ISSUE TITLE
[solved] SPMC data to external storage doesn't work

### ISSUE THREAD

**Issue by Kelso76** [koying/SPMC#1032]
Hi there! I just installed the spmc 17 alpha version 9 on my android box. I tried to move data on my external storage with the spmc_env.properties file but it doesn't work.
It worked on version 16 with the same strings. It trier to rénale it xbmc_env.properties but same résult. Even  with spmc.data= or xbmc.data= it doesn't work. I've tried every configation. Is it broke with spmc 17 alpha,or did i do something wrong ?
Thanks for the answer.

**Comment by koying** [comment]
Very likely something you do wrong, as I use it everyday.
Please paste the content of your (xbmc|spmc)_env.properties

**Comment by Kelso76** [comment]
Hey! Thanks for your answer. That's nice of you to take the time.
Si heure je the content inspiré the file:
xbmc.data=/storage/463E-A574/Android/data/com.semperpax.spmc17/files

**Comment by mLgz0rn** [comment]
is the "/com.semperpax.spmc17/files" present in your data folder on your storage?

**Comment by Kelso76** [comment]
Yes he is. And everything inside SPMC is written inside file/.spmc. I noticed the data transfer not working when I saw that everything was written inside this directory on my internal storage and not on the external storage where I copy/paste this directory

**Comment by mLgz0rn** [comment]
So nothing is getting written to your external storage?
It's working fine on mine, but I created a folder on my external storage called "xbmc_data"
So for me the path is xbmc.data=/storage/sdcard1/xbmc_data
Are you sure that you are using the correct name/path for your external storage?

**Comment by Kelso76** [comment]
Yes I verified many times that it was the right path. In fact it's the exact same file I used for version 16.7.1 except the com.semperpax I changed from 16 to 17

**Comment by mLgz0rn** [comment]
Well I might just gonna let koying take over here :p I got no idea then!

**Comment by Kelso76** [comment]
Thanks anyway :)

**Comment by koying** [comment]
No clue. Log might help...

**Comment by koying** [comment]
Oh, you don't happen to have a spmc_env.properties, do you?
It takes precedence over xbmc_env...

**Comment by Kelso76** [comment]
OK, so I turn log on, and restart spmc and then what do I do? What do you need?

**Comment by Kelso76** [comment]
It is the only file I have (spmc_env.properties)

**Comment by koying** [comment]
> OK, so I turn log on, and restart spmc and then what do I do? What do you need?

I need <SPMC_HOME>/temp/spmc.log

**Comment by Kelso76** [comment]
Ok so i have those two in a zip file :
[spmc log.zip](https://github.com/koying/SPMC/files/1281951/spmc.log.zip)
Hope it will help. And thank you for taking time to help me.

**Comment by koying** [comment]
> It is the only file I have (spmc_env.properties)

And you put it in "/sdcard", not "/storage/463E-A574", right?

**Comment by Kelso76** [comment]
Exactly, on the infernal storage

**Comment by Kelso76** [comment]
Internal*

**Comment by koying** [comment]
Maybe something peculiar with external storage, then. I will test...

**Comment by Kelso76** [comment]
Ok, but strange since it used to work with previous version of spmc

**Comment by koying** [comment]
Definitely work (on shield), so I'm clueless right now

```
xbmc.data=/storage/2C5E-D46A/Android/data/com.semperpax.spmc17/files
```
```
~/src/spmc-krypton $ adb shell ls -a /storage/2C5E-D46A/Android/data/com.semperpax.spmc17/files/.spmc
.
..
addons
media
system
temp
userdata
```

**Comment by koying** [comment]
If you're motivated, you can grab a logcat of when spmc is starting up, but it's quite a chore if you have no android hacking experience.

Assuming you don't know how, here seems a reasonably "easy" way to do it: https://wiki.lineageos.org/logcat.html

**Comment by Kelso76** [comment]
Ok so i'll try to do that later. Indeed i have zero expérience. I'll give it a try. 
If i succeed what do i do with it?

**Comment by koying** [comment]
Paste the resulting `logcat.txt` to https://pastebin.com/ and post the link here

**Comment by Kelso76** [comment]
It seems i won't be able to do that since my box is non rooted and can't be.
I'll try to see if there's something wrong on my external storage. Anyway i was thinking of buying an extra hdd to use the adoptive storage feature on android. Might be the solution

**Comment by Kelso76** [comment]
Thanks anyway.  Spmc 17a9 is working great. Fast And no bug

**Comment by Michelasso** [comment]
It's working on my Sony Bravia with Android 7.0 as well.

```
1|BRAVIA_ATV2:/sdcard $ ls -la /storage/B7C8-0905/Android/data/com.semperpax.spmc17/.spmc                                                                                          
total 224
drwxrwx--x    7 u0_a170  sdcard_r     32768 Sep  7 10:58 .
drwxrwx--x    4 u0_a170  sdcard_r     32768 Sep  7 10:58 ..
drwxrwx--x   11 u0_a170  sdcard_r     32768 Sep  7 10:59 addons
drwxrwx--x    2 u0_a170  sdcard_r     32768 Sep  7 10:58 media
drwxrwx--x    2 u0_a170  sdcard_r     32768 Sep  7 10:58 system
drwxrwx--x    4 u0_a170  sdcard_r     32768 Sep  7 10:58 temp
drwxrwx--x    9 u0_a170  sdcard_r     32768 Sep  7 10:58 userdata
```

I omitted the "./files" directory because I wanted to start from the first writeable folder, avoiding too much nesting.

Since it most likely has to do with write permissions, one way to debug  it is to learn about "adb shell" just a bit (for starting you just need to download the "adb" binary for your machine - Windows/Mac/Linux), put it in a folder, run it copying & pasting in here the output of

`adb shell ls -la /storage/463E-A574/Android/data/com.semperpax.spmc17/files`

together with the output of 

`adb shell "ps | grep spmc"`

with SPMC running. For example I get

```
adb shell "ps | grep spmc"
u0_a170   23949 1271  1246480 117556 SyS_epoll_ 00000000 S com.semperpax.spmc17
```

the id in "ps" (u0_a170 in my TV. It changes in every system) must match the one in "ls". No root is required. If you get any error then that's it. If the id are different you should delete the whole  
`/storage/463E-A574/Android/data/com.semperpax.spmc17` 
folder and start again.

Now, if I am allowed, a question: is there any way to migrate the current data to the new xbmc.data folder? Or I do have to reconfigure everything (again?).

**Comment by Kelso76** [comment]
Thanks for your help but I have a Xiaomi mi box, so how do i use those adb command?

**Comment by Michelasso** [comment]
adb works exactly the same with all Android devices. [Here](https://www.androidpit.com/how-to-install-adb-and-fastboot) there is a guide. It's for Android phones, but it's about the same in Android TV. The concepts are identical, the interface changes. The only thing is that, since we are not using the USB but the network, you'll have to run this command first on your computer:

`adb connect <IP address of your Mi Box/Television>`

after that you can run

`adb shell` 

or 

`adb logcat`

If one works so must do the other and you are all setup to provide the data required.

**Comment by Kelso76** [comment]
OK ! Thanks a lot. That's really helpfull

**Comment by Kelso76** [comment]
i cannot connect to the mi box : "unable to connect to 192.168.*.**:5555
that's the message i got

**Comment by Michelasso** [comment]
You have to enable "adb debug" first in the developer options, as described in the guide. Also to have the developer options showing you must click 7 times in Settings/Information/Build number. And in order to connect the computer and Mi Box must be in the same LAN (basically connected to the same router). Then at a certain point, after using adb from the computer, you'll get a popup window asking for permission. Click remember the choice and confirm.

**Comment by Kelso76** [comment]
there is no adb debug on the developer options, only USB debug. i enabled this one. my mi box and my pc are on the same wifi, but it doesn't work.
i have this message : unable to connect to 192.168.*.**/Television:5555: cannot resolve host '192.168.*.**/Television' and port 5555  host unknown (11001)

**Comment by ExSport** [comment]
Probably the easiest way is to install WIFI Debugging app from playstore:
https://play.google.com/store/apps/details?id=com.ttxapps.wifiadb&hl=en
EDIT: sorry lost link to non-root version, this one seems to require root...
Edit2: non-root examples:
https://play.google.com/store/apps/details?id=za.co.henry.hsu.adbwirelessbyhenry&hl=en
https://play.google.com/store/apps/details?id=calleestatus.innovidio.com.ipadressget&hl=en
https://play.google.com/store/apps/details?id=com.creativecub.adb&hl=en
https://play.google.com/store/apps/details?id=hwd.com.vn.adbconnect&hl=en

**Comment by Kelso76** [comment]
Thanks for the tip. Might try a non root version when I come home

**Comment by ExSport** [comment]
Non-Root version require you to enable TCPIP stack running by running:
**adb Tcpip 5555 (on PC - it means you have to connect box with PC)**
Not sure if your box can do it (try to switch between USB connection modes MTP/PTP/USB/... on your box)

**Comment by Kelso76** [comment]
Yeah that's what I saw.  it seems possible by what I read on internet but not sure. Will only know when I come home and try. Thank you anyway :)

**Comment by Michelasso** [comment]
Ok, my bad. I think I understand what is going on. The command "adb connect" must have ONLY the IP address. Like in this example:

`adb connect 192.168.1.20`

Just substitute "192.168.1.20" with the IP address of your box. "/Television" was to say that it could be the IP address of a Mi Box or of a TV. Also "USB Debug" should be the right option. In mine it is called "Debug ADB", which is more correct. But it's only a name, leave it on.

**Comment by Kelso76** [comment]
Ok so i managed to solve the issue. I plugged my hdd into my computer and deleted the Android folder. There was some files that I could not delete in the cache folder of the quasar add-on but I succeed following a little trick found on the internet. Then i plugged my hdd back to my mibox launched spmc, closed it and launched it again and it worked.
Thanks to everyone, you took the time to help me, guide me, and explain me things. It was really nice of you. Great community!

**Comment by gl2007** [comment]
Kelso76, can you please tell more about the "little trick" you mentioned? In my case, I am trying to use same external folder shared between Kodi 17.4 and two different versions of SPMC. Kodi works fine. Both SPMC versions crash and just quit. Only when I created a blank spmc_env.properties, do they start up correctly.

**Comment by Kelso76** [comment]
I don't know much but I am not sure you can share the same folder with 3 different installation.
For the little trick, I just deleted the files I could not delete in the cache folder of quasar by opening the path in a zip software and renaming it inside the software. Then I was able to delete them on my external storage. Hope it help
