### ISSUE TITLE
SPMC Krypton (latest version) audio sync.

### ISSUE THREAD

**Issue by zabba8** [koying/SPMC#1049]
The audio is quite a bit behind on HD channels .

**Comment by JFG90** [comment]
Strange as I mine is fine on the latest version..

**Comment by zabba8** [comment]
Strange but true. Ive added some advanced settings where it sets the latency delay to zero and it seems to have helped my issue.

**Comment by tmaniac** [comment]
would you mind sharing those settings?

**Comment by zabba8** [comment]
I'll try, it wouldn't let me post it on the code thread.

<?xml version="1.0" encoding="UTF-8" ?>
<advancedsettings>
  <video>
    <latency>
      <delay>0</delay>
      <refresh>
        <min>23</min>
        <max>24</max>
        <delay>0</delay>
      </refresh>
    </latency>
  </video>
</advancedsettings>
