### ISSUE TITLE
HDR on android tvs

### ISSUE THREAD

**Issue by roafhtun** [koying/SPMC#1052]
My tv supports HDR its Sony x800d, in spmc is HDR supported ? Because in tv picture settings it shows HDR logo if the HDR content is playing, but the colors are washed out, so I'm wondering is it an issue ? Or still not supported ?

**Comment by illgodson** [comment]
It’s definitely supported. I believe you have to enable Surface Codec in video acceleration. If I don’t have it enabled my tv don’t flip to HDR so I only enable that when needed.

**Comment by roafhtun** [comment]
Yes it is enabled I followed this instruction and settings
https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-Android-devices-(other-than-Nvidia-Shield)

I get the HDR signal my tv picture setting shows hdr logo, but the color is washed out so I think it gets the signal but not displaying it or smth, do you get washed out ones also?

**Comment by illgodson** [comment]
Sorry should Note I’m on SPMC version 16.7-01.

**Comment by roafhtun** [comment]
I see, I'm on the latest one 16.7.1

**Comment by illgodson** [comment]
No they seem on par with other HDR content I watch via Amazon or Netflix. I’ll attach a pic of the movie Lucy in HDR...know it’s not exactly scientific but just trying to give a general idea. 

https://i.imgur.com/DmZO4Gy.jpg

**Comment by roafhtun** [comment]
I see that looks nice, mines are like really washed out, I'll give it a try with my PS4 pro via USB and compare again i don't know if it's the content or the tv app.

**Comment by illgodson** [comment]
Just wondering which device you running SPMC on? Do the colors look right when watching Netflix HDR or an HDR BR?

**Comment by roafhtun** [comment]
It's running on Sony x800d android tv, it's been fixed, turning on advanced contrast enhancer fixed it day and night difference, it's a lot better now.

**Comment by roafhtun** [comment]
And yes colors do look right in Netflix and amazon.
