### ISSUE TITLE
New SPMC 17 Alpha?

### ISSUE THREAD

**Issue by vader913** [koying/SPMC#1053]
Just wondering if there is a new alpha out...Thank you Mr. Koying for your hardwork.

**Comment by maxiauer** [comment]
Latest Alpha are published in this post
https://github.com/koying/SPMC/issues/936

I believe latest one is A10

Max

**Comment by philsqueak** [comment]
Kodi nightlies now 17.5RC1.
Expect @koying is aware of this, maybe that's why delay with new build/s ?

**Comment by awbuxton** [comment]
Maybe he's got a life and doesn't just exist for your purpose only!!!!!!

**Comment by philsqueak** [comment]
awbuxton
Not sure what you are saying? what a strange comment!
I was pointing out that he was possibly just awaiting a 17 final from Kodi's side.

**Comment by awbuxton** [comment]
It was meant for @vader913 who chose to open a new thread for that pointless comment
