### ISSUE TITLE
SPMC 17 alpha 10/11 - no Dolby Digital via HDMI ARC

### ISSUE THREAD

**Issue by MHC2000** [koying/SPMC#1063]
Hi, 

testing SPMC 17 on a Philips Android TV (android 6.0).
Audio passthrough via RAW does only provide 2.0 audio via HDMI-ARC.
Same settings on 16.7.1 did work without a problem an DD/DDPlus/AC3 was available.
IEC crashes completely and is not useable.

Tested with version 17.4a10 and 17.4a11

Settings:

- Audio output device: Android, RAW Passthrough
- Number of channels: 7.1
- Output configuration: Best match
- Stereo upmix: no
- Maintain original volume on downmixing: yes
- Boost centre channel when downmixing: 0 dB
- Resample quality: High
- Keep audio device alive: 1 min
- Enable audio DSP processing: no
- Enable passthrough: yes
- Passthrought output device: Android, RAW passthrough
- Dolby Digital: yes
- Dolby Digital Plus: yes
- DTS: yes
- DTS HD: yes

Regards

[spmc.log](https://github.com/koying/SPMC/files/1350342/spmc.log)

**Comment by ghost** [comment]
Do you have 7.1?
Try turning off dts and dtshd. 

I'm getting dd+ on 11

**Comment by MHC2000** [comment]
Yes, I do have 7.1.
Tried your settings with RAW and IEC, but still only Stereo.

**Comment by Michelasso** [comment]
Try also with "Number of channels 2.0". And all DTS must be  off as already suggested.

PS: I think I still get only DD 5.1 on my Bravia with Android 7.0, though.

**Comment by MHC2000** [comment]
Thanks for the advice.
It works with 2 channels.

Activating DTS or DTS-HD has no affect on the output of DD. Do have always DD if I'm activating it or not.
IEC crashes, but this also didn't work at 16.7.01. So no change in this.

Thought I tried it with other channel numbers before, but now it worked.

I'm closing the issue.
Thanks for the help!
