### ISSUE TITLE
SPMC 17(A11) - Back button function

### ISSUE THREAD

**Issue by renehav** [koying/SPMC#1066]
Hi, a long press of the back button at nVidia shield Tv remote starts PIP function in current build (A11). For me, PIP is useless and buggy. So I would prefer the same functionality like it is in SPMC 16. So - short back button press=stop playback, long press=step back. Is there any way to make it work like it is in SPMC 16?

**Comment by CiNcH83** [comment]
Edit [keyboard.xml](https://github.com/koying/SPMC/commit/302e50f28f43267657004a5756003293763e70b7#diff-e0049d392fd1368b3ce8d79c3885130d).

**Comment by renehav** [comment]
Thanks for your advice. In attached zip, there is my edited keyboard.xml with back buton function from native Kodi. Might be useful for someone else.
[keyboard.zip](https://github.com/koying/SPMC/files/1362068/keyboard.zip)

**Comment by ghost** [comment]
hey can anyone help me please im trying to turn off pip function i used @renehav keyboard file it works great but it overrides my keymapping that i did with the keymap editor add-on from the kodi repo dose anyone knows if i could edit the pip long press on the keymap editor add-on

**Comment by hstamas** [comment]
@Fuckuptheworld13 its been a long time since Ive used SPMC but I believe the attached is what I used to get rid of the PIP functionality and restore the 2 different back modes.

Give it a try
[remote.xml.zip](https://github.com/koying/SPMC/files/2134309/remote.xml.zip)
