### ISSUE TITLE
"Can't find next item to play" playlist error message when using SALTS add on and library mode

### ISSUE THREAD

**Issue by idunkle** [koying/SPMC#108]
Firstly, great work with this. Just got shield tv and SPMC works great

Only one issue

I use SALTS as my go to add on for TV
Within that to make easier for wife, I intergrate its subscriptions with my library and enable auto play

Under standard kodi, selecting an episode plays it
Under SPMC I get the "can't find next item to play" message 

To make matters "stranger" if I bring up context menu, go to salts menu and select "choose source" it goes off and finds me all sources available.

**Comment by ghost** [comment]
I use SALTS fine on SPMC and have just recreated your situation and it works for me,

I dont think koying will help with addon specific issues. You may be best off going to the SALTS forums and asking TK, he will require a log to help you.

**Comment by idunkle** [comment]
Cheers for recreating issue and saying works. Curious.

**Comment by koying** [comment]
Yep. Sorry, but I personally don't use addons (besides Youtube) nor PVR, so cannot really help there

**Comment by idunkle** [comment]
No problem. It's a help that someone has confirmed appears local to me so will have a reinstall

**Comment by kalrez** [comment]
Having same or Similar issue with Library integration.
I can play Movies & TV shows directly from 1Channel, SALTS, Specto.
Adding the exact same Movies/TV shows to Library Integration They will not PLAY .  
Pop-Up shows  "can't find next item to play" 
Looking at my Error Log I see the following ERROR:  bool CDVDPlayer: Open Demux Stream

& ERROR: Playlist Player: Skipping unplayable item: 200 [videodb://tvshows/titles/2/-1/241?tvshow=2

Don't know if this is related or not
