### ISSUE TITLE
Beta Program based on 17.5?

### ISSUE THREAD

**Issue by maxiauer** [koying/SPMC#1080]
Hi Koying

I was wondering if it's possible to launch a Beta version of SPMC based on Kodi 17.5  The A11 seems quite stable, and a beta program would allow an easy update until you launch the final release.

Thanks !!!!

Max

**Comment by djstx2003** [comment]
Kodi went to 17.5.1 build officially. 17.5 had a problem.
i'll be happy to test a build based on Kodi 17.5.1

**Comment by maxiauer** [comment]
Koying already launched alpha based on 17.6

http://download.semperpax.com/spmc/android-arm/?C=M;O=D
