### ISSUE TITLE
Request: re-sync SPMC code with Kodi 17.6

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#1103]
@koying 

Would you please update the 17.x alpha 11 to 17.6 Kodi codebase? 

Specifically, I am hoping that the 7.1 audio fixes address some issues I am experiencing.

**Comment by rbronco21** [comment]
I'd like to see if this fixes an issue I am seeing with my FireTV 2, too. Specifically, I can enable MediaCodec (Surface) in Kodi and get near perfect 1080p24 playback. In SPMC, I get lots of skipped frames. With MediaCodec (Surface) disabled in both, I get dropped frames, but not nearly as many.

[spmc.log](https://github.com/koying/SPMC/files/1484504/spmc.log)
[kodi.log](https://github.com/koying/SPMC/files/1484505/kodi.log)

**Comment by classicjazz** [comment]
@Koying 

Thank you.

**Comment by rbronco21** [comment]
Does this mean it's in work? Don't see any change on the alpha thread. Sorry, new to github.

**Comment by classicjazz** [comment]
http://download.semperpax.com/spmc/android-arm/SPMC-spmc-krypton-2a41374-armeabi-v7a.apk
