### ISSUE TITLE
[Feature Request] Optional back button on home doesn't minimise SPMC

### ISSUE THREAD

**Issue by Tazoz** [koying/SPMC#111]
I use my Wetek Core solely for SPMC. When I'm deep in a menu, I click the back button a bunch of times to get me back to the home screen quickly. Sometimes this results in me minimising SPMC and falling back to the launcher.

Is there a way or can there be one developed so that I can stop the back button from minimising SPMC?

As a side-note, I noticed some discussion of a launcher, would this handle what I've described?

**Comment by koying** [comment]
You can long-press back to get to the home screen directly

**Comment by Tazoz** [comment]
Thanks for getting back to me Chris. I was more concerned with non-techy family accidentally pressing the back button whilst on the home screen and minimising out of SPMC. Either way, thanks for looking into this.

**Comment by mjbxx** [comment]
I recall in the past that long-pressing the back button would throw you out of SPMC. I believe the Isengard version fixed that issue. In any event you would have to hit the back button twice to mistakenly minimize out of SPMC. I believe that the way SPMC handles minimizing should stay as is.

**Comment by Tazoz** [comment]
No worries. I just used the keymap editor Addon and set the first page command to the back button. Hitting the back button no longer closes SPMC, it just sets the focus to the first menu item. It's not as clean as Kodi on Android but it does the job. 

Thanks.

**Comment by koying** [comment]
https://github.com/koying/SPMC/wiki/How-to-disable-the-%22double-back-on-home-to-minimize%22-feature
