### ISSUE TITLE
HDR not engaging with 17.6-alpha1 and can’t get back to Alpha 10

### ISSUE THREAD

**Issue by CLFNole** [koying/SPMC#1113]
I upgraded to the latest Alpha 17.6-alpha1 but noticed HDR wasn’t engaging and went to es file explorer to revert back to 17.4-alpha10 but I can’t get it to install. Keep getting “app not installed the package appears to be corrupt”. Any ideas?

**Comment by barenaked** [comment]
Did you enable surface decoding?

**Comment by CLFNole** [comment]
Oh yeah everything is setup correctly. Doesn’t engage for some reason. This also happened with an earlier version. Had uninstall everything then reinstalled Alpha 10 and HDR is working again.

**Comment by byalon** [comment]
Hi, where can I get an SPMC 17.x alpha or beta?
Thanks,
Benny

**Comment by koying** [comment]
Fixed in 17.6a2

**Comment by CLFNole** [comment]
Thanks Chris, it does now engage HDR but quick question...have you ever looked into the buffering issues since 17.4 alapha11?  17.6alpha2 seems to have the same 4K buffering issues that 17.4 alpha10 didn’t. Running some tests but it definitely seems to be different in some way.

**Comment by CLFNole** [comment]
Yeah not sure why but with 17.4 alpha10 I get virtually no buffering with 4K HDR but any starting with 17.4 Alpha11 to 17.6 Alpha2 I get a lot of buffering.

**Comment by satwise** [comment]
Agreed on the 4K buffering, and thinking back I believe it does align with
stepping from 17.4a10 through 17.6a2.  I also have issues with my HDHomeRun
PVR client stuttering video, but the client plays fine.  I have weak OTA
signal, so SPMC buffering formerly allowed me to receive more stations vs
the client itself, but no more.  My 4K HDR collection no longer triggers
HDR when steamed over the network.
