### ISSUE TITLE
SPMC for API15

### ISSUE THREAD

**Issue by scmonline1** [koying/SPMC#1115]
I am really thankful to you for SPMC as I used to face lot of problems with XBMC/KODI that were gone with installation of SPMC.
I have a old Android box (ICS-4.0.4) and SPMC 13.4.0 works great with my box but now a days I face lot of issues with incompatibility for dependencies. 
Is it possible to get a higher version of SPMC work with API15. 
Can you please help?

**Comment by djcasual** [comment]
Sorry, but that's not possible. Support for API 21+ only (Android 5.0+) started on version 16.5.0.

16.5.0 (2016/11/30):
CHG: API 21+ (Android 5.0) only, sorry.

You'll need to upgrade your hardware, or go to 16.4.2 which would be the last version to possibly support API 15.

**Comment by koying** [comment]
API 15 is really old. 
Kodi/SPMC 14 is the last version supporting it, iirc.

**Comment by scmonline1** [comment]
Thanks
