### ISSUE TITLE
17.6a2 - strange message when starting the app

### ISSUE THREAD

**Issue by troelshartmann** [koying/SPMC#1129]
When I start the app on my Shield I get:

SPMC will start capturing everything that's displayed on your screen. 

                                                                                CANCEL START NOW.

It looks like a message from the Shield rather than the app but what does this mean?

**Comment by koying** [comment]
It means you enabled https://github.com/koying/SPMC/wiki/How-do-I-get-Hue%2C-boblight%2C-hyperion...-to-work-with-Mediacodec-Surface%3F
