### ISSUE TITLE
SPMC cannot delete movies via app

### ISSUE THREAD

**Issue by Dorko** [koying/SPMC#1130]
When I longpress a movie folder on the nvidia shield SPMC app I no longer see "delete" option.
The user I use to connect have read/write access.

Is this a setting in spmc anywhere? (I cannot find any)

Thanks in advance!

**Comment by Kr1ss-XD** [comment]
In Krypton, go to Settings (cog wheel on the home screen), _Media_, open the _General_ tab and make sure that the settings level is set to _Advanced_ or higher. There's an option to _"Allow file renaming and deletion"_.

In case u using Jarvis, this option is located at _System_, _System_, _Appearance_, _File Lists_, while the settings level must be _Standard_ or higher to have it available.

**Comment by Dorko** [comment]
Super!!! The Jarvis option were valid.
I can now delete again...Thanks for your support!!
