### ISSUE TITLE
SPMC Krypton Compile Error

### ISSUE THREAD

**Issue by mo123** [koying/SPMC#1132]
When building SPMC you get this compile error

config.status: creating xbmc/platform/android/activity/Makefile
config.status: error: cannot find input file: `xbmc/platform/android/jni/Makefile.in'
make: *** [../../../..//libSPMC.so] Error 1

That folder doesn't exist since only libandroidjni exist in tools/depends/target.

The Android readme is also outdated, can it be updated?
Says to use NDK 12b but it's setup for NDK 14b in tools/buildsteps/defaultenv

**Comment by RuralHunter** [comment]
I encountered the same error. Is it resolved?
