### ISSUE TITLE
"error.Cannot download obb." latest aarch64 build.Obb was placed manually on right folder...

### ISSUE THREAD

**Issue by sammarbella** [koying/SPMC#1140]
I downloaded the apk and placed the obb under [0]/android/obb/com.semperpax.spmc1**7**

Install apparently went fine but once i launch the app it shows the error:

"Error

Cannot download obb"

I tried adding the file before installing the apk and after (creating spmc subfolder under /android/obb/) with same result.

App has storage access right.

Tried on my Samsung S8+

I will try later on my Shield Tv as i saw it has his own separate folder and don't mess with v16 builds.

**Comment by VDRrulez** [comment]
mv  SPMC-spmc-krypton-4993870-aarch64.obb  main.176002.com.semperpax.spmc17.obb
adb push  main.176002.com.semperpax.spmc17.obb  /sdcard/Android/obb/com.semperpax.spmc17/

**Comment by sammarbella** [comment]
I see you renamed the file and then moved it to his spmc subfolder under /obb and that was the solution. :)

Apk was looking a differently named obb file than the one on repo.

I don't need to use adb or any terminal commands to move files around, device is rooted and file manager is able to do it without problem.

Thanks!
