### ISSUE TITLE
Can't use Music shortcut

### ISSUE THREAD

**Issue by catfish66** [koying/SPMC#116]
Buenas Dias,
                        Installed SPMC v16 on my Minix Neo U1 yesterday. I normally will make shortcuts for Radio add on by saving to favorites (Amber skin). Not only could I not save to favorites, I found myself unable to access through the music shortcut or through the music add ons under the add ons shortcut. Any ideas as to why this is happening and maybe a solution. Other than that so far so good.........my Real Debrid seems to work better in the sound department(HD Playthrough).  Muchas Gracias

**Comment by koying** [comment]
No crystal ball, here. Include logs next time.
