### ISSUE TITLE
SPMC 17 (Krypton) Deletion

### ISSUE THREAD

**Issue by Blurayx** [koying/SPMC#1167]
SPMC 17 (Krypton)
Allow file renaming and deletion option not working

**Comment by RolandGoud** [comment]
I can confirm this. (although I thought it was my NAS preventing this)

**Comment by Blurayx** [comment]
Thanks!!

**Comment by Jelf10** [comment]
i'm on 17.6a2 and deletion works. Which build are you on?

**Comment by Blurayx** [comment]
Alpha1 64bit.  I thought I was on Alpha2 64 bit.. deletion now working.

Thanks
