### ISSUE TITLE
TMDB scrapper is broken again

### ISSUE THREAD

**Issue by Fotospecht** [koying/SPMC#1171]
Since a couple of days, the MovieDB Scrapper istn't working anymore.
Please fix, and thanks in advance !

`00:07:09.331 T:138596529232   ERROR: CCurlFile::Open failed with code 404 for https://api.tmdb.org/3/movie/tt5866930::de?api_key=ecbc86c92da237cb9faff6d3ddc4be6d&language=
00:07:09.331 T:138596529232   ERROR: Run: Unable to parse web site`

**Comment by tankalf** [comment]
Yes, I confirm.

It doesn't work anymore. Nvidia Shield with last official SPMC release.

**Comment by ptijoe34** [comment]
Hello, 
I also confirm, same issue with last official Spmc release on Nvidia Shield pro

**Comment by grummel2005** [comment]
and please fix the show of rating in film list too - thx

**Comment by uhnonuhmuhs** [comment]
Universal Movie Scraper doesn't seem to work for me either. Not sure if that's just me, though.

**Comment by tankalf** [comment]
Still no way to fix this issue?
Is it possible to download another add-on or modify it like last time?

**Comment by BigOkie** [comment]
I'm on version 16.7.2 and I've been using the Universal Scraper almost exclusively for the last six months.  Works great.

**Comment by shatpav** [comment]
Same issue about a week. Scrapper does not download plot, fanart and maybe something else. Kindly ask you to fix the issue. I'm using Universal Scrapper with tmdb configured inside for the movies. Thank you.

**Comment by Fotospecht** [comment]
I got it fixed by using the same method as in #1108

**Comment by grummel2005** [comment]
@Fotospecht - what do you mean???
at the end of the thread you are asking for help :)

**Comment by Fotospecht** [comment]
Download the 2 files:
http://mirrors.kodi.tv/addons/jarvis/metadata.common.themoviedb.org/metadata.common.themoviedb.org-3.1.1.zip
http://mirrors.kodi.tv/addons/jarvis/metadata.themoviedb.org/metadata.themoviedb.org-4.1.2.zip

Extract the addon.xml file from each zip.
Edit the addon.xml files and prepend "67" to the version number, so that the versions are 673.1.1 and 674.1.2
Update the zip files with the modified addon.xml files.

Install both zips.


BTW this also fixes the film ratings.

**Comment by shatpav** [comment]
It works for me. Thanks a lot! Hope official update will be working soon as well.

**Comment by koying** [comment]
Please someone test http://download.semperpax.com/spmc/android-arm/SPMC-16.7.3-spmc-9cc7fff-armeabi-v7a.apk to confirm the fix

**Comment by grummel2005** [comment]
thx koying...
but when we can expect to get back the showing of the ratings of the films (1 to 5 or the average - not the age-rating)
since a few versions it is not shown anymore
would be nice to get it back again
thx

**Comment by Fotospecht** [comment]
I tested the aarch64 apk on my Shield and it is working fine. Thanks for the fix.
