### ISSUE TITLE
[Question] Launcher APK

### ISSUE THREAD

**Issue by beschoenen** [koying/SPMC#119]
What is the difference between the default apk and the launcher apk?

**Comment by koying** [comment]
http://bfy.tw/3sMY

**Comment by beschoenen** [comment]
I know what an android launcher is. But it's not possible to use it on the Shield TV, right?

**Comment by koying** [comment]
See http://forum.xda-developers.com/nexus-player/general/how-to-set-default-launcher-marshmallow-t3227812
Never tried myself, though

**Comment by beschoenen** [comment]
Can confirm that this works and SPMC will become the default launcher.
`adb shell pm hide com.google.android.leanbacklauncher`
But there are no power option, so it's kinda useless atm.

**Comment by koying** [comment]
You need to be a system app to properly handle power options, so that's a no-go.
I'll re-add power options for rooted devices, though...

**Comment by beschoenen** [comment]
My Shield TV is rooted, so i'll be looking forward to it.

**Comment by koying** [comment]
You can try http://download.semperpax.com/spmc/android-arm/SPMC-20160320-d4484e7-rooted_reboot-armeabi-v7a.apk
Untested (no rooted device wired :) )

**Comment by beschoenen** [comment]
I'll give it a try

**Comment by beschoenen** [comment]
- suspend works perfectly
- shutdown works too, though the screen will freeze until the system turns off
- reboot, same as shutdown

**Comment by bjgood** [comment]
Will the launcher apk work with a Firestick or only works on Android phones and tablets?

Thank you.
Bob

**Comment by koying** [comment]
Should work on rooted aftv, but not without rooting.
Blame Amazon for wanting them to be sure you see their Prime stuff ;)

**Comment by ErAzOr2k** [comment]
Is it possible to add "Reboot to Recovery" and "Reboot to Bootloader" for rooted devices?

**Comment by beschoenen** [comment]
I'm not getting the power options with version 16.2.1 on update 3.1

**Comment by pr39th** [comment]
Hello koying, did you have the latest update with the power options? Thanks for your help and support.

**Comment by Nerto** [comment]
Is there any trick to forced the shutdown menu on a nvidia shield with update 3.1?

**Comment by beschoenen** [comment]
Forcing the menu wouldn't help, SPMC just isn't allowed to shut down the device without root

**Comment by Nerto** [comment]
Thank for the answer, but my device is rooted, but as far I understand the nvidia 3.1 update changes something.

**Comment by beschoenen** [comment]
It's a problem with SPMC, I tried sending a shut down command to my Shield TV via Yatse but that didn't work, so we'll have to wait for Koying to fix it.

**Comment by beschoenen** [comment]
@koying any update on this?

**Comment by viceversaco** [comment]
@beschoenen I suggest using a android reboot app (root) to accomplish this.  Try holo reboot.  Allows you to shutdown and reboot (normal, bootloader, recovery)

**Comment by beschoenen** [comment]
@vicelversa Well, that wouldn't really be convenient. The idea is that I could use SPMC as my launcher, but because SPMC doesn't have power options I can't turn off my Shield TV.

**Comment by viceversaco** [comment]
@beschoenen you can still add the android reboot app to SPMC for easy access.  This is the same as I currently do.  I actually have my reboot app nested inside my SPMC power menu which works fine.

However, I do agree that this sort of functionally would be desired to have baked into SPMC (at least for root users).
