### ISSUE TITLE
[droid] Hangs on wake from suspend

### ISSUE THREAD

**Issue by elmerohueso** [koying/SPMC#12]
The Suspend command successfully detects root and CEC availability, sends the proper commands, and suspends device.  However, SPMC is perpetually "busy" when the device is woken from suspend.

**Comment by elmerohueso** [comment]
Debug log at http://pastebin.com/UV8R51BJ.
Applicable part:
08:44:26 T:2006545480   DEBUG: ------ Window Init (DialogButtonMenu.xml) ------
08:44:26 T:2006545480    INFO: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY
08:44:26 T:2006545480   DEBUG: Load DialogButtonMenu.xml: 17.76ms
08:44:26 T:2006545480   DEBUG: Alloc resources: 19.20ms  (18.04 ms skin load)
08:44:26 T:2006545480   DEBUG: Unfocus WindowID: 10111, ControlID: 2
08:44:26 T:2006545480   DEBUG: Unfocus WindowID: 10000, ControlID: 20
08:44:28 T:2062553392  NOTICE: Thread Timer start, auto delete: false
08:44:28 T:2062553392   DEBUG: Thread Timer 2062553392 terminating
08:44:28 T:2006545480   DEBUG: Unfocus WindowID: 10111, ControlID: 6
08:44:29 T:2006545480   DEBUG: ------ Window Init (DialogBusy.xml) ------
08:44:29 T:2006545480   DEBUG: Window DialogBusy.xml was already loaded
08:44:29 T:2006545480   DEBUG: Alloc resources: 0.03m
08:44:29 T:2006545480   DEBUG: ------ Window Deinit (DialogButtonMenu.xml) ------
08:44:34 T:2006545480   DEBUG: bool CWinSystemEGL::CreateWindow(RESOLUTION_INFO&): Created surface of size 1280x768
08:44:34 T:2006545480  NOTICE: GL_VENDOR = Qualcomm
08:44:34 T:2006545480  NOTICE: GL_RENDERER = Adreno (TM) 320
08:44:34 T:2006545480  NOTICE: GL_VERSION = OpenGL ES 3.0 V@53.0 AU@  (CL@)
08:44:34 T:2006545480  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.00
08:44:34 T:2006545480   DEBUG: GLES: Extension Support Test - GL_NVX_gpu_memory_info NO

I see the init call for the shutdown menu, then the init for the busy signal and the shutdown menu is wiped, but the busy signal is never wiped.

Could this be due to the placing of the "return" calls within "bool CAndroidPowerSyscall::Suspend()"?  Should we move the "return" call to the end, after the "if" statements?

Unfortunately, I don't have a compile environment currently set up to test fixes.

**Comment by koying** [comment]
I bet you have to call CPowerManager::OnWake() on resume, somehow.

**Comment by koying** [comment]
Looks like you'd just have to do `m_OnSuspend = true` in CAndroidPowerSyscall::Suspend().

**Comment by koying** [comment]
Please test http://www.semperpax.be/owncloud/public.php?service=files&t=d21db6a9df15f7132bac4e7ce8c54a2a

**Comment by elmerohueso** [comment]
Perfect! Works as expected.

**Comment by elmerohueso** [comment]
I'm setting a compile environment so I can better test code before I checkin.  Are you using the Ubuntu 12.04, SDK r23, and NDK r9 from the android.readme?  Are your android.readme and depends readme updated for SPMC?

**Comment by koying** [comment]
I'm using Mint, r9b and I don't remember which SDK ;)

**Comment by elmerohueso** [comment]
Any chance you could update docs/android.README and tools/depends/README
with your current setup?

**Comment by koying** [comment]
It's just what I happen to use. What is in the README is still valid...
