### ISSUE TITLE
16.1.2 Audio Sync Issues (with logs)

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#120]
SPMC 16.1.2 NVIDIA SHIELD TV - RAW PT
AVR: Yamaha RX-V677 with Panasonic GT50 Plasma
GUI: Limited to 1080p GUI
Channels: 7.1 set (5.1 plugged into AVR)
Refresh rate switching: On Start / Stop

AC3 384kbps - video starts well with audio out, video slows down briefly, then rapidly speeds up and syncs with audio well after 3 seconds total. - http://xbmclogs.com/poq2josrj

AC3 640 (4K downscaled to 1080p) - same deal as 384kbps - http://xbmclogs.com/pciquhrc7

DTS 1500kbps - audio 0.5s in front for 2 seconds, then syncs well - http://xbmclogs.com/pynstxfjw

DTS-HD MA - audio out intially by 0.1s, then rapidly speeds up and catches up after 3s have passed - http://xbmclogs.com/pa7qnv2qc

TrueHD - same as DTS-HD MA - http://xbmclogs.com/p4ewabzwf

Haven't tried IEC PT yet but will update accordingly if experiencing same issues.

**Comment by koying** [comment]
Am I ready correctly that you actually have no issue, passing the initial sync? ;)
Or is the initial sync the issue?

**Comment by ghost** [comment]
The issue is that the sync is not immediately correct on start of playback, it corrects itself after a few seconds. It's a bit distracting when you see 2x the video speed when the audio catches up. Haven't experienced it on your latest adddroidPT Kodi build...

**Comment by Nzchocs** [comment]
Hi Koying, just in case you missed my post and if this helps, this truehd track is about 4 seconds out of sync. I have similar problems with other truehd tracks too but interestingly not with dts HD tracks. 

http://xbmclogs.com/paxh8qnus

Thanks again

**Comment by ghost** [comment]
Different issue to mine. Suggest opening a different Issue.

**Comment by Nzchocs** [comment]
No worries at all, Dan,  thanks!

**Comment by drunkenprozac** [comment]
Hi Dan,
Just a thought as I was having the stutter on playback while it syncs, do you have 'pause on refresh rate switching' set?
I had mine set to 2 seconds but once I removed it I get no stutter at the beginning.
