### ISSUE TITLE
With Emby add-on: Blank video info dialog when opening library

### ISSUE THREAD

**Issue by lockdown571** [koying/SPMC#123]
Noticed an odd issue when using Emby (or PlexKodiConnect) in conjunction with skins OTHER than Confluence. When you go to open a library, a blank video info dialog appears. Pressing play or back then takes you to the library. This does not happen with the regular version of Kodi.

**Comment by koying** [comment]
No clue, no addon support and no debug log.
All recipe for an invalid tag ;)
