### ISSUE TITLE
Koying can this be fixed ?

### ISSUE THREAD

**Issue by ruppert10** [koying/SPMC#129]
hi koying there is a issue with using spmc ( any version) with the community portal add on the issue is when you try to use there maintenance section to make a backup copy of spmc you get the famous red x with a script error and you can't make a backup copy of spmc because you have no way to get to the backup settings you need but this works fine with kodi versions from 14.2 on but not any spmc versions they all get the script error on Facebook the community portal devs say it is a known issue with the spmc fork only and not there add on or kodi because kodi works just fine with there add on when you try to make a backup copy using kodi and only the spmc fork gives this script error ? can you look into this issue I know you are soooo busy but can this be looked at ... p.s.
you do a fantastic job just really awesome work on this add on thank you for all of the hours that turn into days out of your life that you take to try to get this add on just perfect for everyone thank you for everything you do

**Comment by koying** [comment]
No addon support here.

**Comment by ruppert10** [comment]
I'm very sorry koying I had no idea it's my first post I just joined github to ask about this issue  I hope that my issue can be fixed in a future version of spmc at some point again thank you for all that you do
