### ISSUE TITLE
Audio sync using passthrough on AML hardware

### ISSUE THREAD

**Issue by bjorn1981** [koying/SPMC#13]
The AESinkAUDIOTRACK.cpp contains code where latency gets determined to 0.250 if the hardware supports amcodec. On Gotham this isn't necessary if passthrough is used, so !m_passthrough needs to be added to the logic.

https://github.com/Matricom/xbmc/commit/317b217c6453a18a4cbdac8f88df5e4d5821622b

**Comment by bjorn1981** [comment]
PR https://github.com/xbmc/xbmc/pull/5221

**Comment by koying** [comment]
Closing this following 5221
