### ISSUE TITLE
No surround sound on Odroid C2 (LPCM or passthrough DTS/AC-E/Etc.)

### ISSUE THREAD

**Issue by jbloch** [koying/SPMC#135]
Hi. We recently got an ODROID C2 with the hope of running SPMC. It works fine for stereo audio, but fails to produce surround sound. I'm running the latest version of SPMC (16.1.2) atop the latest Android release from ODROID (Android 5.1.1 (v1.1)). The details of our experience, including log file, are reported here, on the ODROID forums: http://forum.odroid.com/viewtopic.php?f=141&t=19987 . I realize that this is likely an ODROID issue rather than an SPMC issue, but I'd love to have the benefit of your expertise. Thanks!

**Comment by koying** [comment]
Odroid forums are the right place.
No idea on the specifics the C2
