### ISSUE TITLE
[Feature Request] Speech to text 

### ISSUE THREAD

**Issue by ErAzOr2k** [koying/SPMC#136]
Hi,

is it possible to integrate Speech to text by Android API?
Would be amazing to use my microphone as input, when SPMC keyboard opens.

**Comment by ErAzOr2k** [comment]
Thank you for adding speech recognition support :)
Could one thing be changed: insted of opening speech recognition by pressing the context button, is it possible to bring this feature up by pressing the microphone button (when soft keyboard is open)?

**Comment by koying** [comment]
Ah, it's here ;)
Yep, will be in 16.2.1

**Comment by phatboyj** [comment]
**How exactly can I make use of the text to speech function?**

I'm using an older fly/mouse that has audio input but does not have a dedicated mic button.

So for me to use it there would have to be some way to invoke the voice action via  the onscreen keyboard or by mapping a key, "some how" to my fly/mouse/keyboard

I could really use some help here. I would very much like to make use of this functionality.

So any helpful feedback,  would be greatly appreciated.

I should probably add that I'm running SPMC on a BB2-Pro  s912 android box with Kodi No Limits Build installed.

Thanks In advance,
                                phatboyj

...
.

**Comment by koying** [comment]
The IP button on the SPMC soft keyboard has been "re-purposed" so that pressing it should invoke speech-to-text
