### ISSUE TITLE
System screensaver preview not working. Is it supposed to?

### ISSUE THREAD

**Issue by rfgamaral** [koying/SPMC#139]
I like the idea of having SPMC screensaver as the system one so I can use daydream. But when I press "preview", this doesn't work. Is this supposed to or is this a bug?

**Comment by war59312** [comment]
Preview nor when set to "System? works for me. Just blank white screen on my Shield.

**Comment by koying** [comment]
You'd have to wait for the daydream delay yo _maybe_ see the "preview".
Not really important...
