### ISSUE TITLE
SPMC addon

### ISSUE THREAD

**Issue by hinball** [koying/SPMC#148]
I got a fresh install of SPMC 16.1.2 on nvidia shield TV , I found that there are youtube add on that i cannot uninstall, is that the default add on for SPMC? , coz I cannot uninstall in anyways , I cannot saw any addon in folder .smpc/addon/ or .spmc/userdata/

**Comment by ruppert10** [comment]
I have a BIG issue with this as well  but koying says you can't talk about add-ons here just type in Google how to install cold keys repo go to seo-Michael's and scroll down in the comment's I'm the Barbra booey read and I'm sure we have the same issue I can't fix it no matter what I try over 4 days of trying every trick I know ?
( koying ) sorry to post this I'm just trying to help him all as I'm sure we have the same issue

**Comment by ruppert10** [comment]
Hey hon ball if you want to I'm me on Facebook I'm Barbra booey I can send you all the steps I tried to fix this  as a last resort I even tried to close my spmc and then copy and paste my old version of y---t--e from version spmc version 15.2 to version 16.2.1 but you can not delete to old version  I don't want to upset koying and keep talking about this here so  read my first post or get me on facebook

**Comment by hinball** [comment]
I am experiencing a problem is that I get back the Nvidia shield TV from my friend, I do a factory reset and then I clean installed the latest SPMC 16.1.2 , after the first run I found that there are youtube addon, I seldom use addon so I try to uninstall it but the button greyed out, I do not  install blacklist addon, actually I only use it for my movie, but I just curious that is it the default addon included in SPMC which I cant uninstall, actually the problem don't bother me very much

**Comment by koying** [comment]
I'll remove the YT addon from the apk
