### ISSUE TITLE
SPMC - Kodi - Audio offset Audio Lip Sync Problems

### ISSUE THREAD

**Issue by Wordstar1981** [koying/SPMC#165]
Hi Koying, 

im writing this because ever since Kodi 16 i have not been able to solve the audio offset sync problems. I keep reading that a lot of people have theese problems or similar problems.

I have my passthrough set to IEC passthrough since that is the one to go for my tv...

Now these days i was watching a movie with DTS and i was observing the lip sync and was possitivly suprised that everything seemd realy nice. 

Yesterday i was then watch a couple of riped tv shows, new episode of better call saul and walking deas and then noticed that lip sync was all messed up with the dolby digital. It wasnt bad enough as to where i couldnt watch anyfurther but i was noticing a slight desync throughout the whole viewing expirience.

Now i would like to get behind this issue... what is the cause... is it the shields offset? Is that the offset to be ajusted or is it just the offset in kodi wich is desync? My shield is by default set to a offset of 50. What is your shield offset set to standardly Koying? Is it a problem with the 16 version of Kodi SPMC? How should i go about fixing this?

**Comment by liq456** [comment]
I have the same problem, it seems to be limited to Web-dl rips, so it must be something with the encoding of the rips. I have't been able to track it down further then that.

**Comment by Wordstar1981** [comment]
not only web rips but also normal tv rips from DIMENSION and AVS and so on...

**Comment by Wordstar1981** [comment]
Ok so I just tested with the new 16.2.0 and it seems Koying has fixed something in this version because i watched two 3 tv shows today with perfect lip sync... Ill just go ahead and close this for now.
