### ISSUE TITLE
Weird display for sound/subtitles delay

### ISSUE THREAD

**Issue by LePousson** [koying/SPMC#168]
When I am trying to adjust the delay for audio and/or subtitles, here is what I get : 
- when trying to adjust audio delay : http://hpics.li/06b8ff6
- when trying to adjust subtitles delay : http://hpics.li/cccb19b

I have had this display problem on every release of Kodi and SPMC on SATV ...

Anything I can try ?

**Comment by koying** [comment]
Please try in English to see if there is an issue there.
Might be that the french labels are larger, or an UTF8 issue (although "décalage" is ok)

**Comment by LePousson** [comment]
Instead of "Décalage" I should be seeing the value of the delay ... I'll make a try with English Language ...

**Comment by LePousson** [comment]
You are totally right ...

It is because of the é or any accent letter in French (no problem at all with English OSD)

Can you fix that ?

**Comment by koying** [comment]
Yep, confirmed.
Note to self: Issue with UTF8 formats in StringUtils::Format on Android only (NDK bug?)

@MrMC Already encountered something like that? Would it be solved by bumping the NDK?

**Comment by MrMC** [comment]
odd one, does issue exist on other platforms ?

**Comment by koying** [comment]
Nope. Tested on windows an rpi and ok

Le sam. 2 avr. 2016 17:16, Scott Davilla notifications@github.com a
écrit :

**Comment by LePousson** [comment]
Planned to be fixed in 16.2.1 ??

**Comment by koying** [comment]
vsnprintf issue:

```
09:35:39 T:1394174256   DEBUG: StringUtils::FormatV before
09:35:39 T:1394174256   DEBUG: MEM_DUMP: Dumping from 0x5567ff0c
09:35:39 T:1394174256   DEBUG: MEM_DUMP: 0000  41 76 61 6e  63 c3 a9 20  64 65 20 3a  20 25 32 2e  AvancÃ© de : %2.
09:35:39 T:1394174256   DEBUG: MEM_DUMP: 0010  33 66 73                                            3fs
09:35:39 T:1394174256   DEBUG: StringUtils::FormatV after nActual(5)
09:35:39 T:1394174256   DEBUG: MEM_DUMP: Dumping from 0x57eb8800
09:35:39 T:1394174256   DEBUG: MEM_DUMP: 0000  41 76 61 6e  63                                     Avanc

```

**Comment by koying** [comment]
Ref: https://code.google.com/p/android/issues/detail?id=78669
Is solved in NDK 21, from the look of it

**Comment by koying** [comment]
@MrMC Locale issue.
As of lollipop, C.UTF-8 is supported (but not via std::locale (at least not on NDK 17)) and must be used for vsnprintf to work in UTF8.
I do a hard hack (https://github.com/koying/SPMC/commit/a3e356e4dc6c6910eccbfff6740bc94094ec0951) but I'll be interested to know if you succeed to set C.UTF8 via std::locale in NDK 21

**Comment by MrMC** [comment]
will check
