### ISSUE TITLE
3D Film tagging not seen with 16.2 install of SPMC

### ISSUE THREAD

**Issue by VimesUK** [koying/SPMC#176]
I had 16.1.2 installed on my NVidia Shield and all the films (107) which are correctly tagged as being encoded in 3D appeared find with the 3D symbol in a list type view using Confluence when running SPMC. They played fine also.

The above is the same with Kodi 16.1 RC 2.

However changing on the Shield to 16.2 it will list the films as being HD only.

Other known working skins (tested Xonfluence and Transparency) will also show the same, fine on 16.1.2 but HD tagging on the 16.2 release.

On the AFTV first gen I have remained on 16.1.2 and that also is fine with all the films tagged (example : Avatar 2009 .3d.hsbs.mkv)  listing with the 3D symbol and not just HD.

Screenshots, along with other information, were uploaded to the SPMC thread over at the Kodi forums.

Thanks.

**Comment by koying** [comment]
To be clear, are the film still playing as 3D?
i.e. is it only the skin display which is wrong?

**Comment by VimesUK** [comment]
Yes the films work great in 3D.

I do not know which are which mind you as they are all tagged as being HD.

But playing a film invokes the 3D response from my Panasonic GT50 TV and they play fine.

The skin display was great in 16.1.2 but not in 16.2.

No difference is seen when using other known working skins, as noted.
I have the Transparency skin working fine with displaying 3d tagging on 16.1.2 SPMC and other builds of Kodi from 16 to 17 Nightlies but not 16.2

**Comment by VimesUK** [comment]
SPMC 16.2 list.....

http://s25.postimg.org/xyy7qohdr/SPMC_list.jpg

Kodi 16.1 RC 2 list (just the same as SPMC 16.1.2)....

http://postimg.org/image/5al9ngf7f/

**Comment by koying** [comment]
Were your movies "auto-detected" as 3D or did you "force" them via the OSD settings (or a mix of both in your screenshots)

**Comment by VimesUK** [comment]
They were auto detected.

I removed the source folder (separate 3D Movie folder) from the 16.2 SPMC build and let it clean the database. I cleaned the library and then restarted SPMC 16.2. Then I added the folder again and let it scrape. The films were all found, as before, but still tagged as HD and not 3D.

In 16.1.2 SPMC they auto detect and display fine.
In Nightly Kodi 17 the same.
In 16.2 RC 1 the same.

On the AFTV 16.1.2 they also display fine.

I could sideload the apk of 16.2 SPMC onto the AFTV and let you know about that if you want....?

**Comment by koying** [comment]
Nah, thanks. Found the issue, I think.

**Comment by VimesUK** [comment]
Most impressive, thanks for the consideration.

**Comment by koying** [comment]
Fixed in https://github.com/koying/SPMC/commit/d3b86c1a0be79f2b30a6f343ed4d96f03e8d5937
