### ISSUE TITLE
TV Recommendations in 16.2.0 link to season and not the episode

### ISSUE THREAD

**Issue by mattsch** [koying/SPMC#179]
$SUBJECT seems to be not quite the desired behavior, would assume it should go to the episode much like movies.

**Comment by koying** [comment]
It should show you exactly the same view as if you'd have clicked on a TV show inside SPMC.
Not the case?

**Comment by mattsch** [comment]
It does bring me to the season of the next episode to watch, but I was expecting it to bring me to the episode itself.  Perhaps I misunderstood the implementation?

**Comment by hstamas** [comment]
I'm seeing the same behavior. On my Shield home screen, SPMC recommends s02e02 of Friends for example. If I select that, SPMC launches but it goes to a random episode within season 2 of Friends. 

Expected behavior would be for it to highlight the actual episode selected on the home screen.
