### ISSUE TITLE
Koying thank you for fixing this issue

### ISSUE THREAD

**Issue by ruppert10** [koying/SPMC#181]
Hi koying I just got version 16.2.0 from the Google play store and want to just give you 
A BIG THANK YOU  for fixing the broken 
y*\* tu*e add on we had from the other version it was driving me crazy trying to fix it i'm sure it is nice just to hear a thank you on here for once insted of this don't work or that don't work you made me very happy today thanks again koying for all that you do

**Comment by koying** [comment]
You're welcome
