### ISSUE TITLE
Video playback stops when pressing the back button on remote.

### ISSUE THREAD

**Issue by msammut** [koying/SPMC#189]
It seems that video playback stops when pressing the back button to go back to the video listings.
On Kodi, the video (and audio) keeps playing in the background while I can navigate other content in the menus, but with SPMC this does not seem to work, playback stops immediately.

I'm running AMBER skin on SPMC's latest build. running on the nvidia shield and using the small remote , same behaviour on the gamepad too though.
I have the 'background music visualization/video player on home screen' option set to Yes.

Am I missing something obvious?

**Comment by ErAzOr2k** [comment]
It's not a bug, it's a feature :)
You can disable this by edit keyboard.xml

**Comment by msammut** [comment]
hehe ok... any idea what I need to edit in the xml?
Any way to do that directly on the shield ui?

**Comment by ErAzOr2k** [comment]
You need to undo this change: 

https://github.com/koying/SPMC/commit/46ad2918907eb8b918cb1f2eb7b3d834ebf71123

**Comment by msammut** [comment]
ah so currently a long press of the back button will achieve what I'm after? :D

**Comment by ErAzOr2k** [comment]
remove these lines:

`<backspace>Stop</backspace>
<browser_back>Stop</browser_back>`

**Comment by koying** [comment]
> ah so currently a long press of the back button will achieve what I'm after? :D

Yep ;)

**Comment by msammut** [comment]
Awesome! Thanks all!
