### ISSUE TITLE
music addons not working 

### ISSUE THREAD

**Issue by michaelamsterdam** [koying/SPMC#190]
it seems that no music Addons are able to stream audio.  tried several which are working on kodi 16.  for example mp3streams bin@tural mp3box and others.  other people in my group are also having the same issue so it doesn't seem ADDON related.  everything goes fine until you start to play the stream then it just doesn't okay

**Comment by michaelamsterdam** [comment]
play I meant

**Comment by nevrion** [comment]
All my Music Addons works well...

**Comment by michaelamsterdam** [comment]
ok will check further then thanks

Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: nevrion notifications@github.com
Datum: 07-04-2016  17:43  (GMT+01:00)
Aan: koying/SPMC SPMC@noreply.github.com
Cc: michaelamsterdam michaelamsterdam@hotmail.com
Onderwerp: Re: [koying/SPMC] music addons not working  (#190)

All my Music Addons works well...

---
