### ISSUE TITLE
Feature Request: Boost center channel when downmixing (port from OSMC)

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#193]
This is a feature I love in the Raspberry Pi versions of Kodi. It's on both OpenELEC and OSMC.
Basically when downmixing a 5.1 track to 2.0, you have to option to boost the center channel by a certain DB-value, to make dialogue much easier to hear.

I understand "Normalize levels on downmix"/Volume Amplification sort of does this, but I way prefer OSMS's implementation.

**Comment by koying** [comment]
Yep
