### ISSUE TITLE
Denon avr passtrough only multi chan in

### ISSUE THREAD

**Issue by gbizet** [koying/SPMC#196]
Hello, since 16.2 on HDMI passtrough raw to à Denon x2200w hdcp2.2 i get only multi chan in and no more the dts or dolby or dts HD etc. From à shizld TV . any idea?

**Comment by Metascientomics** [comment]
I have the same problem on a Denon AVR-x4100w (also from a shield tv).

**Comment by gbizet** [comment]
more info : Settings system audio : device Raw android, 5.1, passtrough on raw, all options to on for passtrough, output try optimized and best match. 
Was working on 16.1 ;d

source shield to AVR denon on hdmi (2.0a, hdcp 2.2) to a TV (also on hdmi 2 hdcp2.2).

Thank you.

**Comment by Metascientomics** [comment]
Same parameters as gbizet for me. Was working in 16.1 for me as well (and still works on "standard kodi" with regard to passthrough...of course no HD sound passthrough there).

Cheers

**Comment by heymoe** [comment]
Do you have "Sync to Display" enabled under Video settings? If so, a new feature / bug fix / whatever you want to call it, was back ported from Kodi 17 that disables passthrough when Sync to Display is enabled in v16.2.

**Comment by gbizet** [comment]
Have try with it disable,(sync) still the issue

**Comment by gbizet** [comment]
My bad was not good option. Its working with sync disable. Thank u!!
