### ISSUE TITLE
Passthrough doesn't

### ISSUE THREAD

**Issue by DavidCWGA** [koying/SPMC#198]
16.2.0 from Google Play on Shield TV, HDMI to Onkyo receiver.

What settings do I have to change to get passthrough to work?

Currently I have, in Settings > System > Audio output:
Audio output device is "Android, PCM" (Though I tried Android, RAW as well and it didn't make any difference.)
Enable passthrough is ON
Passthrough output device is "Android, RAW"
All of the "capable" options are ON.

But I always get PCM output. The current version of Kodi in the Google Play does passthrough correctly.

**Comment by heymoe** [comment]
Do you have "Sync to Display" enabled under Video settings? If so, a new feature / bug fix / whatever you want to call it, was back ported from Kodi 17 that disables passthrough when Sync to Display is enabled in v16.2.

**Comment by DavidCWGA** [comment]
Yes, I do, and that was the problem.

Will turning it off cause any sync problems? In particular, I watch a lot of PAL videos, but I've noticed that SPMC does not switch to a 50Hz mode when playing them back.

**Comment by heymoe** [comment]
I personally don't have a good answer for you on that one. Sorry.
