### ISSUE TITLE
The app icon

### ISSUE THREAD

**Issue by BMKlum** [koying/SPMC#215]
Hey

Love your work!

Just wondering if you considering updating the app icon for Android TV?

Sorry to say, but I find the icon a little bit old and it doesn't fit with the rest of Google's design language.

Just a suggestion.

Best regard

**Comment by koying** [comment]
Consider? Sure.
Spend myself any time on it? Nope ;)

**Comment by BMKlum** [comment]
That's too bad...

**Comment by tar-gezed** [comment]
@koying I made this if you want to use it ;)

![spmc-logo](https://cloud.githubusercontent.com/assets/4738932/14610229/47c7dd02-058d-11e6-9a07-8bc29789f87e.png)

**Comment by BMKlum** [comment]
That looks nice!

**Comment by tar-gezed** [comment]
I don't know if you're interest by my logos @koying but here there are ;)
Small color change to respect material design guidelines and a new banner for android tv ;)

![spmc-illustrator-2](https://cloud.githubusercontent.com/assets/4738932/14704457/1383d512-07b5-11e6-85bf-1a1b3e247b3f.png)
![spmc-banner](https://cloud.githubusercontent.com/assets/4738932/14704456/13803fa6-07b5-11e6-9278-d187fe69c5c6.png)
