### ISSUE TITLE
Frequent intermittent audio loss while on Android home screen

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#217]
If you are listening to an internet radio stream, it plays fine until you go to the Android TV home menu. Then the audio has frequent rapid drop outs ("machine gun effect"). Returning to SPMC eliminates the drop outs. Occurs every time.

I am using Nvidia Shield with firmware 3.0 and SPMC 16.2.0

To recreate, you can create a .pls file with the code below:

```
[playlist]
NumberOfEntries=1
File1=http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p
Title1=BBC Radio 1
Length1=-1
```

Then play it in SPMC.

**Comment by koying** [comment]
Confirmed and fixed

**Comment by classicjazz** [comment]
Thanks. I donated some beer money.

**Comment by j9ac9k** [comment]
Ran into this issue, glad to see already fixed, ...also donated money a week ago thanks for the awesome product!
