### ISSUE TITLE
Can't write on external storage 

### ISSUE THREAD

**Issue by tar-gezed** [koying/SPMC#219]
Hi, 
On my Nvidia Shield TV running marshmallow, I can't write on my SD card if I don't adopt it (adoptable storage marshmallow feature) or only if I'm rooted. 
So I was wondering if it's possible to add permission to SPMC to write on external storage?  (even if it's only for rooted users it would be awesome) 
Thanks in advance and keep it up, really great work ;-)

**Comment by koying** [comment]
Known issue

**Comment by tar-gezed** [comment]
I know that is a known issue, but it was just a question ;)
Is it possible to do something (even if it's only for rooted users) like a workaround or something else ? :)
