### ISSUE TITLE
with latest apk of today live tv is not working anymore

### ISSUE THREAD

**Issue by nfstry** [koying/SPMC#22]
using the update i got today on the device, i can't setup anymore livetv. when i select enable livetv i used to get a window to choose the pvr client, after the update that window doesn't come anymore and ui freezes. ( with the previous apk it was working well)
![xbmc](https://cloud.githubusercontent.com/assets/3796513/4829991/832ee41c-5f8a-11e4-8746-f53790ec46dd.png)

image link is the log file from spmc

17:34:45 T:1217918648   DEBUG: ------ Window Deinit (Settings.xml) ------
17:34:45 T:1217918648   DEBUG: ------ Window Init (SettingsCategory.xml) ------
17:34:45 T:1217918648   DEBUG: Window SettingsCategory.xml was already loaded
17:34:45 T:1217918648   DEBUG: Alloc resources: 2.36m
17:34:46 T:1217918648   DEBUG: Keyboard: scancode: 0x16, sym: 0x0113, unicode: 0x0000, modifier: 0x0
17:34:46 T:1217918648   DEBUG: bool CApplication::OnKey(const CKey&): right (0xf083) pressed, action is Right
17:34:49 T:1217918648   DEBUG: Keyboard: scancode: 0x17, sym: 0x000d, unicode: 0x0000, modifier: 0x0
17:34:49 T:1217918648   DEBUG: bool CApplication::OnKey(const CKey&): return (0xf00d) pressed, action is Select
17:34:49 T:1434529000  NOTICE: PVRManager - starting up
17:34:49 T:1404219800  NOTICE: Thread PVRManager start, auto delete: false
17:34:49 T:1431534904  NOTICE: Thread PVRClient start, auto delete: false
17:34:49 T:1217918648    INFO: stopping PVRManager
17:34:49 T:1217918648  NOTICE: PVRManager - stopping
17:34:49 T:1404219800   DEBUG: Thread PVRManager 1404219800 terminating
17:35:19 T:1378127128   DEBUG: Thread JobWorker 1378127128 terminating (autodelete)
17:35:19 T:1434771592   DEBUG: Thread JobWorker 1434771592 terminating (autodelete)
17:35:19 T:1383377952   DEBUG: Thread JobWorker 1383377952 terminating (autodelete)
17:35:19 T:1434529000   DEBUG: Thread JobWorker 1434529000 terminating (autodelete)

**Comment by koying** [comment]
Yep. This release turns into a packaging nightmare ;)

**Comment by nfstry** [comment]
solved on today's update
