### ISSUE TITLE
No DTS-HD or true HD after Update to 3.1

### ISSUE THREAD

**Issue by Mbendtsendk** [koying/SPMC#224]
Hi, iam using a hdmi splitter shield to avr and tv, because of 4k.

Yesterday bedre the 3.1 Update everything worked fine i had the 4k resolution on My tv and DTS-HD displayed on My receiver, now after the Update to shield 3.1 everything but DTS-HD and true HD works, does anyone know why it doesnt work for me anymore ?

**Comment by koying** [comment]
Works for me (without splitter)

**Comment by Mbendtsendk** [comment]
I need the splitter because My receiver only has hdmi 1,4 it worked flawless before the 3.1 Update, i just cant figure out where the change is

**Comment by war59312** [comment]
Sounds like you need to bug with Nvidia.

If you were already using same SPMC build before the shield update.

**Comment by showmak** [comment]
My TV is HDMI 1.4 and my Shield is connect to my Yamaha RX-A3050 and everything was fine on 3.0 and now on 3.1.

**Comment by Mbendtsendk** [comment]
I have a Yamaha rxv 1067 and a Samsung js9500, i Think its a hdmi cec issue it works when i bypass My splitter, but Then i lose the 4k resolution. I Read that in the next shield Update it should be possible to turn OFF cec, so i guess i just have to wait and see.

**Comment by showmak** [comment]
@Mbendtsendk may I know which HDMI splitter you are using?

**Comment by Mbendtsendk** [comment]
@showmak iam using this one

http://www.lindy.co.uk/audio-video-c2/splitters-c159/2-port-4k-hdmi-2-0-uhd-splitter-p9147

**Comment by showmak** [comment]
@Mbendtsendk thank you mate.
