### ISSUE TITLE
SPMC 16.2.1 metadata issue after 3.1 Update

### ISSUE THREAD

**Issue by showmak** [koying/SPMC#226]
Here is the issue with SPMC 16.2.1 and also 16.2.0 after I updated my Shield to 3.1

**SPMC 16.2.1/16.2.0**
http://i759.photobucket.com/albums/xx236/showmak/SPMC_20160420_002024_zpsdd0adcf7.png

**KODI 16.1 RC2**
http://i759.photobucket.com/albums/xx236/showmak/Kodi_20160420_002048_zpsbamtxzno.png

As you can see from the above pics, for some reasons, SPMC does not show the movie metadata information e.g **1080/H265/Dolby TRUEHD/7.1/16:9 and etc.** While KODI (kodi-20160308-b881949-adddroidPT-armeabi-v7a.apk) still working fine on this regards on 3.1 Shield update.

**Comment by llonca13** [comment]
Try to start the movie,leave it playing for a fw seconds..maybe then will show

**Comment by koying** [comment]
Acknowledged

**Comment by showmak** [comment]
@llonca13 Did that and also uninstalled and reinstalled SPMC, still the same issue. However, on 3.0 was just fine.

**Comment by showmak** [comment]
@koying Thank you Chris for acknowledging the issue.

**Comment by koying** [comment]
Fixed

**Comment by showmak** [comment]
Chris, you are the man. Many thanks.

**Comment by showmak** [comment]
Chris, it is all OK in 16.3.0. Well done.
