### ISSUE TITLE
Amcodec and auto refresh rate SPMC v16.2.1

### ISSUE THREAD

**Issue by ukmark62** [koying/SPMC#228]
If I have auto refresh turned on and using Amcodec hardware acceleration, SPMC hangs when changing refresh rate. This only occurs for 23.976 --> 24p switching. This is happening on all the 23.976 files so far. The screen hangs and the only solution is to reboot.

However, If I play 25p videos, then SPMC correctly switches to 1080p/50p output and everything plays back perfectly. I have set permissions on the Amlogic files to 666 as mentioned on various web sites (e.g. http://forum.kodi.tv/showthread.php?tid=229310). What's weird is that 25p switching works but not 23.976p??

If I then disable Amcodec and choose MediaCodec instead, everything plays back perfectly (23.976 and 25p files with corresponding switch of TV to 24p and 50p respectively). So, I can use SPMC very happily, but find this issue with Amcodec very weird.

Using M8S box with S812 CPU, android 4.4 (stock M8S rom from 23/3/2016:-  http://chinagadgetsreviews.com/download-latest-android-kitkat-4-4-2-stock-firmware-m8s-tv-box-3.html), 2gb ram, 8gb storage, AP6330 WiFi.

PS. The 'Sync playback to display' definitely makes a difference. If I disable that , then I get micro stuttering, if I enable it, perfect playback!!! (Thanks so much for your work!)

**Comment by llonca13** [comment]
Im almost sure its firmware problem.those chineese firmwares are awful.i have mxiii(s802) and i tried 5 diff fw before i tried the one that works perfectly(even this init.d scripts didnt help).go on freaktab and find another firmware for m8s(under amlogic s812).
Another thing that cross my mind is..somethimes this init.d scripts need a couple of minutes to apply.so if you use spmc like luncher it doesnt get the right permissions.try to set this permissions manually (in some terminal emulator,line by line),and then restart spmc.maybe this helps,of no find a new firmware.trust me :)

**Comment by ukmark62** [comment]
Thanks for the reply. I think it's firmware related too. If both 25p and 23.976p frame switching didn't work, I would have thought some kind of permission issue. But, the 25p does switch frame rates. I have checked the permissions on the Amlogic files before opening SPMC. I'll look for another firmware on freaktab as you suggested. If I find one that works, I'll come back and make that info available.

**Comment by llonca13** [comment]
Glad i could help :) just try until you find the one that works ..m8s and mxiii-g firmwares should work for you device

**Comment by ukmark62** [comment]
I'll close this as I have installed OpenELEC on the M8S and everything plays back smoothly and with less memory used than Kodi. The only reason I bought an Android box was for kodi.
