### ISSUE TITLE
Handle buffering settings better

### ISSUE THREAD

**Issue by mishan** [koying/SPMC#241]
The biggest problem I had with Kodi was that its buffering settings are extremely conservative and do not serve more modern content very well, nor does it attempt to leverage higher-powered devices like Nvidia Shield.

I learned that an `advancedsettings.xml` file is required change buffering settings to handle a wider range of content over the network better. Creating this file with the appropriate settings definitely resolved my issues. This is sort of a pain in the butt. If SPMC is aiming to support devices like Shield particularly well, perhaps it could have more reasonable defaults? The device has 3GB of RAM, after all. If a conservative default is still desired to support a broader range of devices, it would be super nice to be able to either alter buffering settings directly from within the application, or, perhaps, set some kind of "device/usage profile" (e.g.: >1-2GB RAM, streaming of large files expected)

Proposing this as a "wishlist" issue

**Comment by heymoe** [comment]
May I ask what changes you made to your advancedsettings.xml that you feel are better for the Shield TV? I personal run the defaults right now and haven't really noticed any problems playing content but who know what I'll be doing in the future so might be good to know what some better recommendation are. Thanks

**Comment by koying** [comment]
> The biggest problem I had with Kodi was that its buffering settings are extremely conservative and do not serve more modern content very well, nor does it attempt to leverage higher-powered devices like Nvidia Shield.

Majority of my files comes from an unoptimised personal webdav server out of my country.
Never had to touch the buffer settings.

Assuming you are streaming from "grey" servers, **they** are probably unable to cope with the demand.

**Comment by mishan** [comment]
Hm. I was thinking about this some more and perhaps it is a limited edge use case, at least for now. I'm currently using a local server running NFS over 802.11ac Wi-Fi. This all should  be on wired Ethernet but I haven't gotten around to the wiring yet.

99% of stuff plays fine. It's when I hit files that are 30GB or larger that I run into issues.

This "safe" setting for 1GB devices from the Kodi website allows files like the one I mentioned to play fine.

```
<advancedsettings>
  <network>
    <buffermode>1</buffermode>
    <cachemembuffersize>157286400</cachemembuffersize>
    <readbufferfactor>20</readbufferfactor>
  </network>
</advancedsettings>
```

Source: http://kodi.wiki/view/HOW-TO:Modify_the_video_cache

**Comment by koying** [comment]
99% of the use cases running fine with default settings explains why the cache settings are _advanced_ ones.
Putting them in GUI will:
1) clutter the settings
2) encourage newbies to put nonsensical values, then come whining that their device does not work ;)

**Comment by mishan** [comment]
Fair enough. Closing issue.
