### ISSUE TITLE
1080p support for youtube addon 

### ISSUE THREAD

**Issue by dubastik** [koying/SPMC#242]
Hi koying,Is it possible that you can SPMC enable 1080p support on YouTube addon?

**Comment by koying** [comment]
Surely not currently, it needs multi-stream, which is not in SPMC, and I don't think the youtube addon supports it either.

**Comment by crazy888** [comment]
@koying

Right now YouTube IS supporting 1080p videos. http://forum.kodi.tv/showthread.php?tid=267160&highlight=Dash+YouTube

We just need that input.stream plugin. Can't find it anywhere. The dash support button is greyed out in YouTube plugin settings. Maybe reopen this request?

**Comment by koying** [comment]
See https://github.com/koying/SPMC/issues/588
