### ISSUE TITLE
Alot of skipped frames

### ISSUE THREAD

**Issue by llonca13** [koying/SPMC#243]
I dont know if its a bug in codecinfo screen or spmc  really skips frames or bug in my firmware(because all my videos play buttery smooth).kodi(16.1) shows no skipped frames(but the video is nowhere near smooth like in spmc).
I dont consider this as a problem,but i was just wondering can anyone else confirm this bug?
Btw its affected in all codecs(x264,avc,xvid) i tried.

Picture of codecinfo screen:
http://s32.postimg.org/b0qcii85h/20160427_103318.jpg

Btw also just want to thank you koying for all your work.I almost throw to trash my old s802 amlogic box before i found out spmc is continued in developing.Thank you for this

**Comment by llonca13** [comment]
I forgot to mention..in 2mins i get 200 skipped frames and its linearly growing

**Comment by dubastik** [comment]
Hi llonca13, me i constantly have dropped frames on my Mkv files vidéos in h264 with framerates in 23.976,50.000,59.964, when i advanced the video with the mouse. Ps: i have a nvidia shield tv connected on a hd tv with synchro playback actived.

**Comment by llonca13** [comment]
I dont think our problems are the same...i think dropped frames usually means that decoder couldnt decode them (impossible for nvidia shield :D ) ..try to disable synch playback to screen,and turn on "Adjust display refresh rate to match video" (to start/stop)..maybe this helps

**Comment by BhwSyd** [comment]
What happens if you just use MediaCodec as your acceleration hardware enabled option?

**Comment by llonca13** [comment]
I tried..there is no skipped frames with mediacodec..but my box use ffmpeg then and my cpu cant handle it..kodi works though without skipping frames with amcodec :(

**Comment by llonca13** [comment]
i guess is amlogic problem only....closed
