### ISSUE TITLE
Wrong TV shows season order

### ISSUE THREAD

**Issue by griev04** [koying/SPMC#245]
Hi,
since updating to 16.2.0 (and 16.2.1) I've noticed that, in some menus, tv series seasons are sorted incorrectly: season 3 is now the first season to be displayed, then 4, 5 and so on; season 1 and 2 are the last ones.
I found this issue in the "all seasons" list (after picking any tv show with more than 2 seasons) and in the widgets showing in progress shows: even if I'm watching season 1, it suggests me to watch season 3 (as it was the first one).

I tried both 16.2.0 and 16.2.1 with fresh install and using different skins: always the same issue.
Using 16.1.2 I have no issues at all.

Thank you

**Comment by koying** [comment]
Already fixed in upcoming version
