### ISSUE TITLE
SPMC 16.2.1 View listings in wrong order

### ISSUE THREAD

**Issue by ziggy73701** [koying/SPMC#246]
Please stay with me on this one as its a little odd to explain. I have a playlist which brings up the IMDB top 250. On IOS and Windows, this playlist loads and all films are shown in ascending numerical order.

 If I then flick to SPMC, the same playlist shows out of order ie

 1
 100
 101
 102

 Etc. I have tried this in a couple of installs both clean and using my existing settings all with the same result. I run MySQL, though that has also had a clean build. I have confirmed across several installs and OS that it does display correct. 
 Can anyone offer any ideas as its driving me mad!

**Comment by koying** [comment]
Already fixed in upcoming version

**Comment by ziggy73701** [comment]
Legend!!!!

Any ball park on when that release may be?
