### ISSUE TITLE
FireTV 2 + SPMC 16.3.0 DD51 works but DTS not

### ISSUE THREAD

**Issue by dm82m** [koying/SPMC#247]
I have expert settings. Passthrough activated. Within audio settings I use "Android, RAW Passthrough" and check AC3 and DTS. If I play a file with DD51 it works. I get Dolby Digital signal on my Denon X1200 amp. But if I start a file with DTS there is only PCM signal on my amp instead of real DTS. I have no idea if I did any setting wrong!?

**Comment by Firetv344** [comment]
Having the same exact issue on my nvidia shield........when I use android raw PT I get no sound at all

**Comment by Firetv344** [comment]
Forgot to mention.....I only get sound when I use

**Comment by marcmv1** [comment]
SPMC 16.2.1, FireTV2, Denon receiver, Android, IEC Passthrough. No issues at all with DTS

Maybe try IEC passthrough and see if that fixes it?

**Comment by Firetv344** [comment]
I'm using android iec but no DTS....amp just display PCM

**Comment by dm82m** [comment]
IEC is not giving a sound at all...

**Comment by dm82m** [comment]
no idea?

**Comment by koying** [comment]
You activated the DTS passthrough option in spmc, right?

**Comment by dm82m** [comment]
yes I did. also updated to 16.3.0 but everything the same. DD51 working fine, DTS is NOT given as digital stream but as PCM...

**Comment by koying** [comment]
What do you mean by PCM: Noise or audible 5.1 PCM?
If audible PCM, log, please.

**Comment by dm82m** [comment]
with IEC I have only noise. With RAW I have PCM. is there any documentation I can read about how to create the log?

**Comment by koying** [comment]
Oh, missed the Denon part.
See http://forum.kodi.tv/showthread.php?tid=273081&pid=2331817#pid2331817
RAW for DTS only work as of Android API 23 (AFTV's FireOS5 is API 22).

**Comment by dm82m** [comment]
thanks for clarifying that. do you think that firetv OS will be updated or should I try to send my firetv2 back and order a nvidia shield?

**Comment by Firetv344** [comment]
I have a Sony receiver and an nvidia shield I only get sound if I use iec pass through and that's only 5.1 DTS display as PCM 48 HZ......If I use android Raw I get no sound at all..

**Comment by koying** [comment]
@dm82m Hold on. Building a special apk with some tweak for AFTV

**Comment by Firetv344** [comment]
Any ideas how to get DTS?

**Comment by dm82m** [comment]
sounds good @koying :+1:

**Comment by koying** [comment]
@Firetv344 Please open your own ticket. Your issue is obviously unrelated to this one (and I have no clue)

**Comment by Firetv344** [comment]
Ok

**Comment by koying** [comment]
@dm82m Here is: http://download.semperpax.com/spmc/android-arm/SPMC-20160510-4fc0678-testAudioMediacodec-armeabi-v7a.apk

First try **with passthrough disabled altogether**, then, if it doesn't work, with IEC. RAW will not work on AFTV for DTS, as I said.

**Comment by dm82m** [comment]
@koying the apk is not installable on firetv...

**Comment by koying** [comment]
Ah damn, version issue. Can you uninstall? Can you force a downgrade ("adb -r -d" if you do so)?
If not, I'll build another one.

**Comment by dm82m** [comment]
`C:\adbFire>adb install -r -s 192.168.178.9:5555 C:\Users\dm\Downloads\SPMC-20160
510-4fc0678-testAudioMediacodec-armeabi-v7a.apk
523 KB/s (62732729 bytes in 117.071s)
        pkg: 192.168.178.9:5555
        ver: /sdcard/tmp/SPMC-20160510-4fc0678-testAudioMediacodec-armeabi-v7a.a
pk
Failure [INSTALL_FAILED_INVALID_URI]`

**Comment by koying** [comment]
"adb -r **-d** -s ...", although the error message is strange

**Comment by dm82m** [comment]
Also not working, same error message, other Versions (also older ones) are working...

**Comment by koying** [comment]
Strange. Please try with http://download.semperpax.com/spmc/android-arm/SPMC-20160510-4fc0678-testAudioMediacodec-armeabi-v7a.apk

If it still doesn't work, maybe try renaming the apk. I'm not aware of a name length issue, but who knows...

**Comment by dm82m** [comment]
installable without any name change or modifications... will try it out now.

**Comment by dm82m** [comment]
Without Passthrough it is only stereo on DD51 and DTS. With passthrough and IEC DD51 is stereo and DTS only noise. With passthrough and RAW DD51 is DD and DTS is PCM. So no changes at all...

**Comment by nutron802** [comment]
All i get is noise with DTS with passthrough enabled. I am using a AFTV2 latest update and the latest SPMC 16.3.0. My receiver is a Pionner.

**Comment by lb99** [comment]
I have a Yamaha DSP A1 and the Fire TV 2. If I select passthrough and RAW,  DD5.1 works and DTS is in 2 channel pro logic. If  passthrough and IEC is selected, DD5.1 has no sound  but DTS works fine. Can you add a mode to the program where both DD5.1 and DTS are sensed and selected by my receiver without me having to switch between RAW and IEC ? According to your previous posts this should be corrected in android API 23 but perhaps the program could address the problem now.  Also, your SPMC media codec fix APK would  not install on my Fire TV.  I am using your latest official version of SPMC 16.3.  Another idea is that you could add a selection for  RAW or IEC passthrough in the audio settings that are available when I am playing a video.   That would be awesome... Thanks for your great program !

**Comment by lb99** [comment]
Koying.. you answered the above question in another post in the Kodi forum under audio passthru on Fire TV : http://forum.kodi.tv/showthread.php?tid=217937&page=7

You provide a link to your SPMC build in RAW: http://download.semperpax.com/spmc/android-arm/SPMC-20160526-780e447-fix_dts_raw-armeabi-v7a.apk

This build allows me to play DD5.1 and DTS without a problem. Thank you !

**Comment by koying** [comment]
Not sure it's quite the same issue as the others but thanks for the feedback

**Comment by dm82m** [comment]
does not work for the original problem described in this ticket. no sound or noise for me. depending on settings...

**Comment by sierrabobusa** [comment]
If it helps, I have verified that AFTV 1 + SPMC 16.3.0 works properly through optical output to Samsung HT-DB600.  I can play a 1080P/DTS file with no issues.   This is with the following audio settings in SPMC:  android, pcm output, 2.0 channel, passthrough enabled, android, IEC passthrough device, AC3 capable receiver, AC3 transcode enabled, DTS capable receiver.   No additional software involved.

**Comment by cornwolf** [comment]
Hi All, 

I know this post is a little old but I am having the same issue with no DTS audio, does the above APK link still apply even though I am on the latest version which is 16.4.1? 

Thanks

**Comment by Steinblock** [comment]
Since DTS is not supported in Raw Passthrough on current FireTV Api Level: Is there an option in SPMC to transcode DTS to AC3 5.1 on the fly?

In my current setup I get 5.1 with DD and Raw Passthrough (FireTV2).

I disabled "DTS capable receciver" and enabled "Enable Dolby Digital Transcoding". Now I would expect DTS would be converted to DD 5.1 but I only get two channel output on all 5 speakers.

**Comment by koying** [comment]
It should... unless it's DTS 2.0

**Comment by kip-dynamite** [comment]
The latest Denon firmware solved this issue for me (FTV 1 with Denon X1200). DTS and DD 5.1 passthrough with IEC without any problems.

Cheers kip

**Comment by koying** [comment]
@kip-dynamite thanks for the info
@mrmc You might want to check on yours ;)

**Comment by cornwolf** [comment]
I all just a little update from me, I have found that it is not the FireTV etc that has the issue it is my TV. For some reason it is no longer switching from Dolby Digital to DTS etc. If it is on a different source the TV just goes to stereo which is really annoying. I am trying to contact Samsung about it but I can't find a bug list etc.

**Comment by MrMC** [comment]
Yea, just got the Denon update notification. Lets see if it fixes the Denon 3200W and below issues with passthrough. Also tracking and issue with EAC3 w 7.1 channels on FireTV2. Shield has no issue, FireTV2 is strange, with Denon, just get silence. If skip amp and pass hdmi to Samsung UHDTV, plays but audio skips. Very Strange. Same sample file, same APK. CJNIAudioFormat::ENCODING_E_AC3 supported on both.

**Comment by Steinblock** [comment]
I have a FireTV2 connected to a Grundig GFB 6621 SmartTV which is connected to a Samsung HT-J4500 5.1 home theater via HDMI and ARC.

Since the FTV has no Digital Out and the HT-J4500 has not HDMI IN I only can connect the FTV to the TV. This is my progress so far:
- Amazon Instant Video play 5.1 sound just fine without any additional setup needed.
- With Kodi 16 I could not get 5.1 sound at all (didn't matter if passthrough or not, DD, DD+ or DTS, either stereo or white noise)
- With Kodi 17 nightly no sound for passthrough
- With SPMC (currently I am on `SPMC-20160510-4fc0678-testAudioMediacodec-armeabi-v7a.apk` but I am pretty sure the same applies to the 16.4.2): Dolby Digital works with RAW Passthrough, Dolby Digital Plus is stereo (if I enable Dolby Digital Plus capable receiver, the sound/video lags a lot, but would be 5.1) and DTS is stereo (with DTS capable receiver disabled, white noise if I would enable it).

The Samsung HT-J4500 5.1 is capable to decode DD, DD+ and DTS. I verified it by playing the same file from a local disk. But with IEC passthrough I only get white noise so I believe the TV does not transmit the signal correctly. 
Raw passthrough works, but as koying said, raw passthrough for DTS only works from api level 23, so I am hoping for a FireTV Update.

If I have time I will examine my logs to figure out why DTS is not transcoded to DD which would solve my problem.

I am still playing with the settings and if I figure out the best settings, I will post it here.

**Comment by MrMC** [comment]
Verified, Denon update for DTS-X fixed seeing DTS/IEC on FireTV2 on my Denon 3200W

**Comment by dm82m** [comment]
Works now with my x1200!!! This is brilliant!!! Thread can now be closed as my initial problem is solved!
