### ISSUE TITLE
Plexbmc won't connect to media servers

### ISSUE THREAD

**Issue by y2kbadbug** [koying/SPMC#249]
I am running the latest version and installed Plexmbc from the repo.  It loads just fine, but when I try and connect it says that it cannot connect to my media center.  This is a Nvidia Shield TV.  I've tried logging into my Plex account and trying to connect to my local Plex server automatically.

Is there anything in the program blocking it?

**Comment by Vlaves** [comment]
Thats not a SPMC problem as far as I can see. Plexbmc is not continued as far as I could see and I guess it is not updated to catch up with the server development moving foreward.
Use this instead: https://forums.plex.tv/discussion/210023/plexkodiconnect-let-kodi-talk-to-your-plex/p1
Its working great for me. Hope that helps.

**Comment by y2kbadbug** [comment]
Actually, I was using the latest 3.x version of Plexbmc, but using the latest beta build of 4.x on Plexbmc works completely fine.  Also, before giving bad information, Plexbmc is not discontinued or abandoned, the maintainer has just been pretty busy lately.  He does plan on working on it again.

This can indeed be closed though.
