### ISSUE TITLE
File resume for UPnP

### ISSUE THREAD

**Issue by Dion250** [koying/SPMC#256]
This is a feature request really.  But is there a way to add file resuming support over Files>UPnP.
Kodi requires everything to be in a library for it to resume.  But you can't add the UPnP source to the library.  Which is understandable since UPnP provide there own setup.  But resume is still client side based.

**Comment by Dion250** [comment]
I brought this issue up to the Kodi developers.
http://trac.kodi.tv/ticket/16680

And they fixed it here.
https://github.com/xbmc/xbmc/pull/10027

Is it possible to get this merged into SPMC Jarvis ?  All the code they fixed it available and shouldn't require much work.
Hope this can be merged thanks.

**Comment by koying** [comment]
Done. Thanks for the tip.
