### ISSUE TITLE
4K Gui, SPMC 16.3 and Shield TV 3.1 with Denon AVR-X2200W

### ISSUE THREAD

**Issue by scotch24** [koying/SPMC#257]
4K GUI is not working in combination with my DENON AVR.
Tried all HDMI input, also with passthrough settings.
The strange thing is when i connect the Shield direct to my Samsung TV everything is working as expected.
Other devices connected to my AVR are working fine with 4K.

Any idea ?
Thanks

**Comment by BubbaFatAss** [comment]
I have the same AVR / Shield / SPMC combination as you do, and after setting GUI Size to Unlimited and restarting, System Info reported SPMC rendering at 4k.

**Comment by scotch24** [comment]
Problem solved.
While i was playing around with Netflix i realized no 4K content was available.
Had to change the HDMI input on my TV because just 1 port supports HDCP 2.2
