### ISSUE TITLE
16.3.0 - All Video Causing Video Blackout And Dropped Frames

### ISSUE THREAD

**Issue by war59312** [koying/SPMC#259]
koying,

Afraid bad news.

Nvidia Shield TV and Pioneer 830

First Log: https://www.war59312.com/spmclogs/public/pvcqijtl2 or http://xbmclogs.com/pzch1ttft or http://spmclogs.semperpax.com/pxj4xwibi

2nd Log: https://www.war59312.com/spmclogs/public/pa1vebkn8 or http://xbmclogs.com/pwvrwfzfy or http://spmclogs.semperpax.com/p6tknmzfi

All videos are causing my TV to black out when I start a video.

And even when it does start to play it drops a good many times. And audio goes in and out or no Audio at all.

Some it even causes Shield to lockup and reboot.

Normally can get video to play OK after a few tries.

Can't install old version either without a total uninstall it seems. That's a first.

Get: "App not installed." when I attempt to intall older build now.

Wow, thanks Nvidia, that's real useful.

Thanks,

Will

**Comment by BhwSyd** [comment]
I am finding something similar with my x8-h plus. Audio dropouts (roughly half second at a time), stutters and drops with 16.3.0.

**Comment by war59312** [comment]
Fixed! :+1: 

Thanks to: "SHIELD Android TV Software Upgrade 3.2" :dancers:
