### ISSUE TITLE
SPMC from store not valid for Fire TV

### ISSUE THREAD

**Issue by ckuetbach** [koying/SPMC#27]
The app from the Amazon Appstore ( http://www.amazon.de/Semperpax-SPMC/dp/B00MK49LL8/ ) is not compatible with Fire TV Box.

If I sideload the apk from http://spmc.semperpax.com/ and sync my bought items to the box, the app appears and works fine.

In the AppInfo I find the Info "Not compatible with any controller". I think it may need just to be marked as kompatible with defaul controler and it will be available for the Fire TV.

Regards,
Christian

**Comment by TrueCitrus** [comment]
I was about to make the same post until I found this one. The app shows as incompatible with my Fire TV Stick. I tried "purchasing" it and side-loading the APK but it does not show up at all. How did you get it to show up?

**Comment by ckuetbach** [comment]
You'll need to synchronize your bought items in the settings menu.

You should use the non launcher Version.

**Comment by TrueCitrus** [comment]
I synchronized my purchases from the account settings section and I don't see anything. I loaded the non-loader version spmc-armeabi-v7a_13.3.3.apk. Do I need to rename the APK for it to recognize?

Are you using a Fire TV or Fire TV Stick?

**Comment by ckuetbach** [comment]
I use the Fire TV (the stick is not available in germany yet).

**Comment by ckuetbach** [comment]
After installing the spmc 1.3.4 the icon disappeared from the Amazon FireTV launcher.

I beleave  it is because of the different Version number compared to the amazon app store (there is still 1.3.3.3 available)

Can you upload the current version to that app store?

**Comment by mulliganman** [comment]
What is the non-launcher version of SPMC?  Anyone have a link?

**Comment by eskay993** [comment]
This workaround doesn't seem to work with 13.4.0 unfortunately. I have SPMC in my purchase list on Amazon, as well as sideloaded on my FTV, and syncing doesn't work. My box is rooted if that makes a difference.

@mulliganman If you download 13.4.0 from http://spmc.semperpax.com , then that is the non-launcher version by default.

**Comment by eskay993** [comment]
Actually, this now appears in my Recent Items list, but not in apps, so half way there. As ckuetbach says, under More Info for the app, it says "Works With: No Supported Controller" which includes the remote control so this may be where the issue is.
