### ISSUE TITLE
Might not be a real issue - AC3 Dolby Digital vs all other formats

### ISSUE THREAD

**Issue by Cherry-Dude** [koying/SPMC#280]
As mentioned, this might not be a real issue, but thought I should mention it just in case.
On my Shield all audio formats works flawlessly trough passthrough to receiver - except Dolby Digital AC3 which have extremely low volume. Is this just the nature of Dolby Digital or is there something I might have missed? If I disable passthrough (my current solution) the videos have some volume as all other formats. True HD is no problem by the way.

**Comment by heymoe** [comment]
Using passthough your receiver is getting the raw audio bit-stream to process. As such, it's your receiver that controls the volume of the decoded raw bit-stream audio plays back and not SPMC/Kodi.

Maybe you receiver has AC3 specific settings that you can tweak? 

I personally have a receiver that can decode all the current formats including Atmos and DTS:X and haven't notices any volume issues with the passthough formats. I do get some volume swings in non-passthough audio but that's normally related to the media being played back.

**Comment by Cherry-Dude** [comment]
Boy I feel a bit stupid…

My receiver does unfortunately not allow adjustments for different formats, but for some reason a general “Dialogue level” was set to – 5 dB, so that helped a great deal, at least with the dialogue.
Anyways should benefit from some more fiddling around, otherwise it might be time to upgrade the receiver (Denon AVR 2113)

Thank you for clearing this up, I hope no one else is as stupid, otherwise this might help them ;)
