### ISSUE TITLE
My webserver wont use 8080 as failed to start, can use any other port fine but then that means no reccomendations. how to fix this??????

### ISSUE THREAD

**Issue by slayerkodi** [koying/SPMC#281]

**Comment by slayerkodi** [comment]
if its not port 8080 it doesnt even show up in home screen - reccomendations

**Comment by slayerkodi** [comment]
just found out its something to do with utorrent, utorrent uses incoming port 6881, has no option for outgoing port so im gonna guess that is using port 8080. cant change that so guess ill just have to lose recommendations, would be nice if we can use whatever port we want to for recommendations

**Comment by heymoe** [comment]
I'm kind of in the same boat and I've already submitted a feature request to be able to use custom web server settings:

Feature Request Link: https://github.com/koying/SPMC/issues/185

**Comment by portfine** [comment]
8080 is just a bad port backdoors, email wormhole, remote access control like leaving the keys in the ignition and windows down with a for sale sign saying please steal me I'm free.
W W W32. Spybot

**Comment by portfine** [comment]
2080 4080 recommendations http://userprofiles/[X]port8080/slayerkodi/github.com
