### ISSUE TITLE
Voice search: bug or intended behaviour?

### ISSUE THREAD

**Issue by buongiorgio** [koying/SPMC#291]
Hi there,
I am running SPMC on a 16GB Shield, not rooted, firmware 3.1, Android 6.0. SPMC has being freshly installed (i.e. I did not import anything from Kodi), with Aeon Nox as skin and the global search add-on installed. I have found the followin behaviour and I do not know if is intended or it is a bug:
-I boot the shield (i.e. not "resumed");
-Launch SPMC;
-Press the voice search button on the Shield's remote when in the home of SPMC;
-The Shield voice search pops up (I mean, the same voice search that I have when I am in the home of the shield), I can perform a voice search (e.g. an actor's name) and I am redirected to the Shield's home with results from SPMC, youtube, google video;
-Now I return to SPMC's home;
-Launch the global search add-on;
-I press the voice search on the Shield's remote: a fields pops up and I can perform a search within SPMC (i.e. not redirected to the Shield's homepage).

Till this point everything is normal to me.

-Now after the search with the global search add-on, I return to SPMC's home page;
-I press the voice search on the remote expecting that Shield's search pops up as before, but nothing happen;
-I go to Shield's settings, kill SPMC, launch it again;
-Press the voice search button on the remote while being in SPMC's home and... Tada!, Shield's voice search pops up.

To me, the Shield's voice search while being in SPMC's home should run each time OR never.

I hope I had been clear in my explanation, if not please ask for clarifications.

Regards,
Gio

**Comment by koying** [comment]
Yep. The bug will be fixed in next version
