### ISSUE TITLE
'Imperial Streams' plugin not visible in SPMC

### ISSUE THREAD

**Issue by pdoth** [koying/SPMC#294]
I have both Kodi and SPMC installed with Pulse CCM build on both. Both running Mucky Ducks latest repo. On Kodi I installed 'Imperial Streams' from repo. However, this addon does not even show up in SPMC version (16.3).

Any ideas?

**Comment by koying** [comment]
No video addon support. Better asked to the author.

**Comment by pdoth** [comment]
OK, thanks. BTW, great work on your version. Works a charm :)
