### ISSUE TITLE
TV show episode thumbnails appear to be rendered in 1080, not directly in 4K

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#297]
I am using SPMC in 4K with the settings I describe here:
http://forum.kodi.tv/showthread.php?tid=264102&pid=2326338#pid2326338

I am using the FTV skin by Sualfred and Hitcher.
http://forum.kodi.tv/showthread.php?tid=253058

I have created my own HD (1920x1080) thumbnails as described here:
http://forum.kodi.tv/showthread.php?tid=276774

The jacket art for movies and TV shows look very crisp, with no jaggies. 

However, the TV episode thumbnails look soft by comparison. It's like the 1920x1080 source image is down-sampled and then up-sampled to the thumbnail size on the episode listing screen. I think what's happening is that the TV show episode thumbnails are being scaled down to the 640x480 target for a 1080 resolution screen, then those images are scaled up 2x for 4k output. It should be scaling the 1920x1080 down to 1280x960. 

Hitcher believes this is a Kodi/SPMC issue, not a skin issue. See exchange here:
http://forum.kodi.tv/showthread.php?tid=253058&pid=2347514#pid2347514

**Comment by koying** [comment]
I replied in thread.
You probably need to alter http://kodi.wiki/view/advancedsettings.xml#imageres, then regenerate the thumb cache (removing Texture13.db should do).

**Comment by classicjazz** [comment]
Yes, I was already using <imageres>2160</imageres>. And I deleted  Texture13.db. That made no differences. Additional details are in the thread, where I also replied.

**Comment by classicjazz** [comment]
When I opened this issue, I focused on thumbnails that I generated with an FFMPEG script in 1080 resolution. They were read along with local metadata and then stored in the video library.

There's a separate but related issue of thumbnails generated automatically by SPMC/Kodi that appear to be much lower resolution than 1080. In this second case, I have a directory of shows saved by my PVR. SPMC extracts the images automatically.

I would expect both existing images and images scraped by SPMC/Kodi to honor the parameters in my advancedsettings.xml file, which is described here:
https://github.com/koying/SPMC/wiki/Sample-advancedsettings.xml

including
`<imageres>2160</imageres>`

**Comment by classicjazz** [comment]
There's a reference in the Krypton changelogs to the following:

_Changed GetThumbSize() to m_imageResso so bookmark/chapter images are same resolution as posters_ 

I am not sure whether this commit would address the issue. I tried testing Krypton Alpha 2 on the Shield but, among other issues, it doesn't seem to support 4K GUI so I can't test whether the TV show episode thumbnails would be as crisp as the jacket art.

**Comment by classicjazz** [comment]
@koying Can you please take a look at this commit for Kodi 17:
https://github.com/xbmc/xbmc/pull/9175/commits/ae5bb99756aece6686297a2a29dfafbfd8438ae5

**Comment by Hitcher** [comment]
Have you checked the size of the thumbs Kodi is creating in the Thumbnails folder?

**Comment by classicjazz** [comment]
Thanks Hitcher for joining the thread. Hitcher clarified that his commit referenced above only applied to bookmarks.

I have attached sample images (original and cached).  
[thumbnails.zip](https://github.com/koying/SPMC/files/420318/thumbnails.zip)

Image caching is using these settings:

```
<fanartres>2160</fanartres>
<imageres>2160</imageres>
<imagescalingalgorithm>lanczos</imagescalingalgorithm>
```

Resolution remains the same though cached image size increases roughly 20%. (One would think that the caching algorithm would simply use the original image if it's the same resolution and smaller file size).

As Hitcher noted here, a different, additional scaling algorithm then appears to be applied to the cached image when resized for as required by the skin:
http://forum.kodi.tv/showthread.php?tid=200401&pid=2117089#pid2117089

What's weird is that jacket art with a 4K GUI looks incredibly detailed (in all sizes) while TV episode thumbnails pulled from the same cache look much more blurry. One would expect them to be universally good (fine resolution) or bad (relatively blurry).

**Comment by Hitcher** [comment]
There only seems to be one set of thumbnails in that folder.

Also, have you tried using a skin that displays episodes in fullscreen?

**Comment by classicjazz** [comment]
I think you are asking for a comparison of TV episode thumbnails to jacket art thumbnails.

The TV episode thumbnails are 1920x1080 (original=cache).

Some sample jacket art thumbnails are attached. Source images are 2000x3000. Cached images are scaled down to 720x1080 (notwithstanding the 2160 advancedsetting).
[jacket.zip](https://github.com/koying/SPMC/files/420896/jacket.zip)

If you recommend a skin displaying episodes in full screen, I will test it.

**Comment by Hitcher** [comment]
https://github.com/HitcherUK/skin.copacetic has fullscreen episode views
