### ISSUE TITLE
Stuttering while playing 29.97 / 59.94 fps content on Nvidia Shield 3.1

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#301]
I have certain video files that stutter heavily. Playing on SPMC 16.3 on a Nvidia Shield TV v3.1 to a Samsung UHDTV. Using HQ scalers with Lazcros3 Optimized as described here: http://forum.kodi.tv/showthread.php?tid=264102&pid=2326338#pid2326338

FFMPEG shows:

```
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc
    Stream #0:1: Audio: dts (DTS-HD MA), 48000 Hz, stereo, s16p (default)
    Metadata:
      title           : Lossless
    Stream #0:2: Subtitle: hdmv_pgs_subtitle
```

SPMC codec info says its playing at 59.94.

By comparison, here's a later season's episode. This doesn't skip.

```
  Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc
     Metadata:
       LANGUAGE        : eng
       DURATION        : 01:36:40.461000000
     Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, stereo, s16p (default)
     Metadata:
       title           : Lossless
       LANGUAGE        : eng
       DURATION        : 01:36:40.457000000
     Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle
     Metadata:
       LANGUAGE        : eng
       DURATION        : 01:36:25.467000000

```

SPMC codec info reports 23.976fps. 

Many of my movies report:

```
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc

```

And these play flawlessly.

It's not a network issue (the latter file streams at 40Mbps with no drops). I am connected via GigE to the NAS. My network settings follow:

```
   <network>
           <buffermode>1</buffermode> <!-- Buffer all filesystems (including local)  -->
           <cachemembuffersize>209715200</cachemembuffersize> --> <!-- 200MB buffer  -->
        <readbufferfactor>20</readbufferfactor>
    </network>
```

So I think it's something specific to 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc

I am not sure whether this is a Kodi issue or a Shield TV v3.1 issue. If the latter, it might be fixed with the forthcoming v3.2 release. I don't have access to v3.2 beta to test though.

https://forums.geforce.com/default/topic/919324/shield-android-tv/update-3-0-netflix-stutter-on-23-976hz-output-/post/4888226/#4888226

**Comment by classicjazz** [comment]
Here's the relevant entries from the log when I see the stuttering:

``

09:18:16 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - dup error(686186.660772), clock(256476813.339228), correction(682666.666667)
09:18:16 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - skip error(-36304.940359), clock(257198829.064895), correction(10666.666667)
09:18:16 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - skip error(-35919.620081), clock(257198324.689228), correction(10666.666667)
09:18:16 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - skip error(-36585.028803), clock(257198460.834561), correction(10666.666667)
09:18:16 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - skip error(-34922.990525), clock(257197485.937895), correction(10666.666667)
09:18:16 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - skip error(-35367.306248), clock(257197616.875228), correction(10666.666667)
09:18:21 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - dup error(38437.820925), clock(250750861.617175), correction(32000.000000)
09:18:21 T:1488910640  NOTICE: CDVDPlayerAudio::OutputPacket forcing clock sync for passthrough - dup error(34636.416925), clock(250808573.594175), correction(32000.000000)

``

**Comment by classicjazz** [comment]
Actually, there's a lot of these errors too:
07:34:46 T:1609550128   ERROR: CDVDVideoCodecAndroidMediaCodec::GetOutputPicture ExceptionCheck; dequeueOutputBuffer
07:34:46 T:1609550128   ERROR: CDVDVideoCodecAndroidMediaCodec::Decode ExceptionCheck

**Comment by koying** [comment]
> SPMC codec info says its playing at 59.94

That's surely the root causes of the log entries you report, that's why I'd need the file to understand what specific about it.

**Comment by classicjazz** [comment]
This appears to still be an issue in Shield v3.2. Did the test file I shared with you help to diagnose?
