### ISSUE TITLE
Optimal 4K settings for both GUI and video on Android (NVIDIA Shield)

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#305]
There was some discussion in the Kodi forum about the correct video settings. I am creating this ticket to clarify and then update the Wiki accordingly.

First, it appears that Kodi 16 (and therefore SPMC) shifted to a 1080p GUI with support for up to 4K output
https://kodi.tv/kodi-16-0-alpha-4-jarvis-nearing-completion/
http://forum.kodi.tv/showthread.php?tid=260932&page=5

For most Android devices including even AFTV2 (which is 1080p GUI and 4K video), therefore, you should enable mediacodec (surface) rendering.

Similarly, if you have have an HD/FHD TV--not a UHD (4K) TV--you should use mediacodec (surface) rendering.

If you have an NVIDIA Shield Android TV settop, it is uniquely able to support both a 4K GUI and to render 4K video. Using the HQ scaler settings will upsample lower resolution video to 4K output. The UHD TV scalers will not be used then and you should enable SPMC's scalers instead.

The current draft of the SPMC+Shield+UHDTV document on the Wiki walks through how to enable the scalers and deinterlacers. It's my understanding that mediacodec should be enabled and mediacodec (surface) should be disabled in order to support both 4K GUI and 4K video. 

Other than some edge cases related to specific video fps, this works well for me on Samsung and Vizio UHDTVs with Shield TV v3.1, with and without an AVR in the middle. The edge case video skipping will hopefully get resolved either in Shield v3.2 or a later version of SPMC. CPU load for 1080p content with scalers enabled is 20-40% per codecinfo.

I haven't tested it with native 4K content though.

Even on the Shield, there might be some edge cases related to color space settings and 8v10 bit content:
https://forums.geforce.com/default/topic/923547/?comment=4835395

**Comment by classicjazz** [comment]
Fritsch recommends keeping the resolution at 1080p because the Kodi scaler is so bad (UHD TV's scaler must be better). Koying confirms that app's can't change resolution in Android (therefore you are stuck with Kodi scaler).
http://forum.kodi.tv/showthread.php?tid=241359

 lanczos3 - optimised is the best available upscaler in Kodi. But it could be better.

One alternative is MadVR but it is Windows-based and closed-source.
http://forum.kodi.tv/showthread.php?tid=223175&page=151

MPV supports a number of upscalers and is open source.
https://github.com/haasn/mpvhq-upscalers/blob/master/Rose.md

Two different methods in MPV seem to be better than Kodi's lanczos3 - optimised, if they could be ported to Kodi:

```
scale=ewa_lanczossharp:scale-antiring=1
```

or

```
core.nnedi3.nnedi3_rpow2(video_in, 8).set_output()
```

**Comment by koying** [comment]
Fritsch is fundamentaly right regarding giving preference to your TV scaler, but if you want 4K anywhere on your device (for Nertflix, f.e.) you must set the device in 4K, and the TV scaler is out of the loop. You then are left with the choice of using Kodi or the device to do 1080p > 4k upscale.
As I personally have no 4K content, I indeed run in 1080p. 

Re running Kodi GUI in 4K, there are a limited set of use cases:
- You want to show 4K pictures inside Kodi
- You want fine-grained control on your 4K videos (mediacodec(S) offers basically no control)
- You prefer the Kodi upscalers vs. the Shield (f.e.) one.

In all other cases, best is probably to let GUI at default (=1080p) and let Shield do the upscaling. 4K content will automatically use mediacodec(S) to show true 4K.

**Comment by tchirou** [comment]
Hello

To clarify if you have a 4K tv, 4k & 1080p & 720p media files but not enough bandwith (or need) to have youtube or netflix in 4K, it is better to let the tv do the upscale.

To do so, we need to : 
- put the shield TV in 1080p

in SPMC > Videos > Acceleration
- enable HQ scalers = never
- allow hardware acceleration - Mediacodec (Surface) = on
- allow hardware acceleration - Mediacodec = on
- accelerate MPEG2 = always
- accelerate MPEG4 = always
- accelerate h264 = always

Am I missing something ? Sorry but it gets a little confusing

Edit : I must be mistaken because the small purple text is not legible with these settings.

**Comment by DaMacFunkin** [comment]
I have now set my settings to output 1080p and let the TV do the scaling, the picture is much better, only problem is what happens when I need to play a 4K file via spmc, will it down convert to 1080p?

**Comment by classicjazz** [comment]
I think the decision tree is as follows:

**1. I own a Shield Android TV settop**

**_1a. I own an UHD TV and watch 2160p content (e.g. in SPMC, YouTube or Netflix)_**
- You should use the Shield settings currently described in the Wiki. 
- Your GUI will be in 4K. 
- All content <=2160p will play at 2160p resolution. 
- Content <=1080p will be upscaled with SPMC's HQ scalers but may not look as good as your UHD TV's scalers, which are not used.

**_1b. I only watch content <=1080p in any Android app._**

We need a Wiki entry that describes the following:
- You should set your Shield TV maximum resolution to 1080p.
- You should set SPMC GUI resolution limit to 1080. 
- You should use SPMC's HQ scalers and all other settings described in the current Wiki entry.
- Your GUI will be in 1080p.
- All content will play at 1080p resolution. 
- Content <1080p will be upscaled with SPMC's HQ scalers. 
- If you have a UHD TV, its scalers will upsample the 1080p output to 2160p. Content at <=1080p resolution may look better than scenario 1a due to the UHD TV scalers.  

**2. All other Android settop boxes and dongles including Fire TV and Mi Box.**

We need a Wiki entry that describes the following:
- You should set your Android settop to its maximum resolution (e.g. 1080p or 2160p).
- You should set SPMC GUI resolution limit to 1080. 
- You should enable Medicodec surface rendering.
- You should not use SPMC's HQ scalers because your settop likely isn't powerful enough.
- Your GUI will be in 1080p.
- All content will play at 1080p resolution, except for 2160p content which will play if you have a UHD TV and a capable settop (e.g. Fire TV 2). 
- Content <1080p will be upscaled by SPMC but won't look as good as HQ scaler upscaled content. 
- If you have a UHD TV, its scalers will upsample the 1080p output to 2160p. Content in <=1080p resolution may look better than scenario 1a due to the UHD TV scalers.  

Addressing scenario 1a's <=1080p video upscaling as compared to UHD TV scalers:
- Perhaps SPMC could implement an alternative to the current "_lanczos3 - optimised_" similar to MPV's  "_vo=opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossoft
  hwdec=auto_". This could eventually work across settop boxes, as they become more powerful.
- Nvidia may have Maxwell-specific MFAA scaler and deinterlacer APIs that are lower overhead. Android-specific information here seems to be scarce. I emailed them for more details.

**Comment by classicjazz** [comment]
I created 2 new Wiki pages based on the outline above.

For 1b: **Recommended video settings for SPMC and NVIDIA Shield TV with 1080p GUI**
https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC-and-NVIDIA-Shield-TV-with-1080p-GUI

For 2:  **Recommended video settings for Android devices (other than Nvidia Shield)**
https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-Android-devices-(other-than-Nvidia-Shield)

Please take a look at these page to see if there are any errors. I will add them to the main page of the Wiki in a few days.

**Comment by classicjazz** [comment]
These pages are now linked on the front page of the Wiki.

**Comment by VirTERM** [comment]
just to clarify, for Sony Android TV's such as 930D I should be using something like:
enable HQ scalers = **never**
allow hardware acceleration - Mediacodec (Surface) = on
allow hardware acceleration - Mediacodec = off
accelerate MPEG2 = always **???**
accelerate MPEG4 = always **???**
accelerate h264 = always **???**

**Comment by tibidt** [comment]
I have the same Sony Android TV and no Nvidia Shield or other box for the moment.
Will/should 4k video playback from a 4k source work ? How could I check ?
I know interface is "stuck " in 1080p, but this is no issue.
What are the recommended settings for 4k playback ?

**Comment by lukehansford** [comment]
What settings do we need to set for 2016 Sony android TVs?.

Should we set never to hq scalers?. GUI is limited to 1080p. Is this correct and why is this limited to that?.

**Comment by lukehansford** [comment]
I mean to upscale 720 and 1080 content to 4k correctly ?
