### ISSUE TITLE
Feature Request: advancedsettings.xml option to clean orphaned thumbnails

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#308]
16.2.1 added the ability to manually remove orphaned thumbnails through the GUI. Thank you.

I may have missed it, but could we add an option in advancedsettings.xml to automatically remove orphaned thumbnails whenever the library is updated, similar to how clean library can be automated with:

```

    <videolibrary>
        <cleanonupdate>true</cleanonupdate> <!-- Also clean library during library update -->
    </videolibrary>

```

That way the library is updated, old library entries are also cleaned, and orphaned thumbnails are also removed.

**Comment by ghost** [comment]
Very cool, I didn't know we could do that!  I'm adding this to my advancedsetting.xml
