### ISSUE TITLE
Remove cache before opening plugin urls from shortcut

### ISSUE THREAD

**Issue by coolllman** [koying/SPMC#316]
As a plugin is mostly online content the cache should be removed before opening to make sure we get latest content.
https://github.com/xbmc/xbmc/pull/9898
Please add this.

**Comment by coolllman** [comment]
https://github.com/xbmc/xbmc/issues/10394

**Comment by koying** [comment]
Makse sense...

**Comment by koying** [comment]
Actually causes more harm than good.
Reverted.
