### ISSUE TITLE
current android apk present itself as a debug build

### ISSUE THREAD

**Issue by renierr** [koying/SPMC#32]
Was it by intention or by mistake, that the current apk from the website present itself as a debug build.
Version 13.4.0 from here http://spmc.semperpax.com

As I seen on this commit bff57183585c1fa0acbbf4a3f116104f3dfa826f
There was a misbehavior in the build system.

It would be nice if we can disable the logging complete independent of a build.

**Comment by koying** [comment]
Oversight, indeed. Default is debug and I didn't specify release.

**Comment by renierr** [comment]
Thanks for the quick answer. Possible to get a new release build?
The TV box is flooded with debug logs.

**Comment by renierr** [comment]
the New 14.1 build is again a debug build.
So logfiles will grow big and we are not able to disable them.

**Comment by codexaxiu** [comment]
renierr, are you sure it's on debug build even on 14.1? 

I notice kodi since 14.1 and after are all growing in data size as well. 

Since v14 and on, i switch back to Kodi instead. SPMC doesnt help much on data space or loading speed anyway.

**Comment by renierr** [comment]
Pretty sure here are the first rows of my log, see for yourself

:50:21 T:1783508664  NOTICE: special://profile/ is mapped to: special://masterprofile/
11:50:21 T:1783508664  NOTICE: -----------------------------------------------------------------------
11:50:21 T:1783508664  NOTICE: Starting spmc (14.1 Git:2015-02-13-68ec995-dirty). Platform: Android ARM 32-bit
11:50:21 T:1783508664  NOTICE: Using Debug spmc x32 build
11:50:21 T:1783508664  NOTICE: spmc compiled Feb  7 2015 by GCC 4.8.0 for Android ARM 32-bit API level 14 (API level 14)
11:50:21 T:1783508664  NOTICE: Running on MBX NEO-X8-H with Android 4.4.2 API level 19, kernel: Linux ARM 32-bit version 3.10.33
11:50:21 T:1783508664  NOTICE: FFmpeg version: 14.0-Helix-258-g2dfa829-xbmc-2.4.6-Helix
11:50:21 T:1783508664  NOTICE: Host CPU: ARMv7 Processor rev 1 (v7l), 2 cores available
11:50:21 T:1783508664  NOTICE: Product: k200, Device: NEO-X8, Board: NEO-X8 - Manufacturer: MBX, Brand: MINIX, Model: NEO-X8-H, Hardware: amlogic
11:50:21 T:1783508664  NOTICE: ARM Features: Neon enabled
11:50:21 T:1783508664  NOTICE: special://xbmc/ is mapped to: /data/data/com.semperpax.spmc/cache/apk/assets
11:50:21 T:1783508664  NOTICE: special://xbmcbin/ is mapped to: /data/data/com.semperpax.spmc/cache/apk/assets
11:50:21 T:1783508664  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc/userdata
11:50:21 T:1783508664  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc
11:50:21 T:1783508664  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc/temp
11:50:21 T:1783508664  NOTICE: The executable running is:
11:50:21 T:1783508664  NOTICE: Local hostname: localhost
11:50:21 T:1783508664  NOTICE: Log File is located: /storage/emulated/0/Android/data/com.semperpax.spmc/files/.spmc/temp/spmc.log
11:50:21 T:1783508664  NOTICE: -----------------------------------------------------------------------
11:50:21 T:1783508664  NOTICE: load settings...

**Comment by renierr** [comment]
Solved. See latest release 14.2.0
