### ISSUE TITLE
i have 2 diffrent android boxes, both diffrent models, i installed spmc 16.3 and on both boxes when you do a search for a movie on any of the apps it always closes spmc and takes me back to the desktop, any ideas

### ISSUE THREAD

**Issue by lbeltran13** [koying/SPMC#326]

**Comment by heymoe** [comment]
You're going to need to provide a copy of your spmc.log file.

**Comment by ghost** [comment]
Upload your log file to pastebin.com

**Comment by lbeltran13** [comment]
Actually, I think I figure it out, I was running Confluence++ Skin, which when installing said there were some issues with versions 15 and 16, but thought I would try it because is my favorite skin.
I went back to the stock Confluence skin the issues disappeared, is working fine now

**Comment by heymoe** [comment]
Cool.. Please close this issue report since you solved your problem.. Thanks!

**Comment by Etiwanda90** [comment]
I am having the same issue on my boxes as well.

**Comment by lbeltran13** [comment]
try changing the skin, that fixed it on mine
