### ISSUE TITLE
MKV / x264 AAC SD video stuttering on Amazon Fire TV Version of SPMC (13.3)

### ISSUE THREAD

**Issue by donalberto223** [koying/SPMC#33]
Hello,

I have tried to watch several SD videos encoded with x264 and AAC 2.1 Audio. I can not properly watch it on ATV because it starts stuttering after watching 10-30 sec. Is this issue known? Any resolution to it?

I tried Kodi 14.0 on ATV and it also stutters. But very differently and not so bad. Still cant use it to watch the episodes normally.

thanks
Don

**Comment by adairjim** [comment]
13.4 fixed that issue

**Comment by donalberto223** [comment]
Just updated and testing. looks good so far. everything's very smooth.
thanks!!!

[EDIT] - issue completely resolved with 13.4!
