### ISSUE TITLE
Fix droid DVD ISO Playback

### ISSUE THREAD

**Issue by mo123** [koying/SPMC#339]
DVD ISO Playback is broken in Jarvis on Android and also in SPMC Jarvis.
MrMC fixed it here
https://github.com/MrMC/mrmc/commit/cc3b3aa179e1e2d0d0489aa56066bdace724a01c

But all these commits will also be necessary to change the folder location of libdvd from
xbmc/lib/libdvd/ to xbmc/xbmc/tree/master/tools/depends/target like it is done in Kodi Krypton alpha.
https://github.com/MrMC/mrmc/commits/master/tools/depends/target/libdvdcss
https://github.com/MrMC/mrmc/commits/master/tools/depends/target/libdvdnav
https://github.com/MrMC/mrmc/commits/master/tools/depends/target/libdvdread

Please merge new DVD ISO code for Android and backport to SPMC.

**Comment by koying** [comment]
Still no word on what is supposed to be broken...

**Comment by Uukrull** [comment]
Isos with SPMC need a lot of time before they are played (SPMC compiled for Windows doesn't have this problem). I get tons of seek errors with all the isos I tried. For example, this one needs more than a minute before the playback starts:

> 14:53:07 T:1434786096    INFO:   msg: libdvdread: Get key for /VIDEO_TS/VTS_04_0.VOB at 0x00134c1c
> 14:53:07 T:1434786096   ERROR: Seek - Error( seekpos: -1704927232, whence: 0, fsize: 6519261184, lseek call failed with "")
> .
> .
> 14:54:23 T:1434786096   ERROR: Seek - Error( seekpos: -2077386752, whence: 0, fsize: 6519261184, lseek call failed with "")
> 14:54:23 T:1434786096    INFO:   msg: libdvdread: Error cracking CSS key for /VIDEO_TS/VTS_08_1.VOB (0x003085b3)!!

or this one:

> 14:55:45 T:1404524848    INFO:   msg: libdvdread: Get key for /VIDEO_TS/VTS_02_0.VOB at 0x003a3e33
> 14:55:45 T:1404524848   ERROR: Seek - Error( seekpos: -772696064, whence: 0, fsize: 8148756480, lseek call failed with "")
> .
> .
> 14:57:19 T:1404524848   ERROR: Seek - Error( seekpos: -463970304, whence: 0, fsize: 8148756480, lseek call failed with "")
> 14:57:19 T:1404524848    INFO:   msg: libdvdread: Error cracking CSS key for /VIDEO_TS/VTS_04_1.VOB (0x003c8b0c)!!

Full debug log: http://paste.semperpax.com/pt31odlz6

**Comment by koying** [comment]
Thanks for the details.
Fixed: https://github.com/koying/SPMC/commit/507bd0eb9eff889a35961db1b71eeed095ed3b50
