### ISSUE TITLE
wanting to know how to add my own files to the spmc apk

### ISSUE THREAD

**Issue by thehamby** [koying/SPMC#342]
im wanting to add my own files to the apk. i have it all setup how i like and i want to make it a install and not have to go through finding them on my device. someone please help

**Comment by heymoe** [comment]
I'm pretty sure this is outside the scope of any sort of support / bug issue reporting for SPMC. 

To do what you're asking you could a) checkout the SPMC code (GIT), add your files and compile it into your own APK or b) Google "repackage APK" or something along those line.

**Comment by koying** [comment]
Unrelated to SPMC
