### ISSUE TITLE
Shield mpeg2 hardware acceleration and SD

### ISSUE THREAD

**Issue by DannyCL** [koying/SPMC#344]
While mpeg2 hardware acceleration is always on:
Playing mpeg2 sd movie always stuttering after 10 or 15 minutes playing.
Mpeg2 hardware acceleration HD and above give no stuttering and more cpu use;

**Comment by 99rook99** [comment]
Unless you want Koying to use his magic eight ball, to figure out what is wrong, he is probably going to need a debug log.

**Comment by DannyCL** [comment]
Fixed via shield update 3.2
