### ISSUE TITLE
RKStageFright crashes when changing channels

### ISSUE THREAD

**Issue by ricardofcf** [koying/SPMC#35]
I'm running SPMC 13.4 on my Tronsmart Orion R28 Pro (RK3288). When using IPTV Simple Client, I'm able to select and successfully play any channel from the list or the EPG. However, when playing fullscreen, if I try to go up and down, either with the remote or the OSD, SPMC crashes (I believe it's actually being caused by librkstagefright). Below you'll find part of my xbmc log. Let me know if I can provide any other relevant data.

http://pastebin.com/2kVf3zKF

**Comment by aimuzov** [comment]
+1

**Comment by ricardofcf** [comment]
Still happening with 14.1.0

**Comment by Shadi86** [comment]
Hi<br />
<br />
I have a rk3288 box from hph.<br />
<br />
I have been use spmc without a any problem especiale when it become to movie and full HD, it's playing it like a charm! <br />
<br />
So now to my problem, I have begin use TVHeadend on spmc and got many problem, when I play a channel I get black playback and got only sound,  but when I unchecked RKlibstagefright hardware accelerateed the black playback it's disappear and everything it's fine, I have also a minix neo 8h box and it's playing the channels without a problem with spmc.
