### ISSUE TITLE
Rockchip

### ISSUE THREAD

**Issue by skakun99** [koying/SPMC#350]
I'm wondering with the future of spmc it was was noted no specific support regrading rock chip.  Does this mean spmc won't work with spmc? I'm rather ignorant with this kinda stuff but I'm trying.  Can anyone elaborate?

**Comment by skakun99** [comment]
Oh snap I mean rock chip with spmc

**Comment by mjbxx** [comment]
Bingo!

**Comment by skakun99** [comment]
Bingo?

**Comment by koying** [comment]
No special treatment, so if rockchip works with mediacodec, it will work with spmc.
