### ISSUE TITLE
Internet radio streaming doesn't stop when you watch video in another app

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#356]
As best as I can tell, SPMC keeps streaming in the background. 

To replicate, listen to an internet radio station (I use PLS files). 
If you go to Leanback Launcher, the radio station continues to play, as expected.
Start video playback in another app such as HDHomerun View. The audio switches for the duration of video playback to the new app (e.g. HDHomerun View).
As soon as video playback ends, the internet radio station audio can be heard again, in real-time.

**Comment by koying** [comment]
Mmm... I don't get the "wrong" part in this. What are you expecting?

**Comment by classicjazz** [comment]
Well, let's say that you watch several hours of TV in HDHomerun, using my example above. Then the streamed internet radio station is needless consuming data that noone can hear.

I don't think this is a case of the internet radio station stopping then restarting, with no data consumed in the interim, because there is no buffering occurring like when you first load a station. And because it's real time, its also not just resuming playback from a buffer.

I can check the firewall to confirm if needed.

**Comment by koying** [comment]
Please check actual consumption. The flow is paused, so I assume it doesn't actual run in background.

**Comment by classicjazz** [comment]
Watching the firewall connection by device, I see the Shield continue to consume data (136-170Kbps on average) regardless of whether I am listening to radio within SPMC or Leanback, watching a locally recorded TV show in HDHomerun View or watching tuned IPTV in Live Channels. This shouldn't be the case for HDHomerun or Live Channels because they are tuning TV from my LAN, not WAN. 

As soon as I stop the radio station in SPMC, data consumption on the firewall falls to 0Kbps.

The user experience tends to differ by app. For HDhomerun View, the internet radio station audio resumes as soon as I finish playing a recorded show. For Live Channels and Youtube, after playing a TV channel or Youtube video, the user does not hear the internet radio station again. So, a user would believe that they are no longer consuming data because they cannot hear any internet radio audio. In the case of Live Channels and Youtube, even if the user returns to SPMC, the internet radio audio is not heard. The issue is that the data that I believe is associated with that stream (136-170Kbps) continues to be consumed until you select Quit in SPMC. At that point, data drops to 0Kbps as expected.
