### ISSUE TITLE
Shield 3.2 not 4K output

### ISSUE THREAD

**Issue by stanthewizzard** [koying/SPMC#358]
Hello

With gui unlimites
4K mkv are displayed in 1920x1080
Zoom to original only shows 1/4 of the picture

Bug or settings errors ?
Thanks for help

**Comment by devabuse** [comment]
https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC,-NVIDIA-Shield-TV-and-UHD-(4K)-TVs-with-4K-GUI

Maybe that will help on the settings bit.

**Comment by stanthewizzard** [comment]
Work like a charm on hdmi hdcp 2.2 after a reboot
Strange strange
Thanks
