### ISSUE TITLE
Improved Upscaler for SPMC

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#359]
There has been discussion about the state of Kodi/SPMC's upscaling of <2160p content v UHD TV native upscalers. The purpose of this issue is to foster discussion of potential improvements to Kodi/SPMC's scalers based on comparable open source solutions. 

The goal is to have hardware-accelerated upscaling of 480i, 720p, and 1080i/p content such that users of SPMC on Shield TV (Android)--and, ultimately, Kodi users with advanced GPUs--have a better solution than using Kodi existing scalers for <1080 resolution followed by UHD TV scalers from 1080 to 2160 resolution. 

---

Current SPMC 16.3 upscalers are defined here (last commit 2yrs ago):
https://github.com/koying/SPMC/tree/spmc-jarvis/xbmc/cores/VideoRenderers/VideoShaders

XBMC 17alpha2 upscalers are defined here:
https://github.com/xbmc/xbmc/tree/master/xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders

The only change in v17 code appears to be rename dvdplayer to VideoPlayer.

---

SPMC supports HQ scalers on the Nvidia Shield, which has a Maxwell-class Nvidia GPU. The best current scaler is Lanczos3 - optimised.
https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC%2C-NVIDIA-Shield-TV-and-UHD-%284K%29-TVs-with-4K-GUI

Other threads suggest that MPV appears to be the best open-source, cross-platform alternative to MadVR.

Within MPV, potential presets (which may be too much for the Shield) include: 
**High preset**

```
vo=opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossoft
hwdec=auto
```

**Highest preset**

```
vo=opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:prescale-luma=superxbr:prescale-downscaling-threshold=1.5
```

https://yuki.la/g/54176289

From the MPV docs:
**ewa_lanczos**
Elliptic weighted average Lanczos scaling. Also known as Jinc. Relatively slow, but very good quality. The radius can be controlled with scale-radius. Increasing the radius makes the filter sharper but adds more ringing. (This filter is an alias for jinc-windowed jinc)

**ewa_lanczossharp**
A slightly sharpened version of ewa_lanczos, preconfigured to use an ideal radius and parameter. If your hardware can run it, this is probably what you should use by default.
https://github.com/mpv-player/mpv/blob/master/DOCS/man/vo.rst

---

MPV filters are defined here:
https://github.com/mpv-player/mpv/blob/master/video/out/filter_kernels.c

Some code is based on Glumpy, here:
https://github.com/glumpy/glumpy/blob/master/glumpy/library/build-spatial-filters.py

And Imagemagick's magick/resize.c
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/resize.c

```
// Radius is based on the true jinc radius, slightly sharpened as per
// calculations by Nicolas Robidoux. Source: Imagemagick's magick/resize.c
{{"ewa_lanczossharp", 3.2383154841662362, jinc, .blur = 0.9812505644269356,
      .resizable = true}, .polar = true, .window = "jinc"},
    // Similar to the above, but softened instead. This one makes hash patterns
    // disappear completely. Blur determined by trial and error.
{{"ewa_lanczossoft", 3.2383154841662362, jinc, .blur = 1.015,
     .resizable = true}, .polar = true, .window = "jinc"},
```

---

SuperXBR in addition to the ewa_lanczossharp may be overkill for the Shield (particularly for film content) but there is this repository here:
https://github.com/bjin/mpv-prescalers/blob/source/superxbr.py based on
https://github.com/Hyllian/glsl-shaders

So I would recommend starting with a ewa_lanczossharp shader based on MPV.

**Comment by 99rook99** [comment]
The last commit for SPMC was 3 months ago for the HQ scalers, when Koying added the rest of the scalers that were disabled on Android.  However I would love to have an improved scaler.

**Comment by 99rook99** [comment]
Since, I own a lot of dvds that I really don't want to replace, I would always welcome improved upscalers. The only thing I'm wondering, is would the work required for improved scalers be worth the work required to implement is. As it stands right now @Koying, is the only one developing SPMC, and I have no idea how long it would take to implement.  I also would like to see SPMC / KODI switched to use Vulkan instead of using Open Gles

**Comment by classicjazz** [comment]
Picture quality and comparisons to UHD upscaling are one of the most frequent discussion topics here and on related forums. People with a 4K settop (Shield) and 4K TV are running at 1080p resolution because SPMC/Kodi's upscaling isn't as good. 

An OpenGL implementation could be used on other platforms and has existing open-source code to borrow from and developers that know it well. Vulkan holds the promise of lower overhead at a given frame rate: https://developer.nvidia.com/vulkan-android

But the only open source project that I am aware of that has created even a Vulkan sink (not upscaler) is a preliminary version in gstreamer:
https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/vulkan/860548-gstreamer-1-8-brings-initial-vulkan-api-support

**Comment by 99rook99** [comment]
I was hoping that in Kodi 17, with the rewrite /modernization of dvdplayer to videoplayer, we would have seen an improved upscaler.  I would think this didn't happen as I would imagine that redoing the video system was very time consuming, to worry about upscalers.  Let's face it, if it was something easy or fast to do someone would have added it to Kodi.  I'm still hoping that it will someday happen, but I don't believe that it will happen in the near future.

**Comment by classicjazz** [comment]
Closing this issue. I am covering ongoing research here: http://freetime.mikeconnelly.net/archives/1206
