### ISSUE TITLE
Compiled SPMC and result was com.semperpax.spmc not com.semperpax.spmc16

### ISSUE THREAD

**Issue by radioactivetoy** [koying/SPMC#362]
Hi, 
I managed to compile SPMC but when I installed it it did not update the version I had. I checked and my compiled version is called com.semperpax.spmc and not com.semperpax.spmc**16** as the old one. Is this a recent change or I did something wrong?

Thanks

**Comment by koying** [comment]
It's on purpose, so that self-compiled tests could be installed along releases.

**Comment by radioactivetoy** [comment]
Makes sense! Could you tell me what to change so it generates com.semperpax.spmc16? Maybe just changing version.txt "APP_PACKAGE com.semperpax.spmc" to "APP_PACKAGE com.semperpax.spmc16" an running make apk again?

Thanks

**Comment by radioactivetoy** [comment]
To answer my own question, changing version.txt, doing a make -C tools/depends/target/xbmc release && make && make apk seems to work.

**Comment by koying** [comment]
Yep, indeed ;)

**Comment by koying** [comment]
Note that it's probably not worth it as the signature will be different from the release, so they will not be interchangeable, anyway.

**Comment by radioactivetoy** [comment]
Well, until now I was modifying your apk adding a pvr client for Spanish IPTV provider movistar, so the one I had installed was re-signed by me. I will use the same signature for the one I have compiled. 
Thanks for you help!
