### ISSUE TITLE
Menu Text distorting and or disappearing

### ISSUE THREAD

**Issue by AFFLUENTSOCIETY** [koying/SPMC#363]
Hello I'm having a issuse where the text disappear or  Distort up on start up or after using it after 20-30 mins, I'm using the latest SPMC, and I tried SPMC on different boxes from rockchip(which I know is not supported) to h3,amlogic,allwinner and have texted it on kitkat 4.4.2, lollipop and will be texting it on I've also cleared cache and deleted data and still have similar issues I will be trying SPMC on the  s905x this weekend I was wondering if you might be able to help sir. 
![image](https://cloud.githubusercontent.com/assets/12003731/16591148/2f7d0fec-42a0-11e6-8d3a-ebf2856c74f1.jpeg)
![image](https://cloud.githubusercontent.com/assets/12003731/16591150/2f9bfa4c-42a0-11e6-8087-60c62a5ec235.jpeg)
![image](https://cloud.githubusercontent.com/assets/12003731/16591153/2f9dca5c-42a0-11e6-99b5-4be5189111ae.jpeg)
![image](https://cloud.githubusercontent.com/assets/12003731/16591152/2f9cc3b4-42a0-11e6-9456-0698e3401eaf.jpeg)
![image](https://cloud.githubusercontent.com/assets/12003731/16591149/2f9bd6e8-42a0-11e6-8cbf-ea3b4a4f8a8e.jpeg)
![image](https://cloud.githubusercontent.com/assets/12003731/16591151/2f9c5cee-42a0-11e6-924f-bdffa2c0f94f.jpeg)

**Comment by guidosarducci** [comment]
You might be encountering the same issue I reported and then fixed, which was introduced in SPMC 16.3.  I think this is a widespread problem but isn't being traced back to SPMC.  You're the first other person I've seen reporting this.  Hopefully we don't wait too long for the next release...

Details here: https://github.com/koying/SPMC/issues/327. Fix here: https://github.com/koying/SPMC/pull/328.

**Comment by koying** [comment]
Yeah. I hope to release 16.4 this WE

**Comment by AFFLUENTSOCIETY** [comment]
Thank you guys so much, koying off topic question,but where might I be able to donate to you?

**Comment by koying** [comment]
> where might I be able to donate to you?

http://spmc.semperpax.com/ ;)

**Comment by TweekDash** [comment]
I am having this same issue on my Amazon firetv 1 boxes running spmc 16.3 with aeon nox skin. 

I see that a new version came out on the 14th, I'll update asap
