### ISSUE TITLE
Titan Skin

### ISSUE THREAD

**Issue by racas78** [koying/SPMC#366]
Hi, 

I use Titan Skin, Netflix style, but with new Shield firmware 3.2 I can't see anymore movie thumbnails (see picture attached). Can you help me to fix?
![img_3170](https://cloud.githubusercontent.com/assets/18232184/16709232/fac3ffc2-460a-11e6-8d3f-c63675cd97d4.JPG)

**Comment by heymoe** [comment]
Based on the time you posted this and the messages posted in the Titan Skin thread on the Kodi.tv Forum (http://forum.kodi.tv/showthread.php?tid=247525), the missing images was a bug in a version of the skin that was available around the time you posted this. It sounds like a newer version of the skin (v3.6.71+) should have this fixed.
