### ISSUE TITLE
Question about live TV image quality

### ISSUE THREAD

**Issue by mlduncombe** [koying/SPMC#372]
Not sure what to call this. Could someone tell me what the phenomenon in the picture is so I can investigate further.

Kodi/SPMC work great on my FireTV apart from a minor niggle with live TV. When working as a client for a backend PVR most of my SD DVB channels look perfect apart from BBC1 and BBC2, where any fast movement becomes painful to watch, see in the attached image the horizontal lines. Happens with various PVR backends, networks, TV's. Other channels from the same tuners dont seem to have this problem or at least not noticeably.

Can anybody tell me what causes this?

![capture](https://cloud.githubusercontent.com/assets/10163859/16872846/8327bcb6-4a87-11e6-919e-4e24420bdedb.JPG)

Is this something I can fix? Not sure where to start until I know what to call it.

**Comment by MrMC** [comment]
Those are known as interlacing artifacts. You see part of one field and part of another. In this day and ago, interlaced video should just die in a fire.

Enabled deinterlacing or if running MediaCodec (Surface), turn it off.

**Comment by mlduncombe** [comment]
many thanks
