### ISSUE TITLE
spmc 16.4.0 long pause return to spmc home

### ISSUE THREAD

**Issue by sebi0606** [koying/SPMC#377]
After a long pause on spmc 16.4.0 spmc return to home on nvidia shield tv firmware 3.2

**Comment by heymoe** [comment]
Need more info. I'm running SPMC v16.4 on a v3.2 Shield TV and I can jump out of SPMC back to the Android TV Home Screen (leanback) pretty quickly by hitting the home button on my remote.

If you're actually exiting / shutting down SPMC and it's taking a while for it to return to the Home Screen then you likely have an addon / plugin installed that is taking a while to shutdown which is preventing SPMC from closing quickly. Check your spmc.log file and see if you can identity the addon that is having problems or do a trial and error by disabling addons until SPMC exits faster.

**Comment by sebi0606** [comment]
With spmc 16.4.1 resolve
Thx
