### ISSUE TITLE
23.976 fps movie lipsync problem

### ISSUE THREAD

**Issue by kau155** [koying/SPMC#391]
When use the  "adjust display refresh rate = always" option the lipsync of 23,976 fps movie slips. 
The time of slip is 0,225 sec. When turn it off the lipsync is ok, but the movie isn't in right refresh rate.

Can you solve this issue?

**Comment by koying** [comment]
What device?
All videos? Doesn't make much sense unless the audio is not 23.976 itself...

**Comment by kau155** [comment]
HI, nvidia SHIELD ATV .... I don't know all or not, I made some sample. When off this option, the TV in 1080p60Hz mode, when ON 1080p24Hz.

**Comment by kau155** [comment]
Sorry, you are right, I tried the Nvidia without AV proc, and the lipsync was gone....so I set the delay on the AV proc, and the issue was solved. thx.
