### ISSUE TITLE
Movies and TV shows missing from Main screen

### ISSUE THREAD

**Issue by castaban** [koying/SPMC#395]
In the main screen after launch, I  see Music, I see Videos, but I do not see TV or Movies. I am using Amazon Fire TV (v1) with latest firmware.
I also have Kodi installed, if it makes any difference

Any help greatly appreciated

**Comment by heymoe** [comment]
Did you actually setup the Movie and TV library paths and scan for content? 

http://kodi.wiki/view/quick_start_guide#Adding_files

**Comment by castaban** [comment]
I did add a TV show yesterday, it did not appear. Today, I added a  different one and it worked. Maybe it did not recognize the other one as a TV show?. Working now though
