### ISSUE TITLE
FireOS Sync playback to Display (see MRMC)

### ISSUE THREAD

**Issue by ttttubby** [koying/SPMC#398]
I just saw that this feature has been added to MRMC (the paid feature stripped fork of Kodi on the Amazon App Store).  Its kind of the holy grail for Android set top boxes as it gets rid of 3/2 pull down for 24fps movies.  Since MRMC is open source, is it possible that we could see this feature added to SPMC?  It might finally allow me to abandon my old windows box (for which sync playback to display works properly).

**Comment by koying** [comment]
It's in, to be release in 16.5.0.

**Comment by ttttubby** [comment]
Sweet!  Thanks again for your hard work!

**Comment by koying** [comment]
See https://github.com/koying/SPMC/issues/435 for test
