### ISSUE TITLE
Adding Gotham Android app launching improvements

### ISSUE THREAD

**Issue by hessius** [koying/SPMC#4]
Feature request:

Even if using SPMC as a launcher isn't supported right now (damn you multichannel audio!) many people use SPMC as if it were the launcher by having autopilot (or the likes) start SPMC as soon as their Ouya starts.

XBMC Gotham contains improvements to XBMC's android app launching capabilities letting one add apps as favorites and letting add ons launch android apps by calling XBMC.StartAndroidActivity()

(as for example https://github.com/EldonMcGuinness/XBMC-Netflix-Android-Launcher and https://github.com/hessius/XBMC-Spotify-Android-Launcher)

Seeing as other improvements (hardware decoding) could be pulled into SPMC I was wondering if it was possible to add these improvements as well.

**Comment by koying** [comment]
It's not worth the work.
Better wait for Gotham, then just add  whatever didn't make it to main (like multichannel) to make it SPMC 13

**Comment by hessius** [comment]
Ok, will that happen around beta or final release?

**Comment by koying** [comment]
I'll provide beta SPMC in line with Gotham

**Comment by hessius** [comment]
Great! (you rock)
