### ISSUE TITLE
1080p@24fps

### ISSUE THREAD

**Issue by Blurayx** [koying/SPMC#40]
Hi, great work!!!
is it possible to force 24fps with spmc or create a integrated  plugin something like this for Amazon fire TV

http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/beelink-aml-devices-s82-m8-round-mxiii-etc/14968-1080p-24hz-patcher-zip?14440-1080P-24hz-patcher-ZIP=

**Comment by koying** [comment]
Trying hard. But the AFTV (non-rooted) is pretty well locked and it's too late to root mine

**Comment by Blurayx** [comment]
Same here, mines locked.
Anyway I would like to say thank you for your hard and dedicated  work.
