### ISSUE TITLE
HDR signal not recognized when using recommended 4K settings with Shield

### ISSUE THREAD

**Issue by ibizalover** [koying/SPMC#407]
Hi guys,
And thanks for your amazing job! Thanks to you, I just replace my HTPC with a WAF small box in my living room :) This is priceless hehe...

So first my set-up: Sony X85C UHD TV - Denon AVR-X1200 Receiver - Nvidia Shield

After a first night playing with all settings to get everything working, I just have one remaining issue. I'm applying your recommended video settings for SPMC, NVIDIA Shield TV and UHD (4K) TVs with 4K GUI.

Everything works properly excepting HDR. While the HDR signal IS recognized and the TV is switching to HDR mode with default settings , the HDR signal is no longer recognized when applying the 4k settings.

Is it a bug or did I miss something?

Thanks in advance.

**Comment by koying** [comment]
You need Mediacodec (Surface) _on_ for HDR
ping @classicjazz

**Comment by classicjazz** [comment]
I can update the two Shield recommended settings to note that. 

Just to confirm...
Users can either use the HQ scalers (which requires mediacodec surface=off) OR use HDR (mediacodec surface=on). This must be selected manually.

Assuming so, given how little HDR content there is, I would suggest that users only enable surface when they wish to watch HDR videos.

**Comment by classicjazz** [comment]
Also, this gets to an earlier question I raised: only 4K content is in HDR. And upscaling isn't needed for 4K. So why couldn't all 4K content using mediacodec surface=on and all <4K content use HQ upscaling (media surface=off).

**Comment by koying** [comment]
> Users can either use the HQ scalers (which requires mediacodec surface=off) OR use HDR (mediacodec surface=on). This must be selected manually.

Yep.

> So why couldn't all 4K content using mediacodec surface=on and all <4K content use HQ upscaling (media surface=off).

Those are the default settings, actually ;)
With both mediacodecs _on_, the surface one is only used for 4K

**Comment by classicjazz** [comment]
I updated both Shields to have both mediacodecs to "on".

@ibizalover please let us know if you still have issues with HDR content.

**Comment by SL600** [comment]
HDR works fine with both mediacodecs to "on". Also, 1080p files are being up-scaled using "Lanczos3 - optimized".

**Comment by challenges90** [comment]
> all <4K content use HQ upscaling (media surface=off)

@classicjazz Thank you for the very helpful settings. I have a 1080P TV and don't watch 4K content, should I set 'enable HQ scalers' low or high?

What's the difference between 'enable HQ scalers' in Videos > Acceleration and `<enablehighqualityhwscalers>true</enablehighqualityhwscalers>` in advancedsettings.xml?

**Comment by classicjazz** [comment]
@challenges90 If you are using a Shield TV and your TV is 1080p, then you should follow these recommendations:
https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC-and-NVIDIA-Shield-TV-with-1080p-GUI

The advancedsettings line is needed to turn on the spline36 and lanczos3 shaders. See http://kodi.wiki/view/advancedsettings.xml for more details.
