### ISSUE TITLE
Feature Request: Device-specific configuration presets

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#412]
SPMC/Kodi have numerous configuration options. This can be valuable for experts but daunting for novices. 

We have distilled the best configurations by device and resolution in the Wiki. But this still assumes that users read the correct recommendation, apply them precisely, and monitor the Wiki for configuration updates. 

Even with advanced and expert settings hidden by default, all the complexity and potential options inevitably require additional user support.

I suggest going a step further: by default apply a settop box or TV configuration profile for new installs on the following devices:
- **Shield TV**
  -if the Shield TV's resolution is set to 4K, apply the 4K GUI Wiki settings (rewriting guisettings.xml and advancedsettings.xml)
  -if the Shield TV's resolution is set to 1080p, apply the 1080p GUI Wiki settings
- **Amazon Fire TV**
  -if FTV1, FTV Stick, or FTV2 set to 1080p, apply the generic android TV STB Wiki settings
  -for FTV2 @ 4K, it appears we need new settings post-SPMC 16.5
- **Nexus Player**
  -apply the generic STB Wiki settings
- **Generic Android TV or Android STB**
  -apply the generic STB Wiki settings

For those users that already have userdata files/configurations, or who modify an option, they would see the following additional preset:
- **User-defined** (ultimately it might be valuable to permit users to save user defined presets but this isn't necessary initially)

As a first step in user support, users would be requested to confirm that an observed issue occurs with the default device preset applied.

Beyond user support, the other key advantage of a preset system is that users that stick to the default presets could receive preset updates either with new SPMC releases or, longer term, via an independent preset server (similar to Handbrake).

**Comment by SL600** [comment]
That's a GREAT idea!
