### ISSUE TITLE
16.4.2 Playback errors

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#419]
Just installed 16.4.2 on Shield 3.2

Some videos show still frame only 
Some don't play video at all.

Logs show errors like the following:
[spmc.log.zip](https://github.com/koying/SPMC/files/418622/spmc.log.zip)

ERROR: CDVDVideoCodecAndroidMediaCodec::GetOutputPicture ExceptionCheck; dequeueOutputBuffer
ERROR: CDVDVideoCodecAndroidMediaCodec::Decode ExceptionCheck

Same videos play fine on other Shields running v16.4.1.

**Comment by jasonzech** [comment]
I have a similar issue. Video plays fine until I pause the video. Once I unpause it. 60% of the time the video will be stuck on one frame and audio plays fine. I have to skip ten seconds ahead for the video to become unstuck.
