### ISSUE TITLE
No extra deinterlacer options - SPMC Launcher(16.4.2)

### ISSUE THREAD

**Issue by gazzer82** [koying/SPMC#420]
I am running SPMC launcher 16.4.2, which contains SPMC build 16.4-2, and everything is working great, except that i don't have the yadif (2x) deinterlace mode option.

When i go to the video setting menu whilst playing a video clip i only get the standard bob and bob-inverted.

I also don't seem to have the option to set different deinterlacing options for sd/hd?

I do have an advancedsettings.xml file in my files/userdata folder.

Any ideas?

Thanks

Gareth

**Comment by CrisCinefilius** [comment]
Zu cheissa gehen, cabron

**Comment by classicjazz** [comment]
Yadif (ffmpeg) is a software-based deinterlacer. 

Bob and bob-inverted are the only options when hardware decoding is enabled. 

Hardware decoding is essential for HD videos.

See the Wiki for how to configure Yadif 2x for SD videos. In my experience, even the Shield isn't able to use Yadif 2x on HD videos without dropping a significant number of frames.

**Comment by gazzer82** [comment]
Ah i see, worked it out now. The option for Yadiff only appears when you are actually watching a SD video, that wasn't clear to me from the wiki, i was looking for an option for SD deinterlacing and HD deinterlacing in the same window. Doh, all set now!
