### ISSUE TITLE
Passthrough, sound starts then stops

### ISSUE THREAD

**Issue by Mav1874** [koying/SPMC#427]
With both RAW and IEC when playing any file the sound starts then stops. DD or DTS both the same. Going to OSD audio options changing passthrough off then on again seems to fix and sound is passed correctly. My Settings after pretty much a mirror of this 

https://github.com/koying/SPMC/wiki/Recommended-passthrough-audio-settings-for-SPMC,-NVIDIA-Shield-TV-and-AV-Receivers

**Comment by classicjazz** [comment]
Please provide details on your receiver model and STB. Also, please provide a log file.

**Comment by Mav1874** [comment]
Cleared my settings started again and rebooted shield. Seems to have sorted it
