### ISSUE TITLE
Control volume over HDMI-CEC

### ISSUE THREAD

**Issue by LarsNorgaard** [koying/SPMC#429]
I don't know if it is possible or already there, but is there any way to allow SPMC to control the TV/Receiver volume instead of the Android volume over CEC?

**Comment by koying** [comment]
No. CEC goes from your TV remote to apps/devices, not the other way around.

**Comment by LarsNorgaard** [comment]
Ah yeah. I just searched a bit more and how the apple tv does it is via the IR blaster in the remote. Well thanks for your reply anyway :)
