### ISSUE TITLE
Sound gone in 16.4.2 (2016/08/15 release

### ISSUE THREAD

**Issue by Globbered** [koying/SPMC#432]
Hi there

using a Denon surround reciever and used android raw passthrough. After this update sound passed through via this doesn´t work anymore. Recognized as pcm zero etc...
Changing it til andriod iec passthrough sound is back but rather limited sadly if you have dts ma....dts hd....atmos etc

**Comment by ziggy73701** [comment]
Is this all your sound??? I have a issue with MP3 not playing, was fine till the weekend. Installed a Marantz receiver, all other sound is good.. but MP3 just.. fails.
Am set to Android RAW passthrough.

**Comment by Globbered** [comment]
Only working with x264 and x265 mkv files and they´re dead silent now after the update.

**Comment by ziggy73701** [comment]
Quick update.... some how the volume had changed on the Shield... no idea what occurred but it had become locked at 98%!!!

I ended up resetting the shield and all back to working order! I blame the kids
