### ISSUE TITLE
16.4.2

### ISSUE THREAD

**Issue by jasonzech** [koying/SPMC#433]
Shows disappear after marking as watched. In exodus, or specto. I've restarted spmc and they are still gone.

**Comment by jasonzech** [comment]
Tried changing title to show issue. But EDIT button does nothing ...

**Comment by jasonzech** [comment]
all addons are displaying the same missing episode. Inside KODI they show up lol

**Comment by michaelamsterdam** [comment]
nothing to do with spmc select left. menu and untick hide watch shows /episodes

**Comment by michaelamsterdam** [comment]
its a feature not a bug

**Comment by jasonzech** [comment]
Wow. Sorry.  I just of missed that option. It only started after I updated
to 16.4.2   so I did think of checking.  Thanks :)

**Comment by jasonzech** [comment]
Must of missed\*
