### ISSUE TITLE
Android TV recommendations poster art is low rez, zoomed and cropped

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#434]
On my Shield Android TV, the recommended content included movies and TV show poster art. These are very low resolution including suffering from the "jaggies". By comparison, other recommendations such as TED and Live Channels is higher resolution (no jaggies).

There also appears to be a zoom function applied, which results in titles within the poster art being cropped, particularly at the top and bottom. 

I am running at 4K resolution in Shield TV though I believe Android TV's GUI is only 1080px.

**Comment by koying** [comment]
How do they compare vs. the ones inside SPMC?
they are the same...

**Comment by classicjazz** [comment]
> How do they compare vs. the ones inside SPMC?

I am running the GUI in 4K. 

Poster art source images are 3000x2000px. 

Initial (thumbnail) cache should be 2160px with the advancedsettings.xml mod but there appears to be a bug because actual cached size is 720x1080px. Cached images are resized with  lanczos.

`<fanartres>2160</fanartres>
   <imageres>2160</imageres>
   <imagescalingalgorithm>lanczos</imagescalingalgorithm>`

Even though poster art is smaller than desired, it still looks very good with the FTV skin in SPMC.

> they are the same...

I assume you are saying that they are pulled from the same thumbnail cache. They are obviously downscaled and cropped when rendered by Leanback Launcher. What scaling algorithm are you using to do this?

**Comment by koying** [comment]
Plain Android standard resize. I have not paid attention on how it's actually done behind the scenes...
Mind posting some screenshots to make the issue more obvious?

**Comment by classicjazz** [comment]
It's harder to see from these images but SPMC thumbs are low resolution. You can see how blocky the text is and how it is off screen. And one thumb didn't render properly at all. Compare the image quality from the TED broadcast screen grabs.

![img_5689](https://cloud.githubusercontent.com/assets/7338491/18227088/60e07030-71e7-11e6-83e0-0f1814d3dd8d.jpg)
![img_5690](https://cloud.githubusercontent.com/assets/7338491/18227087/60dee5da-71e7-11e6-863a-010a9f99b5bb.jpg)
![img_5691](https://cloud.githubusercontent.com/assets/7338491/18227089/60e15a4a-71e7-11e6-8e68-82b3574d17d7.jpg)

**Comment by classicjazz** [comment]
Appears to be fixed in 16.5RC
