### ISSUE TITLE
Amazon FireTv manual 24p recognition

### ISSUE THREAD

**Issue by lecter84** [koying/SPMC#441]
Hello,

SPMC is able to recognize FireTV refresh rate settings 60Hz and 50hz -> Big advatage over kodi 
(at least for me, because I am so able to watch a certain TV show in 25fps almost judderfree with motion enhancement enabled on my projector)

However, it is possible with the FireTV to cycle through resolutions/refresh rates with button combination "rewind + up" with the FireTV remote. This changes the refresh rate system wide. Also 24p is possible here (which is actually 23.976Hz, as reported in FireTv settings after applying this mode).

Unfortunately, when I do this for 24p on my FireTV firstGen, SPMC still recognizes 60Hz.
Is there anything that can be done about this? Would be great if this would work

I would really like to contribute to this, but I am rather unexperienced with kodi programming.
Thanks so far for all your efforts with SPMC.

**Comment by koying** [comment]
Using https://github.com/koying/SPMC/issues/435 ?
If so, please upload and provide a debug log id.

**Comment by lecter84** [comment]
I will check the version on my aftv. I used the version from google playstore and sideloaded onto aftv with my smartphone. 
OK I have the version 16.4.2 installed. I will check this in few hours. Thanks so far.

**Comment by lecter84** [comment]
I tried the most recent version of spmc and it seems to work. I am testing now some 23.976 hz videos. Thanks!

**Comment by lecter84** [comment]
Hello,
Meanwhile, I found out by reading some of the open issues that automatic framerate switching is actually possible on firetv with spmc. 
And in my case the firetv box itself does the switching obviously correct. However the only thing that works without micro stutter are films that are exactly 24p which is rarely the case. 23.976p files are stuttering even though or just because spmc switches to 24hz refresh rate when playback starts. Is there something that cam be done about this? And, according to your experience, does this whole refresh rate thing work better with nvidia shield tv?
Best regards

**Comment by lecter84** [comment]
Ok  ... how do I upload a debug log id ... ?
