### ISSUE TITLE
x86 Launcher APK

### ISSUE THREAD

**Issue by coldi2k3** [koying/SPMC#445]
Is it possible to get a x86 Launcher APK?
Would be great for Intel x86 Android STB and Tablets

**Comment by koying** [comment]
https://github.com/koying/SPMC/releases/download/16.4.2-spmc/SPMC-x86_16.4.2_launcher.apk
Totally, never, tested ;)

**Comment by coldi2k3** [comment]
looooove you for that upload :)
BIG BIG THX

**Comment by coldi2k3** [comment]
works great, would be nice if we would see a regular release :)
