### ISSUE TITLE
SPMC 16.4.2

### ISSUE THREAD

**Issue by gwies71** [koying/SPMC#446]
Just installed on Nvidia Sheild for the audio passthru functions and must say it works great. However I do not see the i button or any method to manage incorrect dvd art/movie info. Can someone point to what menu I may need to change or do I need to add something.  I am new to Kodi/SPMC so I have limited knowledge.

Glen

**Comment by redsmity81** [comment]
Hold down your select button on the movie art you wanna change should bring up a context menu where you can manage the item

**Comment by gwies71** [comment]
Thank you! That did the trick.

**Comment by gwies71** [comment]
Thank you! That did the trick.

**Comment by gwies71** [comment]
Thank you! That did the trick.

**Comment by gwies71** [comment]
Thank you! That did the trick.
