### ISSUE TITLE
Binary addons don't work with SPMC compiled for aarch64

### ISSUE THREAD

**Issue by Uukrull** [koying/SPMC#452]
As title says. The only addon that seems to work is visualization.spectrum (pvr and audio decoders don't). For example with pvr.demo:

> 16:09:15 T:138723451968   DEBUG: RegisterClient - registering add-on 'PVR Demo Client'
> 16:09:15 T:138723451968   DEBUG: PVR - Create - creating PVR add-on instance 'PVR Demo Client'
> 16:09:15 T:138723451968   DEBUG: ADDON: Dll Initializing - PVR Demo Client
> 16:09:15 T:138723451968   DEBUG: SECTION:LoadDLL(/data/app/com.semperpax.spmc-1/lib/arm64/libpvr.demo.so)
> 16:09:15 T:138723451968   DEBUG: Loading: /data/app/com.semperpax.spmc-1/lib/arm64/libpvr.demo.so
> 16:09:15 T:138723451968   ERROR: ADDON: Dll PVR Demo Client - Client returned bad status (6) from Create and is not usable
> 16:09:15 T:138723451968    INFO: Called Add-on status handler for '6' of clientName:PVR Demo Client, clientID:pvr.demo (same Thread=no)
> 16:09:15 T:138723451968 WARNING: UpdateAndInitialiseClients - failed to create add-on PVR Demo Client, status = 6
> 16:09:15 T:138723451968 WARNING: UpdateAndInitialiseClients - failed to load the dll for add-on PVR Demo Client, disabling it
> 16:09:15 T:138725409856   DEBUG: Thread AddonStatus pvr.demo start, auto delete: true
> 16:09:15 T:138725409856   DEBUG: Thread AddonStatus pvr.demo 138725409856 terminating (autodelete)

and with audiodecoder.sidplay (.sid files can be downloaded from [here](http://www.skytopia.com/games/c64/c64.html))

> 16:09:28 T:138369311808   DEBUG: ADDON: Dll Initializing - Sidplay Audio Decoder
> 16:09:28 T:138369311808  NOTICE: ADDON: Loaded virtual child addon special://temp/audiodecoder.sidplay-000.so
> 16:09:28 T:138369311808   DEBUG: SECTION:LoadDLL(/data/app/com.semperpax.spmc-1/lib/arm64/libaudiodecoder.sidplay.so)
> 16:09:28 T:138369311808   DEBUG: Loading: /data/app/com.semperpax.spmc-1/lib/arm64/libaudiodecoder.sidplay.so
> 16:09:28 T:138369311808   ERROR: ADDON: Dll Sidplay Audio Decoder - Client returned bad status (6) from Create and is not usable
> 16:09:28 T:138369311808    INFO: Called Add-on status handler for '6' of clientName:Sidplay Audio Decoder, clientID:audiodecoder.sidplay (same Thread=no)
> 16:09:28 T:138705613888   DEBUG: Thread AddonStatus audiodecoder.sidplay start, auto delete: true
> 16:09:28 T:138705613888   DEBUG: Thread AddonStatus audiodecoder.sidplay 138705613888 terminating (autodelete)

Full debug log: http://paste.semperpax.com/ppvp31gf4

**Comment by koying** [comment]
Good to know, thanks (not using a single one myself ;) )

**Comment by Uukrull** [comment]
With your latest changes, addons are now working. Many thanks!

btw, not related to aarch64 but there is a problem with audiodecoder.modplug:

> 18:44:01 T:137625871424  NOTICE: ADDON: Loaded virtual child addon special://temp/audiodecoder.modplug-000.so
> 18:44:01 T:137625871424   DEBUG: SECTION:LoadDLL(/data/app/com.semperpax.spmc-1/lib/arm64/libaudiodecoder.modplug.so)
> 18:44:01 T:137625871424   DEBUG: Loading: /data/app/com.semperpax.spmc-1/lib/arm64/libaudiodecoder.modplug.so
> 18:44:01 T:137625871424   ERROR: Unable to load /data/app/com.semperpax.spmc-1/lib/arm64/libaudiodecoder.modplug.so, reason: dlopen failed: library "libmodplug.so" not found
> 18:44:01 T:137625871424    INFO: Called Add-on status handler for '4' of clientName:Modplug Audio Decoder, clientID:audiodecoder.modplug (same Thread=no)

Mods can be downloaded [here](https://modarchive.org/)
Full debug log: http://paste.semperpax.com/pscyrfqql

**Comment by koying** [comment]
Thanks. Latest build should have modplug working

**Comment by Uukrull** [comment]
Thanks!
