### ISSUE TITLE
Playback video issue h265 10 bits on S905X

### ISSUE THREAD

**Issue by professeur83** [koying/SPMC#467]
hello, sorry for my bad english

I have a problem with video playback and SPMC kodi With A mini m8s II S905X

https://www.youtube.com/watch?v=wtn8Kg-xIW0

sample video problem : http://jell.yfish.us/media/jellyfish-10-mbps-hd-hevc-10bit.mkv

**Comment by koying** [comment]
Hehe...

Je n'ai pas de S905X. Tu peux poster un debug log , stp

**Comment by professeur83** [comment]
Bonjour, corrigé avec l'update surprise OTA du firmware du 23/09/16 de la mini m8s
il y a maintenant prise en charge du amcodec :) je pense que c’était un problème de droit R-W
merci :) et bravo pour SPMC et ton développement de qualité 
MAIS SI tu as besoin de log pour s905x je suis disponible sans probleme.

**Comment by koying** [comment]
Okido.
