### ISSUE TITLE
spmc (kodi) black playback (tvheadend) 

### ISSUE THREAD

**Issue by Shadi86** [koying/SPMC#49]
Hi<br />
<br />
I have a rk3288 box from hph.<br />
<br />
I have been use spmc without a any problem especiale when it become to movie and full HD, it's playing it like a charm! <br />
<br />
So now to my problem, I have begin use TVHeadend on spmc and got many problem, when I play a channel I get black playback and got only sound,  but when I unchecked RKlibstagefright hardware accelerateed the black playback it's disappear and everything it's fine, I have also a minix neo 8h box and it's playing the channels without a problem with spmc..<br />
<br />
can anyone help or give me any recommendion? Thanks in advance<br/>

**Comment by BenEfrati** [comment]
same problem with Tronsmart R28 (RK3288), no video with acceleration (only sound), so I use transcoding in tvheadend (but it consumes CPU)
