### ISSUE TITLE
480p movies blinking when start on Shield TV on SPMC 16.4.2

### ISSUE THREAD

**Issue by lelin88** [koying/SPMC#493]
SPMC 16.4.2
All my 480p movies are blinking when start on Shield TV.
I have to stop and start again, then ok.
Other resolutions are OK
Any one else has this problem ?

**Comment by SL600** [comment]
You may wanna try:
Videos > Playback > sync playback to display = ON.
But then you can't use passthrough audio.

**Comment by lelin88** [comment]
Thanx, I'll try tonight

**Comment by lelin88** [comment]
Installed spmc 16.5.82 and problem remain the same
Any other solution ?

**Comment by lelin88** [comment]
problem solved in 16.6
