### ISSUE TITLE
HDR issue on avr

### ISSUE THREAD

**Issue by tknamco** [koying/SPMC#498]
hi ~
I have samsung ks7000 and yamaha a3060,when I plug shield tv to ks7000,HDR works,but when i plug  to a3060 HDR doesn't work,why ??

i also try philips uhd bdp7501,it works great both on plug ks7000 directly or a3060

---

thanks @dwaleke ,problem fix lol

**Comment by dwalme** [comment]
Did you change the 4k mode in the advanced settings of the 3060?   By default it is set to mode 2.  You want mode 1.
