### ISSUE TITLE
Playing some WMV files results in a crash or audio without video

### ISSUE THREAD

**Issue by guidosarducci** [koying/SPMC#501]
This is a problem seen running the latest 16.4.81 version of SPMC on Amazon Fire TV (Gen 1) with Android 5.1.1. Trying to play different WMV files sometimes works, sometimes plays audio only, or crashes SPMC.  I've tried to narrow things down, collecting sample video files and zipped logs below.

Files using the video codec 'WMV3' consistently only play audio and no video. as in this sample:
[sample-wmv9-main-MP@LL.wmv](https://samples.ffmpeg.org/V-codecs/WMV9/wmv-samples/sample-wmv9-main-MP@LL.wmv)

Files using the video codec 'WVC1', for example as in the sample below, might play the first time and then crash on a second playing immediately afterwards. 
[MainconceptLogo_VC-1_WMA_320x240.wmv](http://downloads.mainconcept.com/MainConceptLogo_VC-1_WMA_320x240.zip)

One thing I noticed is that SPMC will sometimes try to use HW-accelerated decoding of WMV, which doesn't exist on AFTV.

Various log files are here:
[wmv_crash_novideo.zip](https://github.com/koying/SPMC/files/489276/wmv_crash_novideo.zip)

**Comment by Gertbucket** [comment]
Both files crash my Fire TV 4K back to the home screen immediately.

**Comment by Gertbucket** [comment]
@guidosarducci @koying

16.5RC will play some WMV's for me now. Some still crash the program. How about you?

**Comment by Gertbucket** [comment]
@guidosarducci @koying All working now with latest RC.

**Comment by guidosarducci** [comment]
Uh, nope. With the latest release, files using the WMV3 codec (as in the OP) still result in audio playing without the video.  However, files using the WVC1 codec do now play without crashing.

This issues should not be closed, but I don't see how to reopen it.

@koying, I posted links to the sample files since I know you have a AFTV v1 and thought your seeing the problem firsthand would be best.

**Comment by Gertbucket** [comment]
@guidosarducci @koying Dude, that first WMV3 file plays video fine on the latest RC with AFTV 4K. Maybe you don't have the most recent build. Look again, he updated it.

But your file doesn't have any audio. It's silent. 

Tried it with Kodi 17, MrMC, and Windows Media Player. Same result.
