### ISSUE TITLE
MiBox Android TV issue

### ISSUE THREAD

**Issue by ingbrzy** [koying/SPMC#509]
H all.. 

As you know, there are issues with Amlogic and Android 6.0 support for HW decoding... 

> _Just one question.. It has to be fixed directly by Xiaomi or Amlogic or SPMC..? 
--- Never mind.. found an answer at kodi forum (its shitty amlogic)---_

If you want test any SPMC apk version with potential fix, I am open to it as owner of this MiBox MDZ-16-AB version... Running it via AV receiver YAMAHA on 4k Samsung TV

**Comment by fatbob01** [comment]
Or maybe the results are only yielded from local content and not addons?  For exaple, will it list results from Phoenix/Exodus?
