### ISSUE TITLE
Zappiti 4k player

### ISSUE THREAD

**Issue by Blurayx** [koying/SPMC#51]
Hi koying
Will it be possible to take advantage of the Realtek chip auto frame rate in the Zappiti 4k player. Zappiti have there own modified version of kodi for there player.

Thanks

**Comment by koying** [comment]
Probably, if they publish their source as they should.
Do you have a link to them?

**Comment by Blurayx** [comment]
I'm currently looking for it but here is some info
http://www.cnx-software.com/2014/11/29/realtek-m-195-review/

http://forum.kodi.tv/showthread.php?tid=204918

**Comment by Blurayx** [comment]
Hi koying,
I think this maybe the source code someone posted it,
It's towards the bottom of the thread.
http://forum.kodi.tv/showthread.php?tid=204918&page=2

Realtek website
http://www.realtek.com.tw
