### ISSUE TITLE
FireTV : Dolby TrueHD (Atmos) & DTS-HD MA - do these audio stream passthrough properly?

### ISSUE THREAD

**Issue by Ltek** [koying/SPMC#518]
Using latest SPMC w/ FTV2

I cant get Dolby TrueHD to pass through. I have an Atmos encoded video but it seems to get converted to PCM.

I currently have tried both RAW & IEC settings. 

Is TrueHD able to pass through properly? If yes, what settings? 

thanks!

**Comment by MrMC** [comment]
FTV2 does not support 192000 which is required for Dolby TrueHD passthrough

**Comment by Ltek** [comment]
thanks, looks like I'll be moving Kodi to Windows PC -- darn.

**Comment by MrMC** [comment]
hint, nvidia shield

**Comment by Ltek** [comment]
I already have a Windows PC running 24x7 and I consolidate as much as reasonable… there’s no benefit to spending money on Shield just for Kodi. I was using Amazon FireTV (Prime subscription) so running Kodi run on it was ideal. Maybe I can consolidate when FTV3 launches.

Thanks guys, which I could still use SPMC/Android… just not in the cards until (if ever) FTV supports Atmos & DTS-X
