### ISSUE TITLE
SMB not working on 14.2 version.

### ISSUE THREAD

**Issue by parapenT1sta** [koying/SPMC#53]
I never had issues with SPMC using SMB, I have videos shared on my desktop and I watched them on my android box, but with the latest update, keep asking me for the password, I put it but still asking for it.

Was working fine with 14.1 version.

**Comment by hessius** [comment]
Working fine for me. You could always try hardcoding your password by entering the smb address manually

**Comment by parapenT1sta** [comment]
I just upgraded from 14.1 to 14.2 and after the password is asked always and when I inserted it seems to not be valid. I used special characters on it.

**Comment by nikkpap** [comment]
Don't bother anymore with,android and xbmc give a try with the minimalistic movian.tv yts ororo.tv and tvheaded and other plugins... Its very promising...

**Comment by koying** [comment]
@nikkpap This is obviously not the place for advertising

**Comment by nikkpap** [comment]
I am not I don't care, I I don't have the benefit from this, I was I fan of xbmc but ots time it's over you are sir a good developer so follow your instinct...sorry and delete all. The above

**Comment by parapenT1sta** [comment]
I really like SPMC because of my S89-H android box but with this new update I am getting trouble with SMB.

I just wonder if the issue is because is using Samba 3.6 on this version

I am using number, letters and !! in my password, that could be the issue?

**Comment by parapenT1sta** [comment]
Just an update, I downgrade to 14.1 and is working fine.

Because I have windows 8, my username is my email example.email@outlook.com
password: 00example00!!

**Comment by maxmcn** [comment]
Same Issue here. Windows 8.1, Username is email and password has special character. 
Tested:
SPMC 14.2: Fail
SPMC 14.1: Works
Kodi 14.2: Works

**Comment by nunofgs** [comment]
I'm also experiencing this issue.

**Comment by nunofgs** [comment]
Here's the log output when I try to add a network location:

```
21:23:37 T:1551944928   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://raspberrypi.local/public'
                                            unix_err:'6e' error : 'Connection timed out'
21:23:40 T:1551944928   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting smb://raspberrypi.local/public
21:23:48 T:1698580800  NOTICE: Thread JobWorker start, auto delete: true
21:23:49 T:1698580800   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://'
                                            unix_err:'2' error : 'No such file or directory'
21:23:50 T:1551944928   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting smb://
21:23:50 T:1551944928   ERROR: CGUIDialogFileBrowser::GetDirectory(smb://) failed
```

As you can see, I tried adding `smb://raspberrypi.local/public` but also clicked the generic "Windows share" on the shares menu (which attempted to access `smb://`). I also tried the samba server's IP directly with no success.

Needless to say, Mac OS X is able to access this share without any problems as well as an ubuntu machine using smbclient.

One thing that is interesting is that it immediately gives the `Connection timed out` error. It's like it isn't even trying to connect...

**Comment by OulmesCode** [comment]
sane here,  kodi 14.2 works fine but SPMC 14.2 fails to connect to my smb
