### ISSUE TITLE
HDR with 16.5

### ISSUE THREAD

**Issue by 3djc** [koying/SPMC#545]
My setup is the following:

Shield - Denon AVR - LG Oled 4k tv. I have setup the Shield according to the post I was able to find on the subject, that is Mediacodec (Surface) = on and Mediacodec = on

I have several HDR movies, all of them do trigger the TV to switch to HDR mode when played with VLC on the Shield, but none when played with SPMC (any version) on the very same Shield

**Comment by war59312** [comment]
Should probably post a sample and log file of playing video.

**Comment by 3djc** [comment]
Will try to do that, as soon I can cut a part of 50gb file :)

**Comment by 3djc** [comment]
The same problem occurs with these two public files:

http://hdrsamples.com/life-of-pi-4k-uhd-hdr-sample-footage/
http://demo-uhd3d.com/fiche.php?cat=uhd&id=144

log : http://pastebin.com/LJ5CK7Vg

Both work with VLC on Shield

**Comment by bluecalx4** [comment]
I can confirm that HDR videos no longer play in HDR in 16.5. They worked fine on 16.4.2

**Comment by 3djc** [comment]
Fixed in 16.5.5
