### ISSUE TITLE
WIP Wiki Document for FTV1 and 2

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#550]
I have 2 placeholder Wiki documents for FTV 1 and 2, for video and audio based on other Android STB settings. They are _not_ currently correct. Since I don't own either an FTV Stick, FTV1, or FTV2 STB, I would appreciate @koying and the community's feedback regarding optimal settings and limitations.

For example, in audio, a quick matrix for each of Fire TV 1 and 2 and Fire TV Stick, are the following audio codecs supported via passthrough or PCM software decoding:
* Dolby Digital (AC3) 
* Dolby Digital Plus (E-AC)
* DTS (lossy)
* TrueHD 
* DTS-HD 
* Atmos (and if so at what frequency/channels)
* DTS-X
 
https://github.com/koying/SPMC/wiki/Recommended-passthrough-audio-settings-for-SPMC%2C-Fire-TV-and-AV-Receivers/_edit

For video, a quick matrix of FTV 1, 2, and Stick: are the following codecs supported without issue and at what resolutions:
* VC1
* MPEG2
* H264
* H265

I assume all video resolutions up to 1080 are supported on all FTV and 2160 for FTV2. I assume all FTV models are limited to a 1080 GUI. Also, is display refresh rate supported in all models if video is set to auto?

https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC-and-Fire-TV-1-and-2-and-Fire-TV-Stick

Thanks for your help!

**Comment by Tumbleweeds** [comment]
codec \ device | AFTV2 | AFTV1 | FireStick1
-------------- | ----- | ----- | ----------
DD (AC3) | P | P | 1
DD-EX |  P  |  1  |  1
DD+ (E-AC) |  1  |  1  |  1
TrueHD |  N  |  N  |  N
Atmos |  N  |  N  |  N
DTS |  P  |  P  |  P
DTS 96/24 |  P  |  P  |  P
DTS-ES Discrete |  P  |  P  |  P
DTS-ES Matrix |  P  |  P  |  P
DTS-HD |  N  |  N  |  N
DTS:X |  2  |  2  |  2

P. Passthrough
N. Passthrough not available, PCM software decoded
1. Passthrough did not work, no audio. Need debug
2. My AVR does not support DTS:X

Although there is no option for DTS-HD passthrough, it follows the DTS flag and passes through as DTS 5.1. So to use the proper 7.1 decoding, disable DTS passthrough and enable Support 8 channel DTS-HD audio decoding instead.

Atmos is decoded as 7.1 PCM.

DD-EX uses the DD passthrough flag. DTS 96/24 and both DTS-ES use the DTS passthrough flag.

I'll try to get some more testing done in the upcoming days.

Testing was done with SPMC 16.5.1 and FireOS 5.2.1.1 (551203220) (Android 5.1.1 API 22) on all devices. The underlying linux kernel is as follows:
AFTV2: 3.10.61+
AFTV1: 3.4.0-perf-gd7006e5
FireStick1: 3.0.31+

**Comment by rbronco21** [comment]
Thanks for your work guys. Can we get the wiki updated? I've been messing with these settings and am having issues with mpeg2 artifacts with acceleration enabled and hadn't seen the comments that the settings here were placeholders.

**Comment by classicjazz** [comment]
Thanks for the feedback. I have updated the work in progress documents. 

@Khaemwese & @koying & @davilla 
I believe the current FireTV is Android API 22 and SPMC needs to stick with RAW, not IEC audio passthrough. It looks like @davilla has done some more advanced work with MRMC that selectively uses IEC and RAW but I believe he is using the Krypton Videoplayer. Also, there are reportedly issues with certain receivers and RAW.

I have also cross referenced this:
http://forum.kodi.tv/showthread.php?tid=289735

And there is also this thread:
https://github.com/koying/SPMC/issues/247

An updated audio passthrough guide is here:
https://github.com/koying/SPMC/wiki/Recommended-passthrough-audio-settings-for-SPMC,-Fire-TV-and-AV-Receivers

It seems like audio passthrough on FTV is limited until they upgrade to API v24.

It looks like only H264 and H265 (FTV only) are natively supported video codecs. FFMPEG might be able to decode SD MPEG2 (DVDs) or VC1. But I would be surprised to see the FTV decode MPEG2 or VC1 HD videos.

I assume that wide color gamut isn't applicable to the FTV.

I believe that the FTV2 can do 4K TV and perhaps 4K GUI but recommend keeping GUI at 1080.

Please confirm my understandings above and I will link these pages on the FAQ page afterwards.

**Comment by MrMC** [comment]
current FireOS 5 is Android API 22 but it has support for some API 23 API calls. Specifically display and rez switching. FireOS 5 'could' do 192kHz for audio but for some reason, they have disabled it.

**Comment by classicjazz** [comment]
Thanks. Do you recommend anything different than what's in the two Wiki pages?

**Comment by classicjazz** [comment]
I linked the pages on the main FAQ page. If there are any necessary changes, please create a new issue.
