### ISSUE TITLE
No dts passthrough from Shield

### ISSUE THREAD

**Issue by MikeyMcG** [koying/SPMC#564]
After reading comments others have made about DD and DTS HD audio and IEC passthrough, I have revisited my original problem and have used IEC passthrough instead of RAW passthrough. I can now get DTS and DD 5.1 audio from standard audio and downmixed from HD, but no HD audio from either format.

Passthrough settings set to on in Shield settings. 

SPMC audio settings set to:
Android, IEC Passthrough
Number of channels = 5.1
Enable passthrough = On
Passthrough Output Device = Android, IEC passthrough
AC3 capable = On
E-AC3 = On
DTS capable = On
True-HD = On
DTS-HD = On 

Streaming to an Onkyo TX-NR626 receiver. Any help?

**Comment by Nehemoth** [comment]
I believe that you must also modify the settings for audio in the shield, if I remember correctly you should change the audio format from Stereo Enhanced(?) to Surround 5.1

Please check the settings, if not let me know and I can check as soon as I arrive home

**Comment by MikeyMcG** [comment]
Sorry  Nehemoth, this post was lost in the sands of time. Yeah, I had all the settings enabled as you say but I was still having the issue. But everything seems to have been ironed out with the new system firmware released a couple of weeks ago. Thanks for taking the time to respond.
