### ISSUE TITLE
Confused about recommended video settings for SHIELD and 4K

### ISSUE THREAD

**Issue by rfgamaral** [koying/SPMC#567]
The [recommended video settings](https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC%2C-NVIDIA-Shield-TV-and-UHD-%284K%29-TVs-with-4K-GUI) state:

> allow hardware acceleration - Mediacodec (Surface) = off
> allow hardware acceleration - Mediacodec = on 

But on issue #407 we have this:

> >Users can either use the HQ scalers (which requires mediacodec surface=off) OR use HDR (mediacodec surface=on). This must be selected manually.

> Yep.

>> So why couldn't all 4K content using mediacodec surface=on and all <4K content use HQ upscaling (media surface=off).

> Those are the default settings, actually ;)
> With both mediacodecs on, the surface one is only used for 4K

The way I interpret the above, the first "yep" contradicts the "those are the default settings".

I mean, the last comment clearly states that mediacodec surface is only used for 4K. So we can leave this setting turned on and still use HQ scalers on 1080p content and below, correct? If so, why is the mediacode surface recommended to be off?

**Comment by classicjazz** [comment]
As noted at the bottom of the Overview, there was a change with v 16.5 that reverted the behavior of enabling surface rendering. You are correct about the behavior of enabling Surface in 16.4.x. Now, however, you must choose either surface rendering or HQ upscaling. 

For now, the Wiki recommends disabling surface rendering in order to use the upscalers. However there does appear to be an issue with playback, wherein surface rendering is smoother. @koying is aware of this but has been focused on fixing crashers for 16.5.1.

**Comment by rfgamaral** [comment]
Sorry, I'm still a bit confused...

I have 16.5.1 installed and for the sake of clarifying things let's assume for now that that issue with playback does not exist (I'm assuming here it will be fixed on some future version).

With this version I need to set mediacodec surface rendering = OFF if I want to be able to watch HDR content but I need to set mediacodec surface rendering = ON if I want to take advantage of HQ upscaling on content below 4K. Right now I can't have both at the same time. Is this correct?

**Comment by classicjazz** [comment]
With 16.5.1...

You need to have **surface ON to view HDR content**. You also need HDR content, v3.3 of the Shield software, the right type of HDMI cables plugged into the correct port of an HDR enabled TV that is firmware compatible with the flavor of HDR you are using (HDR10 v DV), and nothing in between the Shield and TV that  _modifies_ the HDMI signal (e.g. an upscaling AVR).

You need to have **surface OFF to use the HQ upscalers**. 

You are correct... right now you can't have both.

**Comment by 3djc** [comment]
I have surface on with 16.5.1, and still no HDR when the same file played with VLC on the same shield triggers HDR switch on the TV (https://github.com/koying/SPMC/issues/545)

**Comment by rfgamaral** [comment]
@classicjazz Thank you for the clarification.
