### ISSUE TITLE
SPMC 14.2 problem with 720 resolution 

### ISSUE THREAD

**Issue by alexagr** [koying/SPMC#57]
SPMC 14.2 on Beelink MX-III 2/8Gb (109k4 ROM).
I'm using 5 year old Panasonic plasma TV - hence 720 resolution in Android settings.
SPMC correctly recognizes 1280x720 resolution (Settings > Summary Information). However when playing movies, only part of the frame is displayed (as if the full frame is 1920x1080 but only 1280x720 part of it is shown).
Kodi 14.2 on the contrary, shows (incorrectly) 1920x1080 resolution in Summary Information, but movies are played just fine.

**Comment by ilGimmy** [comment]
Device: MXQ 109k4
TV: Panasonic TX-P42G20
A/V settings: 720p50 (I have issue with 1080p50 on my MXQ; probably faulty hardware).
SPMC version: 14.2 and 15beta1
Problem: UI is correctly displayed; any x264 and x265 video is displayed 1080p, so I can see only top-left part of image.
Kodi 14.2 works fine, but doesn't offer H/W decoding of x265.
