### ISSUE TITLE
SPMC 16.5.1  - Black screen at launch

### ISSUE THREAD

**Issue by jupiler5** [koying/SPMC#570]
Device: Samsung Galaxy Tab S2
Android version: 6.0.1

Hi Koying,

I've just made a clean install of SPMC 16.5.1. When I launch the app, I have immediately a black screen (no SPMC logo, nothing). I ear the selection sounds when I push "back" button of my tablet ( the app minimizes as it has to do when I push 2 times on the back button) but I can't see anything.

I tried with and without network (plane mode).

I did't have the problem with previous versions.

If you have any idea...

**Comment by rainman74** [comment]
@koying Yes, black screen at launch with ArmV7-build and crash with Arm64-build.

Here are the logs of the 64bit build (armV7 doesn't write a log - just BLACK SCREEN):
https://1drv.ms/u/s!Au4QgT0yuh6DjQkZSu8g3u2kOMcM

**Comment by clown522** [comment]
I have the same problem with Sony Android TV XD94. Black Screen, but i can here GUI Tones

**Comment by cobrajoe94** [comment]
Device: Fire HD 10 Tablet
Android Version: 5.1.1   API Level: 22
16.5.1 gives me black screen as others have reported.
16.4.2 worked great.

I first tried installing 16.5.1 over / as an upgrade to 16.4.2 and got black screen. So I thought that could be the issue, so I uninstalled it, rebooted and did a clean install of 16.5.1 and got the black screen again. 

Uninstalled 16.5.1 and reinstalled 16.4.2 and all is well again.

Any thoughts?

**Comment by koying** [comment]
Please try http://download.semperpax.com/spmc/android-arm/SPMC-20161208-c30bf15-rmdroidloader-armeabi-v7a.apk

**Comment by jupiler5** [comment]
That works !

Thank you koying, you're the best !

And thank you again for this great app ! :-)

**Comment by jim16127** [comment]
@koying
http://download.semperpax.com/spmc/android-arm/SPMC-20161208-c30bf15-rmdroidloader-armeabi-v7a.apk

Is this a newly compiled version? Is this only available via this link in this open issue? Will you be recompiling a newer version because of this issue? Basically...I'm ready to update...but would rather wait if your going to compile and drop another update in the next week. Thanks for the awesome work and quick responses to the issue!

**Comment by rainman74** [comment]
this is a newly version. You find every nightly build here:
http://download.semperpax.com/spmc/android-arm/?C=M;O=D

koying generally compiles a newer version every 3-7 days, if there are heavy bugs ;-)

**Comment by jim16127** [comment]
Couldn't figure out how to edit my comment above?
I notice that this "revised" version that fixes the black screen issue is 10MB smaller than your normal release. Seems to be the same size (roughly) as your "debug" uploads. Just wondering what is missing?

**Comment by koying** [comment]
The binary addons (PVR), I guess. It's a test build, really.
If this confirms the fix, I'll release a new build this WE

**Comment by cobrajoe94** [comment]
Update for Koying,

Device: Fire HD 10 Tablet
Android Version: 5.1.1 API Level: 22

Tested with SPMC-20161209-2e8bbf4-spmc-jarvis-armeabi-v7a.apk  and the black screen issue is resolved. Thank you.

P.S. I tested with SPMC-20161209-2e8bbf4-spmc-jarvis-armeabi-v7a.apk  as I looked in builds, installed and tested it before I read the follow up posts. Sorry.

Please let me know if you still need me to test with SPMC-20161208-c30bf15-rmdroidloader-armeabi-v7a.apk or is testing with the other newer build fine by you.

Thank you!

**Comment by Webwally1** [comment]
Hi, should I use v16.5.1 or the latest nightly build dated 20161209?   I'm using a firestick.  Thanks in advance! ;-)

**Comment by rainman74** [comment]
Nightly 😉

**Comment by koying** [comment]
Hold off for a while. "Official" 16.5.2 will be off in a couple of hours...

**Comment by Webwally1** [comment]
OK, thank-you both for swift replies, much appreciated.

**Comment by dchrome1** [comment]
How do we tell what's the "official" release from your directory? Thanks.

**Comment by koying** [comment]
Made a wiki page to make it clearer:
[SPMC project way of working](https://github.com/koying/SPMC/wiki/SPMC-project-way-of-working)

**Comment by koying** [comment]
Fixed in 16.5.2
