### ISSUE TITLE
SPMC 16.5.1 Quarter of screen

### ISSUE THREAD

**Issue by kid666** [koying/SPMC#572]
I've android box LP5.1 Amlogic 812, SPMC 16.4.2 works perfect, I upgrade to 16.5.1 and when start I see only quarter of screen... View picture in attach...
![screenshot_2016-12-09-16-18-04](https://cloud.githubusercontent.com/assets/23740610/21055273/142c3f76-be31-11e6-9488-00056a74defc.png)

**Comment by jeff2900** [comment]
Same issue with TV Box Android 5.1.1 and Amlogic S905.
Work fine with  TV Box Android 6.0 and Amlogic s912.

**Comment by pale155** [comment]
I have the same problem with TV Box Android 5.1.1  Amlogic S 905

Have tried changing resolution, themes, ... nothing helped

**Comment by koying** [comment]
Please test http://download.semperpax.com/spmc/android-arm/SPMC-20161208-c30bf15-rmdroidloader-armeabi-v7a.apk

**Comment by jeff2900** [comment]
@koying Thx for your reply
Testing SPMC 16.5.2 SPMC-20161209-2e8bbf4-spmc-jarvis-armeabi-v7a.apk
  ok with  Android 5.11 Amlogic s905
 ok with Android 6.0 Amlogic s912

**Comment by pale155** [comment]
koying - excelent, works like a charm.
thanks a lot

EDIT: there are no PVR clients no more.

**Comment by JustMev** [comment]
Seems to be an issue with latest spmc its showing left bottom quarter of screen 
- Beelink MiniMX amlogic s905 5.1.1  - spmc 15.5.1 issues

15.5.2 sorted ok

**Comment by pale155** [comment]
Where to download spmc 15.5.2?

**Comment by pale155** [comment]
Sorry, didn't know 
http://download.semperpax.com/spmc/android-arm/SPMC-20161208-c30bf15-rmdroidloader-armeabi-v7a.apk
Is spmc 15.5.2

**Comment by JustMev** [comment]
well its not 15,5.2  still 15.5.1 and I should of just called it 15,5,1(alt)

**Comment by koying** [comment]
Fixed in 16.5.2
