### ISSUE TITLE
SPMC 16.5.2 Win32 ?

### ISSUE THREAD

**Issue by rainman74** [koying/SPMC#582]
Hi koying, would be a win32 build of latest 16.5.2 possible?

**Comment by clown522** [comment]
Deleted, my fault.

**Comment by rainman74** [comment]
http://download.semperpax.com/spmc/win32/

**Comment by koying** [comment]
I'm building one.
Might take a while....

**Comment by koying** [comment]
Added to https://github.com/koying/SPMC/releases/tag/16.5.2-spmc
Not tested, though, although it should work.

**Comment by rainman74** [comment]
@koying Thank yo very much!
