### ISSUE TITLE
[RFC] Testers Needed for YouTube DASH and SPMC 16.5.x

### ISSUE THREAD

**Issue by guidosarducci** [koying/SPMC#588]
(With no SPMC forum I decided to post here...)

I've added DASH support for SPMC to the upstream YouTube addon, and have tested it on both SPMC 16.5 and Kodi 17b6.  But it needs additional testing before it can be pushed to the Kodi repo.  You can download it here: [plugin.video.youtube-5.3.7.zip](https://github.com/Kolifanes/plugin.video.youtube/releases/download/5.3.7/plugin.video.youtube-5.3.7.zipXXX). [<-- DONT USE THIS. SEE BELOW.]

Please add your experiences here, and if everything works feel free to also post on the [Kodi YouTube Forum.](http://forum.kodi.tv/showthread.php?tid=267160)

**Comment by koying** [comment]
Cool, thanks. Will test...

**Comment by guidosarducci** [comment]
Don't use that link above to the plugin for testing.  I just noticed that the add-on maintainer migrated the repo, and not only removed my name from the commit and replaced it with his own, but also broke things by leaving out some of my changes.  Not happy one bit...

Use this link from my original PR if you'd like to test: [plugin.video.youtube-5.3.7-spmc.zip.](https://github.com/Kolifanes/plugin.video.youtube/files/644105/plugin.video.youtube-5.3.7-spmc.zip)

**Comment by dbasabe** [comment]
Thaks for your addon.

I've ever tried to run it with MPEG-DASH enable, SPMC crashed .

Here the log. [http://paste.semperpax.com/pkbv5iyrt](url)

**Comment by guidosarducci** [comment]
Hmmm.  As far as the add-on goes, everything seems OK.  It detects SPMC 16.5 on startup and allows you to enable DASH.  Those are the only add-on changes I made, so it's unlikely to be causing the problem.  Looking at the log's end, the SPMC crash could be related to MediaCodec, so probably something @koying would need to investigate.

Thanks for trying out the add-on though.

**Comment by getochkn** [comment]
It lets me enable it, I setup your youtube plugin, setup api keys, and when i search and start a 4K movie playback, it plays in 1080p only.  Should 4K work?  I'm on a Minix U1 4K capable box with a Denon 4K receiver and 4K TV and I can watch 4K content, so I know 4K works fine.

**Comment by compyy** [comment]
Hi Guys,
I have Nvidia Shield TV and SPMC 16.5.3 and i can't enable Dash, what should i do ? i tried to reinstall it and reinstallled the plugin many times but still there is no option to enable it.

i also checked in All Addon, i dont see Inputstream there, it works fine in normal Kodi, i can enable the Dash in addon.

**Comment by getochkn** [comment]
Just installed libreelec, and the inputstream plugin, full 4K youtube on my 905 based box.

**Comment by guidosarducci** [comment]
I want to clarify a few points on this thread for those testing or reporting problems:

1. At this time I'm confident the addon version I linked in https://github.com/koying/SPMC/issues/588#issuecomment-267522164  works fine on both Kodi 17 and SPMC 16.5.  Problems like crashes or 4K support are unrelated to the YouTube addon, and more likely an issue with SPMC, the MPD source, or your device configuration.  Some of these items are discussed in detail in the Wiki.
2. Kodi 17 supports DASH via the Inputstream.adaptive plugin.  For SPMC, @koying built in DASH support without the need of an Inputstream plugin; there's nothing to configure AFAIK.
3. Most people aren't psychic mind readers.  If you want help with a problem then **at least** upload a [debug log](https://github.com/koying/SPMC/wiki/How-do-I-publish-a-debug-log%3F).

@dbasabe I didn't mention this before, but if you're still experiencing crashes you should open a separate issue to capture the details and how to reproduce.

**Comment by koying** [comment]
To add to what @guidosarducci said, the debug overlay ("o") clearly state MPD Audio / MPD Video in SPMC (MPD = Dash)

**Comment by crazy888** [comment]
I can confirm that it is working with 4k and 1080p content without any problems.

Thanks a lot for this. This is awesome :)

**Comment by guidosarducci** [comment]
FYI, the 5.3.8 release of the YouTube addon now supports SPMC DASH, and can be downloaded here:
[plugin.video.youtube-5.3.8.zip](https://github.com/jdf76/plugin.video.youtube/releases/download/5.3.8/plugin.video.youtube-5.3.8.zip)
