### ISSUE TITLE
Gotham beta build?

### ISSUE THREAD

**Issue by hessius** [koying/SPMC#6]
It was mentioned earlier on that a build of spmc based off of gotham would be made as it hit beta. Gotham hit beta a while back now, any news on the gotham spmc build?

**Comment by koying** [comment]
Might not be needed. The needed multi-channel / passthrough patches might hit XBMC self.

**Comment by hessius** [comment]
Oh cool! Do you have a trac url for it? (searching didn't return anything for me)
