### ISSUE TITLE
 SPMC-16.5.3 aarch64 launcher version

### ISSUE THREAD

**Issue by pajopasa** [koying/SPMC#604]
Hi Koying.
I wonder if it's possible for you to compile a launcher version of your version of SPMC-16.5.3 aarch64 ?
And thanks for you work.

**Comment by sammarbella** [comment]
+1

This is definitely something i would like to enjoy in my Shield TV. :)

**Comment by Robinjoeh** [comment]
Hi guys.

The aarch64 16.5.3 of the APK can be downloaded from here:
https://github.com/koying/SPMC/releases/download/16.5.3-spmc/SPMC-16.5.3-spmc-be672c0-aarch64.apk

**Comment by pajopasa** [comment]
But it is the launcher version?

Em 20/12/2016 07:51, "Robinjoeh" <notifications@github.com> escreveu:

**Comment by koying** [comment]
I've added an aarch64 launcher apk to the release items:
https://github.com/koying/SPMC/releases/tag/16.5.3-spmc

**Comment by pajopasa** [comment]
Ok. Thanks

Em 20/12/2016 13:26, "Chris Browet" <notifications@github.com> escreveu:

**Comment by sammarbella** [comment]
Thank you very much Chris. :)
