### ISSUE TITLE
SPMC 16.5.3: External Video Player does not start

### ISSUE THREAD

**Issue by clown522** [koying/SPMC#607]
At Kodi the external player starts without an issue. In SPMC 16.5.3 you choose the Sony Player but nothing happens. 

error:
 ExecuteAppAndroid: com.sony.dtv.osat.video
19:20:37.556 T:18446744072040188816   ERROR: CXBMCApp::StartActivity - ExceptionOccurred launching com.sony.dtv.osat.video
19:20:37.556 T:18446744072040188816  NOTICE: ExecuteAppAndroid: Failure

log and playercorefactory content is attached
[playercorefactory.txt](https://github.com/koying/SPMC/files/664475/playercorefactory.txt)
Thank you for your work!
[spmc log.txt](https://github.com/koying/SPMC/files/664458/spmc.log.txt)

**Comment by koying** [comment]
I'm pretty sure the sony player won't support a smb:// link from spmc

**Comment by clown522** [comment]
oh yeah i have my problem found. In Kodi i opened it with UPNP. Now it works also in SPMC. Thank you for your fast help.
