### ISSUE TITLE
What version do we use? 

### ISSUE THREAD

**Issue by JFG90** [koying/SPMC#613]
I have a nvidia shield do i run the Arcch64?

**Comment by ziggy73701** [comment]
I have been.... seems.... quicker... but.. I cant say why... just... "feels" it.

**Comment by JFG90** [comment]
Ok thanks that's the one I'm using but wanted to be sure

**Comment by chiefkes** [comment]
Is there any official word on this? Is aarch64 better than arm64 on the Shield TV?

**Comment by Wanderlustus** [comment]
I'm confused as to which I should install as well.  I have a Nexbox A95X and am currently running 16.5.3 which auto-updated via Playstore.  Any help appreciated.

**Comment by Wanderlustus** [comment]
Right.  A friend told me to garb the armeabi-v7a.apk download, so going to give that a shot.

**Comment by JFG90** [comment]
Can you let us know how it works with iptv streams if you use them?

**Comment by Wanderlustus** [comment]
Just installed it, watching a flic on USTVNOW, and it seems fine, though the OSD settings recommended don't seem to do it for the A95X.  Well, not all of them anyhoo.

**Comment by JFG90** [comment]
Ok what about movies on exodus does it play them? What device you using?

**Comment by JFG90** [comment]
As in like does it play them ok?

**Comment by Wanderlustus** [comment]
I just mentioned the device, JG.  :<>

**Comment by Wanderlustus** [comment]
But yes, I was just testing a 1080p/5.1 copy of "The Martian" and it was grand.  BTW, I only have 5Mbps DSL, so I'm a very happy man just now.

**Comment by JFG90** [comment]
Ok, i might just wait for the playstore update

**Comment by Wanderlustus** [comment]
?  Dunno why, as it's working like a charm, but ok.

Just switched over to ITV 3 through Filmon in SPMC, and the SD feed is working fine as well.

Bud of mine in Spain is running 16.5.4 on a Shield and is loving it.  It was at his behest I grab the new ver.  As I said, very happy.

**Comment by JFG90** [comment]
Ok is he running same apk version though?

**Comment by Wanderlustus** [comment]
Can't be sure but it's the one he recommended for me.  I'll fire him a note and ask.  he certainly know more than me about SPMC.

**Comment by JFG90** [comment]
If you could that be wicked, the arrch64 i have plays exodus etc perfectly but tv streams it judders I've even tried playing about with settings etc

**Comment by Wanderlustus** [comment]
Sorry I didn't get back to you last eve, JG, but in fact that is the one he's using as well:  arrch64.  Have you followed the settings config K put up?  I believe they're shield-specific, as I had to doodle about with some of the ones in OSD settings for my two A95X units.

https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC%2C-NVIDIA-Shield-TV-and-UHD-%284K%29-TVs-with-4K-GUI

**Comment by JFG90** [comment]
Does anyone know what version of SPMC the playstore uses? Is it the aarch64?
