### ISSUE TITLE
Brightness and Contrast adjustments missing since 16.5.x

### ISSUE THREAD

**Issue by Solitaire555** [koying/SPMC#616]
On SHIELD TV, since version 16.5.x, the brightness and contrast settings are no longer accessible during HD movie playback ! Why ?

**Comment by koying** [comment]
Because it switched back to Mediacodec(Surface) by default.
Disable it to get those controls back

**Comment by Solitaire555** [comment]
Sorry, I don't understand... How do I do that?
Where is this setting?
Thanks

**Comment by koying** [comment]
Settings-Videos-Acceleration

**Comment by Solitaire555** [comment]
Ok found,
Work fine, thanks
Merry Christmas !
