### ISSUE TITLE
Log file naming (smpc.log) breaks log uploaders and viewers

### ISSUE THREAD

**Issue by guidosarducci** [koying/SPMC#62]
I'm currently using SPMC v15 on AFTV. I've noticed a problem where a log uploader or viewer add-on will fail with errors. The issue is caused by most add-ons hard-coding the log file as 'kodi.log'. It appears SPMC changed it's log file name to 'spmc.log'.

There is a way to determine the log file path using the special locator 'special://logpath', but I don't find anything for the log file itself. Is there a programmatic way to determine the log file name, so that log-related add-ons can work across Kodi variants like SPMC?

Since the SPMC installation root dir (e.g. com.semperpax.spmc on android) is aleady distinct from stock Kodi, is it really necessary for SPMC to also change the log name to 'spmc.log', given the problems it causes? Can it be reverted back to 'kodi.log'?

**Comment by koying** [comment]
SPMC v16 now has it's own log uploader
