### ISSUE TITLE
Dash not available in 16.5.3

### ISSUE THREAD

**Issue by compyy** [koying/SPMC#623]
Can you please share simple troubleshooting guide to make sure Dash is enabled on Android ? what to check, im clueless how to make sure Dash is enabled, i can enable it in Kodi but not in SPMC, but people can use it in SPMC not sure what m i missing , i am using 16.5.3

**Comment by compyy** [comment]
This is driving me nuts, why can't i enable Dash in 16.5.5 ? what is the issue ? do i have to install separately or it should be included in the package ?

**Comment by guidosarducci** [comment]
See https://github.com/koying/SPMC/issues/588#issuecomment-269854754 and upload a debug log, otherwise it's not possible to help.

**Comment by compyy** [comment]
Hi,

Thanks,here is the debug log.

http://paste.semperpax.com/pa3ssbghu

**Comment by guidosarducci** [comment]
`12:04:23.380 T:1397549360   ERROR: ExecuteAsync - Not executing non-existing script /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.youtube/startup.py`

This tells me you are running a broken version of the YouTube addon which didn't come from me.  This also means you didn't read the thread in #588 and use the correct YouTube addon linked in https://github.com/koying/SPMC/issues/588#issuecomment-267522164.

Install the right addon version and try again.

**Comment by compyy** [comment]
Great, it worked, I am sure i installed the correct version from your link, strange.

Thanks any way :)
