### ISSUE TITLE
Fix Live TV Playback in TVHeadend, Backport Needed

### ISSUE THREAD

**Issue by mo123** [koying/SPMC#634]
Backport needed for
https://github.com/xbmc/xbmc/pull/11318

**Comment by koying** [comment]
Nope. There is already a fix in 16.6.0.
See https://github.com/koying/SPMC/issues/541

Actually, a double workaround as 16.6.0 will support multiple surface decoders (on devices actually supporting multiple decoders, i.e. not AML).
