### ISSUE TITLE
certificates/ssl settings seem to be ignored in SPMC for MYSQL

### ISSUE THREAD

**Issue by calisro** [koying/SPMC#64]
The WIKI mentions a pull request that enabled SSL for mysql and I do see that code in the spmc git but those values seem to be ignored in spmc.  I've tried Gotham and lsengard.   

Reference:
http://kodi.wiki/view/Advancedsettings.xml

Pull request:
https://github.com/xbmc/xbmc/pull/2566

**Comment by calisro** [comment]
I took a look at the pull request and I noticed that the makefile for spmc does not include this commit:

https://github.com/theuni/xbmc/commit/9a9e64a6f933ec3388188b0e85b1305188ccc3bf

So it is not compiled with ssl support for mysql.  Is it possible to enable ssl support in spmc?

**Comment by calisro** [comment]
I compiled a debug version of the latest spmc from git and enabled the mysql flags referenced in this pull and it works perfectly.  Can this please be merged with spmc?
theuni/xbmc@9a9e64a

**Comment by koying** [comment]
Fixed in v16
