### ISSUE TITLE
Spmc 16.5.1 build 6743d75: not centered to tv

### ISSUE THREAD

**Issue by kemedia** [koying/SPMC#643]
Hi,

I have spmc 16.5.1 build 6743d75 and it is not centered to my tv. It is positioned to the bottom left of my tv. Ive tried changing acceleration settings, android display settings, unplugging hdmi etc. This issue is happening with my m8s pro box android 5.1.1 but it works fine on my amlogic s912 box perfectly.

This build is the only version that i found to be stable on both my boxes without crashes. I just get a

**Comment by koying** [comment]
Upgrade to 16.5.5
