### ISSUE TITLE
Drop in frame rate

### ISSUE THREAD

**Issue by JFG90** [koying/SPMC#677]
Hi there I was just wondering does anyone else experience a drop in frame rate every 10mins or so when playing movies in spmc? Notice it more with 1080p files, I have a Samsung 4k and have adjust refresh rate set to always, so I have no idea what could be causing it!

**Comment by yatoya** [comment]
Same here but only with h265 HEVC encoded videos.
When adjust refresh rate is set to off videos play properly but I really would like to keep it on because videos look much smoother.

**Comment by Dion250** [comment]
Ever since 16.5.0 there is all kinds of stutter and frame drops with SPMC.  Been like this for weeks now.. Don't think this thing is updated anymore.
