### ISSUE TITLE
SPMC 16.1 No audio passtrough on Minix X7

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#68]
He Koying,

I have no audio passtrough anymore on minix x7...
did you stop supporting Rockchip devices...

i hope you can rebuild a RockChip specific SPMC or i realy have to move on...
Thanks anyway greets EagleEye

**Comment by koying** [comment]
Yep, I should make it clear: No more specific rockchip support.

**Comment by blondin76** [comment]
he Koying,

I'm french sorry for my english

I poseur of a chameleon with a RK3288 chipset cloudmedia
is it expected an evolution of Kodi in SMPC 16 with the support of the RK3288?

thank you in advance for your response

**Comment by blondin76** [comment]
?
