### ISSUE TITLE
Is there a fix for automatic pausing? 

### ISSUE THREAD

**Issue by JFG90** [koying/SPMC#682]
It seems spmc is constantly randomly pausing itself on video playback, does anybody know a fix for it?

**Comment by BlindfoldNL** [comment]
This shoudn't be normal behaviour. Do you have any addons installed? Do you see anything in the logs?

**Comment by boobaby60** [comment]
I'm having the same issue, spmc 16.5.5 on Nvidia Shield TV

**Comment by JFG90** [comment]
Blindfolds its not just my device, several have reported the same issue

**Comment by ger630** [comment]
I too have had this happen to me on a AFTV Box (ver2).  No add ons installed just Artic Zepher skin.

**Comment by status42** [comment]
i have the same problem deleted or disabled all app only smpc running still have pausing

**Comment by BlindfoldNL** [comment]
@JonnyGadd I wasn't saying you're the only one, but that there's maybe some info in the logs pointing to something.
I've had an issue like this a while ago, but I always thought is was related to some of my remotes from my Android. I played a bit around with hibernate settings, and somewhere along the way it stopped, so never really bothered to check what it had been.
I have android tv remote for the non SPMC stuff and Yatse for whithin SPMC.
But I also had this issue while watching Youtube casting directly to the Shield, so might either be a different issue for me, or not specifically SPMC related.

**Comment by JFG90** [comment]
It's cool mate, I've reverted back to 16.4.2 for now, do you know what launcher.apk means?

**Comment by BlindfoldNL** [comment]
I never used it. If you mean the launcher ARM32 APK linked between the availble builds, I think that's the apk you need to install on Android Phone.
I always installed the ARM32 normal apk on my Shield and it always worked without issues, but I think I should actually install the ARCH64 version, so tried that one now and that's also working fine for me.

**Comment by JFG90** [comment]
I have removed es file Explorer which was popping up with ads all the time and free space notifications, i believe this could be the cause for the random pausing if the app was running in the background as so far after uninstalling it hasn't done it, but i could be wrong

**Comment by ger630** [comment]
I don''t have ES F.E. on mine so not what is effecting me.

**Comment by koying** [comment]
The origin may be different, but the cause is probably the same: "something" coming, even for a split second, on the frontend, which pauses SPMC.

**Comment by JFG90** [comment]
Well I've had es Explorer uninstalled a few days now and haven't had anymore issues with it passim my end so i believe it was the problem for me, I'm 16.4.2 though as I'm getting jittery playback on my paid iptv sub on any other higher version, I did upload a paste id so fingers crossed it gets fixed :) appreciate all your hard work Koying!

**Comment by JFG90** [comment]
And I definitely know it was something causing the pauses as I was getting pauses on 16.4.2 the other day which i never used to get, so it's not the software, es was triggering it, if i do get anymore pauses I'll post back here but it's been absolutely fine since

**Comment by clown522** [comment]
For me it is also gone since i switched to the es explorer "pro" version. It is ad-free. I share your experience.
Hardware: Sony Android TV

**Comment by boobaby60** [comment]
I'll uninstall es file explorer and see if that helps, 16.5.5 Nvidia Shield, thanks @JonnyGadd
