### ISSUE TITLE
Which apk to use for android phone and box?

### ISSUE THREAD

**Issue by kemedia** [koying/SPMC#691]
Hi,

I was wondering what apk version do i use for an android 6.0 phone  (samsung galaxy s6 edge) and a android 6.0 s912 box? I want to install it on my phone and android tv box.

Thank you

**Comment by sammarbella** [comment]
Depends on the phone SoC.You should looks at the device specs.

If it's 64 bit choose aarch64 builds, 32 bit (V7A) builds will also works.

On 32 bit SoC (ARMv7a) devices only V7A builds will work.
