### ISSUE TITLE
Add in 'suspend' command in system menu

### ISSUE THREAD

**Issue by lingnand** [koying/SPMC#7]
This would be really useful (no need to pick up ouya controller, double tap U button, and choose 'sleep' anymore).

There isn't any readily available command like `reboot` in the system for us to call for suspension. So I guess we need to leverage the ndk api (using a PowerManager presumably, look at [this](http://stackoverflow.com/questions/6756768/turn-off-screen-on-android))

**Comment by elmerohueso** [comment]
I found that simulating a POWER keypress will put Android to sleep.  I've been using this method in a Python "screensaver" I made for XBMC.  The only issue I see with this is that, if your device has CEC, the button press could be relayed to your other devices.  To resolve this (at least on the Fire TV) I issue commands to disable CEC, send the button press, then enable CEC.  The following is the Python code.

import system
def sleep():
    os.system("su -c 'echo 0 > /sys/devices/virtual/graphics/fb0/cec'")
    os.system("su -c 'input keyevent KEYCODE_POWER'")
    os.system("su -c 'echo 1 > /sys/devices/virtual/graphics/fb0/cec'")

I'm not sure if it's an Android standard to have CEC control in that same location, and I don't actually use CEC (I've relied on others to test it).
I am successfully using this on both the Fire TV and OUYA, though.

**Comment by koying** [comment]
Yeah, cec can be a bitch. In xbmc self, you can disable some features, but if  cec is handled at the system level...

**Comment by elmerohueso** [comment]
This can probably be closed as code has been merged.

**Comment by varun046** [comment]
Use this 

"/sys/devices/virtual/graphics/fb0/cec # echo 1 > enable" 
instead.
