### ISSUE TITLE
Updates for the Wiki for Shield Experience 5.0.1

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#702]
@koying 

I have updated the 4k video page based on my testing and recent issues opened by others.

I will update the 1080 video page after more testing of Shield Experience 5.0.1.

If anyone's experience with SE5.0.1 is different than mine, please reply below, so I can incorporate in the Wiki.

Audio passthrough is frequently problematic as of Shield Experience 5.0.1 using the recommended settings. It either works or is silent. If silent, you must close and restart SPMC. This is true across multiple '17 Shield TVs.

Separately, SE5.0 was supposed to bring IEC support (the same way that Kodi Krypton sends passthrough) but my testing results in only silence with SPMC 16.5.5. So my testing above is based on RAW.

**Comment by Qpadder** [comment]
>classicjazz
Audio passthrough is frequently problematic as of Shield Experience 5.0.1 using the recommended settings. It either works or is silent. If silent, you must close and restart SPMC. This is true across multiple '17 Shield TVs.

I have audio issues, when watching a film with Dolby True HD. When there is very heavy sound, my playback pauses , and I have to restart SPMC to continue. 

Also have the problem when playback randomly pauses, and then the Screensaver starts.

**Comment by snowlucas** [comment]
So I'm running Shield Experience 5.01 on an 2017 Nvidia Shield to a Onkyo NR809 amp (Not HDMI 2.0) and then onto a Sony Bravia KDL55W8 at 1080p/60 (Also not HDMI 2.0).

I have the issue described above, no sound on passthrough IEC and passthrough sometimes working and sometimes not working (no sound or garbage sound) with passthrough RAW. When it does work I'm getting audio sync issues which do not occur in other android apps on the same setup. I am also getting audio sync issues with passthrough turned off in SPMC.

As a workaround I have turned off Adjust Display Refresh Rate and all these issues disappear; passthrough works perfectly on DTS, DD, DD+, DTS MA and DD trueHD and crucially no audio sync issues. Most of these files are at 24 frames a second so this is not ideal but I'd be interested if other have the same issues with refresh ate switching.

**Comment by flensburg2** [comment]
Hi, I also experience  the same as you describe with no sound. A workaround for me has been going into OSD , select upmix stereo - then directly deselect it again. Sound comes back.

**Comment by JonRStorey** [comment]
I noticed the updated settings page for 4k but with my setup (Shield>yamaha AV>Samsung UHD)  the only way to get everything to switch and play back correctly {with HDR at all resolutions including 23.976hz} is to enable surface and then disable hardware acceleration for everything but HEVC - appreciated if you could confirm this is the best way forward Koying please.

**Comment by flensburg2** [comment]
Also,  osd,  disabling then enabling passthrough gives me sound back again..

**Comment by rfgamaral** [comment]
@classicjazz I'm curious about this:

> If you are a 16.6 beta tester, then you should use IEC rather than RAW for passthrough, where noted below

Is this a bug on the 16.6 beta or this setting should be set to IEC instead of RAW from this point forward? Why?

**Comment by JonRStorey** [comment]
@classicjazz firstly thank you for all your input on here it has been invaluable, regarding SPMC on the nvidia shield can you confirm if software yadif2x is better quality than hardware 'bob inverted' please? I currently have hardware acceleration turned off to use yadif2x but uncertain if this is the best approach quality wise. Thanks in anticipation.

**Comment by classicjazz** [comment]
@JonRStorey 
You are welcome. Yadif2x is better quality deinterlacing that bob inverted. However, the Shield doesn't seem to handle 1080i files well with yadif2x. So, I recommend using yadif and software deinterlacing solely for 480i files. Your best choice using hardware acceleration for HD files then is bob inverted.  In practice, this mainly applies to ATSC (live TV) feeds.

**Comment by classicjazz** [comment]
@rfgamaral 
IEC is a newly supported capability in Nougat, upon which SE5.0.x is based. Koying added IEC fixes in 16.6beta. It's better to use IEC than RAW going forward if you are using the 16.6beta and assuming that you have upgraded your Shield to SE5.0.x. 

There are more details about this (as applied to Kodi 17) here:
http://forum.kodi.tv/showthread.php?tid=289735

There are still a few bugs re IEC's implementation in the SPMC that I have shared with Koying. But that's why it's called a beta ;-)

**Comment by classicjazz** [comment]
All--

Thanks for your input. I have completely updated the Shield 4K and 1080p Wikis, along with tweaks to the audio passthrough Wiki.

**4K Wiki changes include:**
- better explanation about HDR dependencies (surface, HDR-10, HDMI 2.0a, right cables, right display firmware, etc.)
- distinction between RGB output and YCbCr output, with prioritized list of YCbCr mode you should select, if supported
- 3 sec recommended pause during refresh change (no on start/stop)
- suggestions about other Android programs that may interfere with smooth playback.
- for now, I still recommend using the 4K with HQ scalers. Koying and I submitted a bug request to Nvidia, asking them to fix Mode API so it would permit SPMC to request a physical resolution = native video resolution. This would then permit your UHD to upscale just that video from its original resolution rather than using Kodi's HQ scalers or Nvidia's upscalers.

**1080p Wiki changes include:**
- significant streamlining
- 3 sec recommended pause during refresh change (no on start/stop)
- I would like to consolidate the two Wiki's into one, once Mode API issues are resolved.

**audio passthrough changes include**
- IEC recommended for 16.6beta and beyond
- 3 sec recommended pause during refresh change (no on start/stop)

**Comment by JonRStorey** [comment]
@classicjazz,
Thanks for the prompt reply, again appreciated, i have taken your recommendations and changed the settings but on one minor point when switching from HW to SW files i get the flickering screen and have to restart the SD film every time - i think this was a known bug but do you know if  there is a workaround / fix available?

A lot of the kids films i have are SD and the children have less patience than me! If i continue to use Yadif 2x for files on their profile will the shield melt down prematurely due to the increased CPU usage?

For everyone reading this what i didn't appreciate is that SPMC has a donate button! If your using SPMC give a little, its easy to do with your wife's PayPal account, get a warm fuzzy feeling knowing in some small manner you're helping to keep it going and you appreciate the effort put - if you paid £180 for an nvidia shield you can spare some cash for the best software to put on it.

**Comment by classicjazz** [comment]
@JonRStorey and @koying 
Yes, I just duplicated the flickering/strobing effect in 16.6beta2 when using FFMPEG and yadif. A temporary solution is to disable yadif by disabling software decoding. You can do this by telling it to always accelerate for each video codec.

Koying, let me know if you need sample files or logs.

**Comment by JonRStorey** [comment]
@classicjazz 
I have done as instructed thanks and will look back here to see if there is a fix in due course, just downloading another preview firmware from Nvidia - lets hope that fixes more that it breaks!

**Comment by JonRStorey** [comment]
@classicjazz 
Back again, another easy one for you - is this line still relevant after the 2160 settings in the advancedsettings.xml file:

< imagescalingalgorithm >lanczos< / imagescalingalgorithm >

Again thanks in anticipation

**Comment by classicjazz** [comment]
@classicjazz
> Back again, another easy one for you - is this line still relevant after the 2160 settings in the advancedsettings.xml file: <imagescalingalgorithm >lanczos< / imagescalingalgorithm >

Yes, the 2160 settings along with lanczos image scaling improve the quality of the fanart and thumbs when they are cached, and intended for use with a 4K GUI. See:
http://forum.kodi.tv/showthread.php?tid=200401&pid=2282659#pid2282659

However there is still a second scaling that occurs when an image is pulled from the cache and resized as required by the skin. And when 1080p skin textures are resized. Popcornmix says this uses bilnear, an inferior algorithm, which I don't think was updated with Kodi 17.
http://forum.kodi.tv/showthread.php?tid=200401&pid=2150625#pid2150625

@Koying see here:
https://github.com/xbmc/xbmc/blob/master/xbmc/pictures/Picture.cpp#L245

To be clear this is different than the upscaling of video.

**Comment by JonRStorey** [comment]
@classicjazz and @koying 
Having had a major hiccup with adopted storage yesterday i decided to bite the bullit, so factory reset and added the lanczos algorithm to the AS.xml and rebuilt the library entirely - highly subjective but IMHO it has improved the UI somewhat so again thanks to you both for your highly informative answers.
