### ISSUE TITLE
16.6.0 beta3 (TEST)

### ISSUE THREAD

**Issue by koying** [koying/SPMC#706]
3rd beta: https://github.com/koying/SPMC/releases/tag/16.5.82-spmc

It has a "test" signature, so can be installed along 16.5.

Changelog for 16.6:
- ADD: "Visible behind" for Android TV
- ADD: "Now playing" for Android TV
- FIX: HD audio IEC on N (Shield + Mi)
- FIX: use PT RAW for re-encoding if selected- FIX: 3D -> 2D in amcs
- FIX: windowed amc
- ADD: Dynamic amcs surfaces
- FIX: amcs rotation
- FIX: plugin cache
- ADD: zeroconf via API

Changelog for beta 2:
- FIX: 4K GUI
- FIX: High CPU load

Changelog for beta 3:
- ADD: Smoothstreaming
- FIX: crash on exit with NFS

**Comment by classicjazz** [comment]
I installed SPMC-16.5.80-spmc-9ba4490-aarch64.apk (network ADB) and started it. The icon moved and everything froze. I had to reboot the '17 Shield running 5.0.1. On restart, it started OK.

**Comment by classicjazz** [comment]
I copied over all the files (userdata, addons, etc.) from my working 16.5.5 folder. There is a strange bug wherein the GUI is zoomed from the bottom left, so you can only see a portion of the screen. If you adjust the refresh rate, the GUI properly displays. However, exiting SPMC and restarting it then repeats the zoom on start issue even if you left it at a different refresh rate.

All setting per Wiki with 4K GUI. The one change is that the system refresh rate for 4K should be 59.94 show with SE5.0.1. 

I uploaded a debug log starting with php6 (the rest of the dialog box is stretch so its contents are illegible).

**Comment by classicjazz** [comment]
Once you start a video then you briefly see a flash of the superzoomed GUI before video starts playing.

I changed my audio settings to IEC from RAW (both settings) and I get a rapid machine gun fire sound.

See debug log starting with "plug..."

**Comment by radioactivetoy** [comment]
4k gui is not workign for me, Settings Gui to unlimited (shield configured to 4k 60hz) makes SPMC to only show the botton left quarter of the gui. It's like if it is a 1080p o  720p screen showing a 4k picture without scaling down.

**Comment by JFG90** [comment]
Hopefully this fixes the jittery playback issue I was having

**Comment by anakin4153** [comment]
Same issue as radioactive toy, I can only see the left quarter of the GUI with Shield configured to 4k/60

**Comment by 99rook99** [comment]
I'm sure that koying might want logs to fix the problem,  plus what equipment SPMC is running on.

**Comment by radioactivetoy** [comment]
Shield TV, firmware 3.3. I'll try to upload a log tomorrow.

**Comment by sylvio2000** [comment]
I think 16.6.0 is not based on Kodi 17?
Is there any plan for a beta test of SPMC 17?

**Comment by radioactivetoy** [comment]
I have just compiled spmc-jarvis branch and commit "3e99f5d7766c5768dc40f8eb6012986614d68a5f FIX: [egl;droid] must set buffer geometry" solves the problem of the zoomed 4k gui.

**Comment by Schrotty74** [comment]
No hd audio in new Shield 2017. Dts also not working.

**Comment by Schrotty74** [comment]
Its working now.

**Comment by ghost** [comment]
ReleaseHub issue is still evident with this beta build.
**Release Hub video restarts** #636

**Comment by wesk05** [comment]
HD audio passthrough using IEC61937 is working for me. 
@koying : Does resolution switch work now? I see you have a commit for Display Mode API.

**Comment by Uukrull** [comment]
I noticed a much higher CPU usage with this version on my Shield. Reverting https://github.com/koying/libdroidjni/commit/16bc52b9a3012ea8a00f5de38709883e41c617b1 fixed the issue for me.

**Comment by wrxtasy** [comment]
Feedback so far testing with the IEC capable Mi Box:
 - The Zeroconf API works well for the very first time **EVER** with my El Capitan OSX iMac 👍 
This updated API (if not already) should be upstreamed into Android Krypton.

- Initially had **Jittery Video Playback** (SPMC 16.5.5 & test 16.5.80) & 10bit HEVC video picture breakup.
The cause was Kodi Krypton RC4 minimised in the background. I quit Krypton and normal video playback then resumed in SPMC.

**Comment by koying** [comment]
Could someone affected with the "crash on exit" bug in 16.5 comment on 16.6, please.
It seems I don't see it anymore.

**Comment by Schrotty74** [comment]
I dont have crash on exit.

**Comment by CiNcH83** [comment]
Cool release so far. ZeroConf works beautifully (AirPlay). I like the wallpaper video ("Visible Behind") and "Now Playing". On SPMC it is also possible to bring up the _Action_ menu on Sony and subsequent picture adjustments without stopping the running video (which unfortunately is not possible with the "official" Kodi).

**Comment by mrwookie28** [comment]
Liking the "Visible behind" and "Now Playing" for Android TV but notice on Nvidia Shield TV (2015) the text box and text for Now Playing are both shown as white when highlighted.

**Comment by esoteradactyl** [comment]
HD audio passthrough using IEC61937 is working perfectly for me on the shield. One annoying thing though, the shields voume control is always set to max after audio has been being passed through.  After watching a movie and switching over to say Youtube, it's very loud unless I lower the volume on the AVR about -20db. I have no clue if this is an issue with SPMC or Android OS. With the old passthrough method this obviously wasn't an issue and I was able to keep the volume between the android apps and passthrough consistent. Not a major deal, but thought it's something I would point out.

**Comment by woronczak** [comment]
I am not sure what the "FIX: 3D -> 2D in amcs" is supposed to fix exactly - if it is what I reported in https://github.com/koying/SPMC/issues/657, then unfortunately it doesn't work (same behaviour as in post). Using amcodec,  (for 3d MVC MKVS, even when 3d is turned off or "ignore" is selected in settings, it still displays the movies in Top and Bottom; 3d isos, when you select play in 3d but then turn 3d off, it still plays in Top and Bottom as well),
If need more info, happy to help

**Comment by anakin4153** [comment]
Quick question, is the fix for the 4k GUI already available, or should we wait for another build ? Thanks :)

**Comment by ronniehd** [comment]
Hello, can anyone please tell me what spmc build version should i use with Shield TV 2015? 

Thank you in advance!

**Comment by s2law** [comment]
16.5-5 the current stable release

**Comment by ronniehd** [comment]
Thanks but i meant if armv7, aarch64 or which build is the recommended one i should download that works best or is meant for Shield TV.

**Comment by s2law** [comment]
64 for the shield tv

**Comment by ByteShare** [comment]
Does anyone know which type of art SPMC uses for the home screen recommendations?
Limits for the art (dimensions, file-type, size)?
I see some shows displaying artwork but not for all, and as far as I can tell the shows/movies that aren't showing have the all the required artwork. I even see some shows have the same type of picture and dimensions but not the same file size.
I don't have this issue with VLC's recommendations. 
Update:
Figured this out a little bit more. I wasn't missing the art but after I reloaded the art with TMM (TinyMediaManager) and refreshed in SPMC for the shows not displaying art on the Android TV home screen I am seeing the art.
I confirmed SPMC is using the "Thumb.jpg" file, which isn't coming from TheTVDB.com (I don't think). Not sure about the filesize or dimensions limits.
Update Update:
Looks like if the Thumbs.jpg is missing it defaults to the poster.jpg

**Comment by sammarbella** [comment]
I'm not getting a clean exit on 16.5.80, after clicking on "exit" nothing happens and i must leave to home using the home button on remote, a couple minutes later i get the advice SPMC crashed.

I can't force stop it going to home>system>apps>SPMC the option is not present.

**Comment by ghost** [comment]
Since the Shield updated a few days back getting pixelated/stuttering playback on a lot of videos.
This is with the beta 1, is there a new beta coming soon ?
Prior to shield update everything with beta was fine apart from #636 Release Hub issue already mentioned.

**Comment by JGrana01** [comment]
Quick question. I have my Shield pointing spmc's data to my external drive using spmc_env.properties in the root directory of /sdcard.
Works great.
If I sideload 16.5.80, where does it store userdata? I have a backup of my /userdata folder ready to copy to where 16.5.80 wants them.

**Comment by koying** [comment]
Bumped to beta 2

**Comment by JFG90** [comment]
I shall test it, don't suppose you was able to look at the log I uploaded for the jittery playback koying? Was running spmc 16.5.5 on a nvidia shield

**Comment by classicjazz** [comment]
@koying I just installed SPMC-16.5.81-spmc-fce21e6-aarch64.apk. But SPMC says it is build 16.5.**80** with yesterday's date.

**Comment by JFG90** [comment]
S2law is the version from the playstore aarch64 do you know? As I usually just update through there

**Comment by classicjazz** [comment]
@koying 
I am still having passthrough issues with IEC. First play will have momentary distortion/flanging. Subsequent play of same video will have no sound. See log beginning with pnm2 (rest of dialog box is stretched and unreadable).

**Comment by koying** [comment]
@classicjazz Mind enabling debug? Forgot to actually bump internal version, indeed...

**Comment by classicjazz** [comment]
Debug log sent via email including my understanding of what's happening.

**Comment by koying** [comment]
@classicjazz Didn't get your email (not even in spam).

**Comment by purbanowski** [comment]
@koying Unfortunately beta 2 is still crashing on exit.
To reproduce the issue you have to play a video file, then try to exit the SPMC. If you try to exit the SPMS without playing any video file, then it quits properly..

**Comment by rfgamaral** [comment]
I still have a crash on closing SPMC. Not sure if this helps, but:

```
02-08 19:33:02.237 17711 17735 V SPMC    : virtual void CXBMCApp::onDestroy()
02-08 19:33:02.239 17711 17735 V SPMC    : CEventLoop: we are being destroyed
02-08 19:33:02.239 17711 17735 V SPMC    : android_main: Exiting
02-08 19:33:02.291 17711 17735 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x5bb72508 in tid 17735 (Thread-2)
02-08 19:33:02.291   207   207 W         : debuggerd: handling request: pid=17711 uid=10064 gid=10064 tid=17735
02-08 19:33:02.354 17822 17822 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-08 19:33:02.354 17822 17822 F DEBUG   : Build fingerprint: 'NVIDIA/foster_e/foster:7.0/NRD90M/1915764_835.9903:user/release-keys'
02-08 19:33:02.354 17822 17822 F DEBUG   : Revision: '0'
02-08 19:33:02.354 17822 17822 F DEBUG   : ABI: 'arm'
02-08 19:33:02.354 17822 17822 F DEBUG   : pid: 17711, tid: 17735, name: Thread-2  >>> com.semperpax.spmctest <<<
02-08 19:33:02.354 17822 17822 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5bb72508
02-08 19:33:02.354 17822 17822 F DEBUG   :     r0 6ec19e40  r1 6ec19e40  r2 00000000  r3 5bb72508
02-08 19:33:02.354 17822 17822 F DEBUG   :     r4 6ec219d8  r5 56a9d500  r6 56a9d54c  r7 569c04ec
02-08 19:33:02.354 17822 17822 F DEBUG   :     r8 547d820c  r9 45abb420  sl 000000d4  fp 00001000
02-08 19:33:02.354 17822 17822 F DEBUG   :     ip 569c0500  sp 53804738  lr 547d804c  pc 5bb72508  cpsr 200f0010
02-08 19:33:02.357 17822 17822 F DEBUG   :
02-08 19:33:02.357 17822 17822 F DEBUG   : backtrace:
02-08 19:33:02.357 17822 17822 F DEBUG   :     #00 pc 5bb72508  <unknown>
02-08 19:33:02.357 17822 17822 F DEBUG   :     #01 pc 00a35048  /data/app/com.semperpax.spmctest-1/lib/arm/libspmc.so (_ZN14CNfsConnection19destroyOpenContextsEv+88)
02-08 19:33:02.357 17822 17822 F DEBUG   :     #02 pc 00a351e4  /data/app/com.semperpax.spmctest-1/lib/arm/libspmc.so (_ZN14CNfsConnection6DeinitEv+48)
02-08 19:33:02.357 17822 17822 F DEBUG   :     #03 pc 00a3521c  /data/app/com.semperpax.spmctest-1/lib/arm/libspmc.so (_ZN14CNfsConnectionD2Ev+16)
02-08 19:33:02.357 17822 17822 F DEBUG   :     #04 pc 000520df  /system/lib/libc.so (__cxa_finalize+126)
02-08 19:33:02.357 17822 17822 F DEBUG   :     #05 pc 000162fb  /system/lib/libc.so (exit+10)
02-08 19:33:02.357 17822 17822 F DEBUG   :     #06 pc 005823b8  /data/app/com.semperpax.spmctest-1/lib/arm/libspmc.so (android_main+368)
02-08 19:33:02.357 17822 17822 F DEBUG   :     #07 pc 0057f1d4  /data/app/com.semperpax.spmctest-1/lib/arm/libspmc.so
```

**Comment by classicjazz** [comment]
Using the new recommended settings for IEC passthrough with beta2, there is a 2 second lag between when the video stops and pause OSD appears and when the audio stops.

**Comment by classicjazz** [comment]
Also, @koying  just making sure you saw the reference to flickering/strobing when using yadif (FFMPEG decoder) for 480i videos with beta2. 

https://github.com/koying/SPMC/issues/702

**Comment by Gertbucket** [comment]
Getting any closer to releasing this?

**Comment by koying** [comment]
I forgot to actually publish beta 3. Now done ;)

**Comment by JFG90** [comment]
@koying probably a stupid question but what is smoothstreaming?

**Comment by JFG90** [comment]
I would just like to add that the beta is fantastic! No longer getting crashes on my shield aswell as I've noticed it minimises when you back out of video playback which seems to prevent it happening! Excellent work!

**Comment by Theetjuh** [comment]
Haven't had a crash neither, looking good!

**Comment by Gertbucket** [comment]
@koying As this beta installs alongside the regular release we end up with two indentical icons and no way of telling them apart. Would you mind changing the icon slightly for the beta releases? Any icon would do really. Thanks.

**Comment by JFG90** [comment]
I just uninstalled spmc and am using the beta til it's officially released as it's working perfectly, i will just reinstall when it's released

**Comment by Karkas66** [comment]
I want to pick up Gertbuchets Idea with a Beta Icon, It´s really annoying to search for the right one to test!

Btw, I upgraded my 2015 Shield to 5.1 today. Everything is working great, including 4k UHD content, Passthrough 7.4.1 with Dolby Atmos, DTS-X, and DTS-HD-MA.

Some more little things to test, will report if I find something not working as expected

**Comment by classicjazz** [comment]
I have been using beta 3 for several days on 5 Shield TVs. Things are running very smoothly on Shield Experience 5.1. I think that this is the best SPMC release yet.

**Comment by koying** [comment]
Ok, cool. Thanks for the reports.
I guess I will release this WE.

**Comment by Karkas66** [comment]
I think there are still minor visual framedrops in the Video Stream if you watch a Movie for over 30 Minutes like discussed in [this thread](https://github.com/koying/SPMC/issues/615), but I still need to investigate in this (with debug). L8er!

**Comment by Karkas66** [comment]
OK i´ve found a bug in the 5.1 Release. For some reason Nvidia dropped support for 24hz video resolution in my setup. SPMC Debug Log says on startup:

22:13:34.119 T:1541237024  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940060 Hz
22:13:34.119 T:1541237024  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 59.940060 Hz
22:13:34.119 T:1541237024  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
22:13:34.119 T:1541237024  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 60.000000 Hz
22:13:34.119 T:1541237024  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
22:13:34.119 T:1541237024  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 50.000000 Hz
22:13:34.119 T:1541237024  NOTICE: Found (1920x1080@59.940060) at 16, setting to RES_DESKTOP at 16
22:13:34.119 T:1541237024  NOTICE: Checking resolution 16

The Android App TVHZ from Chainfire confirms this. Application can not see the 24p resolution support of my setup, that has been there in the 3.3 Release. Here is an old spmc log entry:

18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 23.976025 Hz
18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 24.000000 Hz
18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 25.000000 Hz
18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 29.970030 Hz
18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 30.000000 Hz
18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 50.000000 Hz
18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 59.940060 Hz
18:32:05.335 T:1477937456  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 60.000000 Hz
18:32:05.335 T:1477937456  NOTICE: Found (3840x2160@60.000000) at 23, setting to RES_DESKTOP at 16

I think there is not much we can do about it. Is here anyone who still has 24p resolution in a 4k Setup with an active AVR in between TV and Shield?

**Comment by MrMC** [comment]
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940060 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 59.940060 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 50.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 60.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 30.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 30.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 24.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 25.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 25.000000 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 29.970030 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 29.970030 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 23.976025 Hz
08:10:25 T:138680894544  NOTICE: Found resolution 3840 x 2160 for display 0 with 3840 x 2160 @ 23.976025 Hz

Works for me on 5.1. MrMC -> Denon W3200 -> Samsung UHDTV
[ro.build.version.ota]: [5.1(24.28.403.124)]

**Comment by JFG90** [comment]
@Karkass66 have you tried turning adjust refresh rate off? I don't have mine on as in my opinion it's not needed, everything plays perfectly for me

**Comment by Karkas66** [comment]
I just tried it @JonnyGadd but sadly it brings visual shutter every 8-10 seconds on 24hz and 25hz Video Files :-(
But It is better than the constant framedrop I have without it

**Comment by Karkas66** [comment]
Some ppl @ the nvidia Forum posted similar hickups due to refresh rate not synced to frame rate:

https://forums.geforce.com/default/topic/994727/shield-tv/shield-experience-upgrade-5-1-for-shield-tv/post/5093356/#5093356

**Comment by JFG90** [comment]
That sucks mate I can't say I've come across that myself!

**Comment by Karkas66** [comment]
OK Rollback guys. I found the Problem! It was a setting in my AVR that changed the published resolutions to only 50/60hz. I revoked that and everything is at it´s supposed resolution again with refresh rate change on. I try some video files now to see if there are other problems left

**Comment by ghost** [comment]
https://github.com/koying/SPMC/issues/783

Using BETA3

**Comment by LostEchoes** [comment]
I also I copied over all the files (userdata, addons, etc.) from my working 16.5.5 folder to the latest 16.5.8 beta3 test folder. The fist time I used SPMC 16.5.8 I had a crash on exit. Just once. Unfortunately I did not keep the log. All the next times I used SPMC I did not have that crash on exit error.

p.s. Having the 16.5.8 beta3 installed, will we get the update for the stable version, or do we have to revert to 16.5.5 to get it?

**Comment by Theetjuh** [comment]
My 2015 Sony TV is upgraded to Marshmallow, DTS isn't working anymore.
Is that because of MediaTek? Or should it still work on RAW with this test build?
I read something in the passthrough topic on Kodi, that it was removed or atleast left out.

**Comment by LostEchoes** [comment]
Well after I watched a tv series I've got the crash on exit error again. Here is the log:

http://paste.semperpax.com/pciusboey

**Comment by koying** [comment]
> Well after I watched a tv series I've got the crash on exit error again

Well, that's still beta2

**Comment by koying** [comment]
> My 2015 Sony TV is upgraded to Marshmallow, DTS isn't working anymore

Should work in IEC. Doesn't it?
RAW assumes working RAW DTS on Mashmallow, which is not the case on Sony and Phillips TV

**Comment by Theetjuh** [comment]
> Should work in IEC. Doesn't it?
RAW assumes working RAW DTS on Mashmallow, which is not the case on Sony and Phillips TV

Setting both on IEC only delivers static

**Comment by LostEchoes** [comment]
@Koying
That's really strange. I'm confident I downloaded and installed Beta 3.

Edit: I probably accidentally downloaded Beta 2.

**Comment by JFG90** [comment]
The latest beta has been perfect for he with no crashes after exit on playback! When will this be ready for official release?

**Comment by koying** [comment]
16.6.0 is released.
Thanks for your feedback.
