### ISSUE TITLE
No DTS pass-through on 2017 shield.

### ISSUE THREAD

**Issue by AlphaSupreme** [koying/SPMC#707]
Got the 2017 Nvidia Shield with SPMC to replace my odroid c2.
Dolby digital and dolby true HD work fine with pass-through, DTS and DTS-HD do not work with pass-through enabled.
Setup: LG ef950v TV, DENON AV-X2200W receiver and 2017 nvidia shield with SPMC.

Also tested it with a yamaha rx-v565 receiver, that does seem to work. So it seems to be something in the combination shield/denon. With the odroid c2 it all worked fine.

**Comment by Schrotty74** [comment]
I have the same problem. No dts or hd audio working.

**Comment by Schrotty74** [comment]
Its working now.

**Comment by AlphaSupreme** [comment]
How did you get it working?

**Comment by Schrotty74** [comment]
I have set adjust display refresh rate = off and
sync playback to display = off

**Comment by AlphaSupreme** [comment]
Tested it yesterday, no luck.
The DTS and DTS-HD streams are picked up as stereo on the receiver.

I also opened a ticket with denon about this.

**Comment by arccpl** [comment]
im having the same problem. DD works but DTS no, I have old Sony Receiver with supports DD and DTS.
I have it connected via SPDIF. Only the build in Philips Android TV Player play all kind of audio/video type without issues, and Then if I try KODI/SPMC Plex or Emby there is no DD and DTS or DD is and DTS in not.

**Comment by mikeB2210** [comment]
same Problem :-( DD works, DTS nope. With Kodi Krypton RC3 no Problems.
I think its a problem with the shield / Nougat setup. I figgured out that the problems occured by playing DTS-HD soundtracks. In this case the box will not fallback to play the included DTS track.

**Comment by willsy555** [comment]
I had the same problem. Actually got a Shield 2017 recently so decided to try SPMC first. Trouble is I couldn't get both the DTS and Dolby Digital working at the same time. Found that I could get one working by changing sound mode from 5.1 to 7.1 and vice versa. My Marantz NR1506 5.1 AVR (connected to the Shield via HDMI) can accept 7.1 signals, so not sure why my initial setting of 7.1 didn't work for both DTS and Dolby Digital. In the end put on the latest version of Kodi on there instead. This works for both DTS and Dolby Digital (with a 7.1 audio setting on Kodi). Would prefer to be using SPMC though! :-(

**Comment by BwanaFr** [comment]
I have the same problem, no DTS pass-trough on my Denon receiver (worked before upgrade to Android 7).
I noticed the DTS pass-trough works if you disable/re-enable pass-trough during playback using audio menu.

**Comment by Matusov** [comment]
I've been struggling with surround sound and shield for almost a year now. Android 7 finally solved DD issues.

Still no DTS in Kodi no matter what I tried. However to my pleasant surprise Plex was able to output DTS and my amp verified.

I'm convinced it's a software issue to this point, not your AV or Shield.
