### ISSUE TITLE
Jittery playback UPDATED 

### ISSUE THREAD

**Issue by JFG90** [koying/SPMC#708]
Hi there so I installed fresh spmc with no build, and installed my paid subscription IPTV addon along with the TV guide addon I have, it seems streams play fine through the IPTV addon but as soon as they are loaded through my TV guide the jittery playback starts, never used to have this issue on 16.4.2 anyway I've uploaded a paste id being pujowukde would it be possible to have a look and see why it's doing it? Would really appreciate it! Thanks!

**Comment by wrxtasy** [comment]
You will get very little help because you make no mention at all of what actual Hardware you are using SPMC with. We are not mind readers.

Also is there any good reason why you have not updated (via Play Store) to SPMC 16.5.5 ?

**EDIT:** Quit any other Kodi Jarvis / Krypton you may have minimised in the background may help with the Jitters.

**Comment by JFG90** [comment]
No need to get rude about it, I'm running on a nvidia shield and have tested it on every release after 16.4.2 and its been the same, and tested it on his new newest release when i pushed the paste. Don't speak to me like I'm a child

**Comment by JFG90** [comment]
And I was on 16.5.5 but had to revert back to 16.4.2 because of the issue I was having, and i don't have kodi Krypton installed

**Comment by wrxtasy** [comment]
I suggest Disabling "Sync playback to Display" as well if not done so already. 👍

**Comment by JFG90** [comment]
@koying I would like to massively apologise that this was indeed my end the whole time, it was motion plus on my TV that was causing the issue so after switching it off its been perfect!

**Comment by koying** [comment]
\0/
