### ISSUE TITLE
TrueHD Lag with SPMC Jarvis

### ISSUE THREAD

**Issue by mattsch** [koying/SPMC#71]
Playing a movie with a TrueHD track has some stutter at the beginning and the audio lags significantly.  Same hardware as the DTS ticket.

[Mediainfo](https://github.com/koying/SPMC/files/171047/truehd-mediainfo.txt)
[Debug log](https://github.com/koying/SPMC/files/171048/truehd.txt)
[Sample](https://drive.google.com/open?id=0B25LBca0qlnuenlGMlpNelpzVDg)

**Comment by audiomixer** [comment]
More on the TrueHD lag with SPMC Jarvis #71 you have listed as bug. Not sure if this helps, but if I start a movie with TrueHD using either the iOS remote or shield remote, the sync is usually off at varying degrees. If I stop the movie and resume using the iOS remote from the movie pull down of the app, sync will still be off. If I resume from the TV screen using the shield remote, sync is on. Seems that there is a longer pause when resuming from the tv using the shield remote.

Here is my [log](http://spmclogs.semperpax.com/pazajr4hd).

**Comment by Blurayx** [comment]
I have the same issue

**Comment by fjsonin** [comment]
Hello, same problem for me. I have lag with TrueHD track. The audio is ok but the video lag (not as much as mattsch but still)
