### ISSUE TITLE
SPMC 16.5.5 Black Screen - advancedsettings.xml

### ISSUE THREAD

**Issue by hpnas47** [koying/SPMC#713]
I installed a fresh copy of SPMC 16.5.5 and everything was working fine until I dropped the sample advancedsettings.xml file into my spmc userdata folder.  Once I did that and restarted my SPMC it would open to a black screen and go no further.  Nothing I could do would fix it unless I completely uninstalled SPMC and re-installed (which is extremely frustrating to set up my preferences again)

Any ideas why the advancedsettings.xml would cause my SPMC to get corrupted??

**Comment by classicjazz** [comment]
The advancedsettings.xml by itself wouldn't corrupt your userdata folder. 

If you copied every single setting without changing anything (not recommended), then it would have looked for your video and music databases on a local network server. 

In the future, you may wish to back up your .spmc folder. That way you can restore your preferences, copy them to test instances, etc. If you are using a Shield, it is easy to do this via a SMB share.

**Comment by hpnas47** [comment]
Seems to be fixed now, thanks for the help
