### ISSUE TITLE
Ambilight - question

### ISSUE THREAD

**Issue by ziggy73701** [koying/SPMC#719]
Just tested the new   <usedroidprojectioncapture>true</usedroidprojectioncapture> for advanced settings and it works brilliantly!! So awesome stuff!

Am guessing this will only capture what's on screen when a video file is playing? Is there any way to extend to capture everything on screen ie menus etc? Or a music visualization?

**Comment by koying** [comment]
As a matter of fact, the capture will work anywhere in SPMC (those are screenshots, really), but the addons probably only actually handle the captures when a video is playing.

**Comment by ziggy73701** [comment]
Hmmm... In theory.. the add-on SHOULD just pick up anything... Hyperion as a example just displays what is sent.
I will try and explain as best I can... previously, if I hit pause.. a menu would appear on screen which didn't effect the lights at the back. Now, when I hit pause the menu appears and the lights change to effect. This is a good thing. 
This only works though if a video file is playing.

**Comment by koying** [comment]
> Hyperion as a example just displays what is sent

I don't know hyperion specifically, but the addons pull from SPMC/Kodi, it's not pushed to them, so up to them, really...

**Comment by ziggy73701** [comment]
Ok cool.... 
As I said, the fix you put in is tested with x254 and works a treat so thank you!

Ill play around with other settings.
