### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by Gauduchon** [koying/SPMC#72]
Hi Koying, 
I have just noticed that when playing a video,pressing the back button does not stop the video as it did in previous versions, all other aspects of the back button work fine. This was on a Fire TV.

**Comment by koying** [comment]
Righty right. I didn't notice because I'm using a custom keyboard map.
Will map back on stop, and longpress-back on fullscreen toggle.

**Comment by Gauduchon** [comment]
Many thanks Chris, will that be an update I have to do or will it update automatically ?

**Comment by koying** [comment]
Manually.
I'll have a google play version, but it'll have a different versioning scheme so as to not interfere with manual versions.
The GPlay one will be paying, though, in a "donate" fashion. Functionalities will be exactly the same.

**Comment by Gauduchon** [comment]
I don't have access to the google play store, will I be able to download from your web site ?
Happy to donate 👍

**Comment by koying** [comment]
Sure. Same APK's will be at both places.

**Comment by Gauduchon** [comment]
Great, thanks 👍 if you can give me a shout when it's done and I will hit that donate button 😀

**Comment by koying** [comment]
Fixed in 16.1.1

**Comment by Gauduchon** [comment]
You are a star 👍👍
