### ISSUE TITLE
Kicks you out with 16.5 on the new Nvidia Shield Update 

### ISSUE THREAD

**Issue by s2law** [koying/SPMC#720]
Confirmed with 4 users, all since the update the app kicks you out and crashes after a few seconds.

**Comment by freddysmith1** [comment]
try a reinstall?  ive had the 5.0 build for the shield for over 3 weeks and haven't experienced any problems with version 16.5.5

**Comment by s2law** [comment]
I've had the new shield for a week with no issues. Now neither Kodi or spmc
will stay open following today's update from nvidia to incorporate the
older devices.

**Comment by s2law** [comment]
All seems OK on Kodi 17, SPMC however is kicking me out every time. Confirmed with 4 other users too.

**Comment by s2law** [comment]
https://www.dropbox.com/s/4nhg8gf5jadxz8u/spmc.log?dl=0 here's my log file

**Comment by koying** [comment]
```
18:44:33.456 T:18446744071807416608  NOTICE: 1Channel: Service: starting...
````

Then there seems to be a normal exit, like if this script just emit a close.

```
18:44:33.507 T:1537009952  NOTICE: Storing total System Uptime
18:44:33.507 T:1537009952  NOTICE: Saving settings
18:44:33.519 T:1537009952  NOTICE: stop all
```

There are so many wizard scripts and things on your setup...

Try a stock install and report back if it still closes...

**Comment by s2law** [comment]
There's only 1 wizard and that wasn't run. This was literally just opening
it, didn't touch anything else as it crashed straight away. It's been fine
with the same setup for a year

**Comment by ziggy73701** [comment]
Updated Shield this morning, SPMC 16.5 seems to run exactly same. No kick outs or errors.

**Comment by koying** [comment]
> that wasn't run

Hehe.. Have a look at your log to see the number of addons and whatnot starting.

As I said:
1) There is no crash. "Something" is just closing SPMC
2) Reproduce with a clean install or it's just addon garbage as far as I'm concerned

**Comment by zspeciman** [comment]
Updated the 2015 shield an hour ago, no problems exiting spmc 16.5.5 64bit version.
I recall that in my spmc 16.5.1 32bit I could never exit spmc the power/exit way.  But in 16.5.5 64bit I can.

**Comment by ronniehd** [comment]
Hello i see this post and btw sorry if you find it off topic but i would like to know which version is the correct/recommended one for Shield TV (mine is 2015 with very recent 5.0.2 upgrade) so i can try to replicate this and test the beta version. 
Thank you in advance!

**Comment by s2law** [comment]
Found the issue, isolated to one addon. Can I just say whilst I'm here,  what an amazing job you do mate. Really appreciate you talking yo the mantle when Kodi have dropped the ball.

**Comment by s2law** [comment]
Use the latest version 16.5-5
