### ISSUE TITLE
Change framerate has no function - Evolve

### ISSUE THREAD

**Issue by 530330** [koying/SPMC#729]
Evolveo Android box H8,
 AArch64 rev4,
 Android 6.01 API 23,
 graphic - Mali T820 (ARM) OpenGL ES 3.2 rev1

Native players for Android perfectly change FPS of TV according to FPS of film.F.e. MXPlayer, Video player Evolveo and more, but with SPMC nothing, FPS stays as GUI.
My log is
`http://paste.semperpax.com/pqqynxfcp`

**Comment by koying** [comment]
Amlogic + API 23 = No refresh rate switch but on latest amlogic firmwares
You have to pray that "Evolveo" does firmware follow-up...

**Comment by 530330** [comment]
Strange, no refresh rate switch on firmware and every amateur player go very well, only Kodi, SPMC and FTMC no.
