### ISSUE TITLE
Displaying only a fourth of 4k videos

### ISSUE THREAD

**Issue by tchirou** [koying/SPMC#73]
Hello
Many thanks for all your work Koying
Nvidia shield tv with android 6.0 with 4K 60hz resolution
Spmc 16.1
I have set the GUI resolution limit on unlimited and restarted
The system info indicates a screen resolution of 3840x2160 60hz
When I launch a 4K video only a quarter of the video is displayed, the up right corner.
The debug log is here : http://spmclogs.semperpax.com/pwqetj1ij
Test with je si ca jo nes 2160p

**Comment by koying** [comment]
Fixed in 16.1.1

**Comment by tchirou** [comment]
Many thanks

Le 13 mars 2016 à 21:04, Chris Browet notifications@github.com a écrit :

Fixed in 16.1.1
