### ISSUE TITLE
16.5.81 shown as a 16.5.80 under Android TV !!

### ISSUE THREAD

**Issue by LePouSAT** [koying/SPMC#732]
Is it just a display problem or is it a 16.5.80 ?

Thanks for the reply !!

**Comment by sammarbella** [comment]
It's 16.5.81 if you installed 16.5.81.

Take a look at the date: **16.5.81** shows as "16.5.80 GIT **2017-1-29**...." in SPMC<Settings<System Info.

It's not a big deal if you know what version you installed. :D 

If you are in doubt just install it again on top, these TEST versions builds will use the same folder different than normal builds.

**Comment by koying** [comment]
It's purely cosmetic
