### ISSUE TITLE
No Passthrough audio with latest update

### ISSUE THREAD

**Issue by gazzer82** [koying/SPMC#733]
So I seem to have lost passthrough again in SPMC after he last update by Nvidia.

I have never been able to get passthrough to work from Plex on my shield as the EDID of my display doesn't specify that it can handle DD.

But setting IEC Passthrough on and disabling Medicodec (Surface) has always in the past allowed the DD to pass, and DTS transcoded to DD to pass.

But now, no configuration of Passthrough works, I just get silence. If I disable it then as predicted i get stereo only.

I would very happily buy a USB-Optical adaptor so I can make this work, but the Turtle Beach one is not available here in the UK, anyone aware of any other devices that will work correctly?

Let me know if you want a Logcat or Kodi log file and I will extract them when I get home.

I suspect this might be a wider issue, as their seems to be people having passthrough issues on the Kodi/XDA Forums.

HDR seems to work fine, Rec2020.

Cheers

Gareth

**Comment by gazzer82** [comment]
Ok so some slightly more detailed info as I'm sure that will be needed.

I have my Shield connected to my TV using HDMI 2.0.

On the separate ARC output of my TV is connected a HDMI to Optical audio de-embeder that extracts the audio and send it optically to my sound bar.

Previous to the updated this worked as long as the following settings where set (all other settings as per the recommended settings for SPMC)

- Mediacodec (Surface) disabled

- Audio output device IEC Passthrough

- Channel Count 2.0

- Dolby Digital Passthrough Enabled

- DD Transcode enabled

- All other formats disabled

However now, passthrough does not work in any configuration I have tried.

If I set the audio output device to Raw Passthrough, I will get stereo audio when playing back a video filed with a DTS track, but silence with anything with a DD track.

If I set the audio output device to IEC Passthrough, I get silence on anything with a DTS or DD track.

That is with my settings or with the recommended SPMC settings.

Below are SPMC debug logs, and a Logcat from the shield.

First run - My settings as specified about, IEC Passthrough e.t.c, first playing a DD file (Cloverfield Lane), then a DTS one (Amelie).

Log Custom Config - http://paste.semperpax.com/plpa1wbup
Logcat Custom Config - http://paste.semperpax.com/pv6um0llx

Second run - The recommended SPMC settings, first playing a DD file (Cloverfield Lane), then a DTS one (Amelie).

Log SPMC Config - http://paste.semperpax.com/pgb9hxabj
Logcat SPMC Config - http://paste.semperpax.com/pluztn5pt

I'm aware I have posted about this issue previously and have never mad much feedback/assistance from people, so I'm wondefing if I am not providing the correct information, or in the wrong format?? Do let me know if this is the case I am very happy to put some legwork into helping fix this.

Cheers

Gareth

**Comment by wrxtasy** [comment]
Simple questions here have you...

1) Turned off "Sync Playback to Display" ?
2) If SPMC/Kodi refresh switching is enabled, do you have a delay set of at least 2.5seconds set before video playback begins ?

**Comment by gazzer82** [comment]
Yes and yes. Have tried with display rate switching enabled and disabled and it made no difference. 

I am aware that some of my issues come from my EDID not specifying Itself as DD compatible. But previously selecting IEC passthrough would somehow bypass the shields check for this and allow the stream to be passed anyway. This doesn't seem to be the case any more. 

I did replug my system via an old audio de-embeder that had the correct EDID and that did work as expected. But as I need HDMI 2.0a for the HDR for my system currently I'm stuck with either DD or HDR/4K, which is very dull. 

I guess this is an OS level change and their isn't going to be anything you guys can do about it?

Anyone come across a HDMI 2.0a capable EDID manager or audio de-embedder?

Cheers

Gareth

**Comment by lammerz** [comment]
I've just hit a similar problem. Everything was fine before the NV update. SPMC no longer passes through audio for surround codecs, whereas prior to the update it handled the regulars, HD and atmos perfectly.

The interesting thing is the built in video player does do pass-through (at least the DTS, DD lights come on on the receiver), which seems to rule out OS level changes confusing the hardware.

I'm still experimenting. Perhaps I can find a common factor...

**Comment by bramvanderhaeghe** [comment]
I have exactly the same problem.
SPMC as well as Kodi 17 stopped passing through surround _after_ the update to Shield Experience 5.0.2.

I noticed there are some new audio settings in Shield / Android TV.
In Settings > Display and sound > Advanced settings, you'll find a setting for 'surround' and 'HDMI 5.1 audio'.
Guess something changed in how Android TV handles surround audio?

**Comment by lammerz** [comment]
Okay, I have more info; SPMC will do pass-though once the video is playing. I've tested with DD, DTS, MA and Atmos.

When the video silently starts playing:

- bring up the options thingy at the bottom of the screen and go into audio
- deselect "Enable passthrough"
- wait for downsample/pcm (whatever it is) audio to come through
- select "Enable passthrough"

After the receiver stops clicking and flashing the hdmi light, you should see the proper audio stream light come on.

**Comment by Karkas66** [comment]
I think this is an old issue, already discussed in the Kodi Forum - Shield Tread: http://forum.kodi.tv/showthread.php?tid=304226

Try this workaround:

_There is an issue if you have frame rate switching and audio pass-through enabled which may cause stuttering or lose of audio. If you encounter this set the playback delay in Kodi/SPMC to 2.5 seconds.

In Kodi go to - Settings > System > Display > Delay after change of refresh rate
In SPMC go to - Settings > Video > Playback > Pause during refresh rate change_

**Comment by lammerz** [comment]
> In SPMC go to - Settings > Video > Playback > Pause during refresh rate change_

Thanks! 2.5 seconds didn't help, but 4s did. Audio pass-through now functions properly.

**Comment by gazzer82** [comment]
Ok so some progress on this. I have purchased a cheap USB audio interface as the ARC nonsense is clearly not working. And I have DD back, yay!

However, I still cannot get DTS working.

Here is a Kodi log of a DTS file being played with the standard settings as recommended by SPMC, which doesn't give me an option for Transcoding to AC3, I can see a line in the log file indicating that passthrough is not enabled when DTS is played

http://paste.semperpax.com/py2cirred

Specific line is - NOTICE: Creating audio stream (codec id: 86020, channels: 6, sample rate: 48000, no pass-through)

Which I guess makes sense as I'm saying I can't do DTS, so it's not playing it, but I assumed it would transcode to AC3.

So, I also then tried setting the channel count to 2.0, which does give me the "Enable Dolby Digital (AC3) transcoding, however then on DTS I get notice but silence, here is the log file for that.

http://paste.semperpax.com/phvthjzq4

And I still seem to have the same No Passthrough 

NOTICE: Creating audio stream (codec id: 86020, channels: 6, sample rate: 48000, no pass-through)

Anyone got any ideas what's going on, I assume as files with an actual DD track passthrough fine, then DTS transcoded to DD should also?

Thanks

Gareth

**Comment by gazzer82** [comment]
And here is a logcat from the silent DTS play, seems to be some audio issues in their, not that they mean much to me.

```
02-03 19:46:54.753   292  4290 W APM_AudioPolicyManager: getOutput() could not find output for stream 3, samplingRate 48000,format 218103808, channels 3, flags 1
02-03 19:46:54.755  7399  7429 E AudioTrack: Could not get audio output for session 641, stream type -1, usage 1, sample rate 48000, format 0xd000000, channel mask 0x3, flags 0x1
02-03 19:46:54.756  7399  7429 E AudioTrack-JNI: Error -22 initializing AudioTrack
02-03 19:46:54.756  7399  7429 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
02-03 19:46:54.761   292  4289 I NvAudioPolicyManager: getOutputForAttr() device 0x4000, samplingRate 48000, format d000000, channelMask 3, flags 1
02-03 19:46:54.761   292  4289 W APM_AudioPolicyManager: getOutput() could not find output for stream 3, samplingRate 48000,format 218103808, channels 3, flags 1
02-03 19:46:54.762  7399  7429 E AudioTrack: Could not get audio output for session 649, stream type -1, usage 1, sample rate 48000, format 0xd000000, channel mask 0x3, flags 0x1
02-03 19:46:54.762  7399  7429 E AudioTrack-JNI: Error -22 initializing AudioTrack
02-03 19:46:54.762  7399  7429 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
```

http://paste.semperpax.com/pmjq24p92

**Comment by Yomark1** [comment]
I also have this problem with an Onkyo 656 since the latest Nvidia update. If I start a video en then disable passthrough and enable it again, it's starts working immediately.

**Comment by gazzer82** [comment]
@Yomark1 - What settings are you using?

**Comment by gazzer82** [comment]
No that doesn't work for me, if I disable passthrough then I get an stereo audio signal, if I then re-enable it then I get silence again.

This is with the channel count set to 2.0 and AC3 transcoding enabled as per previous post.

**Comment by Yomark1** [comment]
The pause during refresh rate switching does also kinda works for me, but there seems to be a bug with it. (SPMC 16.5)
I've set it to 13 seconds now, but in reality it waits/pauses only 4-5 seconds the first time I play a video(DTS passthrough works fine then) but the second time I start the same video it does not pause at all and there is also no sound.
Can other confirm this behavior?

**Comment by lammerz** [comment]
Yomark1, I've tried to replicate your issue by repeatedly selecting the same videos (not just those with DTS). Most of the time it works as expected, and the audio passes through. I did experience a few problems with freezing where playback would barf after a few seconds. I guess the unit doesn't like a constant start-stop testing.

**Comment by Yomark1** [comment]
https://github.com/koying/SPMC/issues/725 : here some people experience similar issues. @iamerz tnx for checking it for me, seems related to my hardware setup it seems.
Today the passthrough works most of the times with the delay set. So it's better then nothing.

**Comment by gazzer82** [comment]
Ok none of this seems related to the DTS passthrough issue I am now seeing. I have tried it with display rate switching completely disabled and it makes no difference. DD passthrough works perfectly, DTS is either stereo if set to 7.1 output with DTS passthrough disabled, or silence is set to 2 channels with AC3 transcode enabled and DTS passthrough disabled.

**Comment by Yomark1** [comment]
Did you try the latest beta build? There are some  IEC fixes for 5.x in there.

**Comment by bramvanderhaeghe** [comment]
Apparently it's a problem in the Shields audio drivers. Here's an nVidia support guy confirming it: https://forums.geforce.com/default/topic/990134/shield-experience-upgrade-5-0-2-feedback-thread-for-shield-2015-/?offset=473#5070114

**Comment by gazzer82** [comment]
I'll give the latest Beta a go, hadn't spotted that!

As for it being a known issue, given that AC3 when coming from a video with an AC3 track works fine and it's only DTS being transcoded that causes the issue it would seems unlikely to me to be an OS level issue?

**Comment by Vispen74** [comment]
On Sony Android-TV the pass through works well, at least on 16.5.81, beta 2.

**Comment by gazzer82** [comment]
Have just checked the Beta build and the issue persists, but with the Beta build I get no audio at all for IEC Passthrough, RAW Passthrough works, but I get intermittent audio dropout.

**Comment by gazzer82** [comment]
Going to close this and open a new issue as I now have a new issue.
