### ISSUE TITLE
SPMC/xbmc/video/PlayerController.cpp Bug and Fix

### ISSUE THREAD

**Issue by drthaipham** [koying/SPMC#737]
two small bugs in the above file with respect to pixel aspect ratio change. I am sorry if this
is not the protocol to submit bugs. It seems too small for a pull request.

**line 255:**
CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomZoomAmount = 2.f;
should be:
CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomPixelRatio = 2.f;
                                                                                        
**line 265:**
if (CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomZoomAmount < 0.5f)
should be:
if (CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomPixelRatio < 0.5f)
                                                                                       
In adjusting pixel ratio, the actions are attempting to clamp the pixel ratio to between 
0.5 - 2.0. But the actions are using the wrong variable.

The situation arises when  I attempted to write a script to stretch the playing video to a
custom ratio. As there are no PARReset action, I thought I can just use PARdecrease to
bring it down to 0.5 then increase the PixelAspectRatio to the value I want.
That is not possible with the current code.

**Comment by koying** [comment]
Yep, obvious c/p monster. Thanks
Fixed in https://github.com/koying/SPMC/commit/56617c87e041f3316da2ee7131a844e393656d42
