### ISSUE TITLE
Audio drop out after Nvidia Shield TV (2015) 5.0 firmware update

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#738]
After updating my Shield TV to version 5.0(24.28.401.110), my SPMC 16.5.5 gets intermittent audio dropouts that last for 2-3 seconds?

The audio will be mute for 2-3 seconds and then resume, but not where it left off?

**Comment by stabu** [comment]
I lose audio sometimes after I played a file back to back. Have to restart smpc to get it to work again

**Comment by ghost** [comment]
Okay, this isn't an SPMC issue, it happened to me watching YouTube as well.  It's an issue with the Nvidia Shield TV
