### ISSUE TITLE
SPMC freeze on exit, Android-TV

### ISSUE THREAD

**Issue by Vispen74** [koying/SPMC#739]
Press exit within SPMC makes the app freeze. Only way to exit the app is to kill it from settings > apps > force to close. 
Using a Sony TV with Android TV 5.1 running. 
[spmc_log.txt](https://github.com/koying/SPMC/files/752213/spmc_log.txt)

**Comment by JFG90** [comment]
What version you using? I'm not getting this issue

**Comment by Vispen74** [comment]
I tried 16.5.5 and 16.5.81.

It deems to be related to scanning libraries or get media information, because the problem starts when adding sources to libraries on a fresh install. It will Exit, but takes several minutes. Without any sources in libraries it takes just a sec.

**Comment by Vispen74** [comment]
Yesterday it hadn't shut down in 9 hrs. Today the same thing on exit, 8 hrs later after press exit still freezing.

**Comment by Vispen74** [comment]
I solved it; the freeze was because I had a rar-file in the music library, it made the music album scraper to freeze the entire SPMC.
