### ISSUE TITLE
Need to re-toggle audio passthrough every time.

### ISSUE THREAD

**Issue by narlie89** [koying/SPMC#743]
I have an issue with audio passthrough, i'm not sure if it's a bug in SPMC or my reciever.

I'm using the settings from the audio passthrough guide but when i'm playing a movie there's no sound. If I then uncheck the audio passthrough option (inside the player) the reciever recognizes this as PCM and I get sound again. If I then check the audio passthrough option again the reciever recognizes the correct format (DTS for example) and it works until I go back to the main menu where it switches over to PCM again. 

Does anyone have a clue what might cause this? It's like the reciever doesn't recognizes the switch the first time and I have to retoggle it.

**Comment by djtoby1979** [comment]
I just decided to install spmc onto my shield Tv as everyone says it's much better. And I am having the same problem as you. Hopefully someone can help us out

**Comment by djtoby1979** [comment]
I think this is an old issue, already discussed in the Kodi Forum - Shield Tread: http://forum.kodi.tv/showthread.php?tid=304226

Try this workaround:

_There is an issue if you have frame rate switching and audio pass-through enabled which may cause stuttering or lose of audio. If you encounter this set the playback delay in Kodi/SPMC to 2.5 seconds.

In Kodi go to - Settings > System > Display > Delay after change of refresh rate
In SPMC go to - Settings > Video > Playback > Pause during refresh rate change_
@lammerz
lammerz 
commented 3 days ago
In SPMC go to - Settings > Video > Playback > Pause during refresh rate change_
Thanks! 2.5 seconds didn't help, but 4s did. Audio pass-through now functions properly.

**Comment by narlie89** [comment]
Cheers djtoby1079! 4 second delay worked for me too!

Thank you!

**Comment by rfgamaral** [comment]
Should this issue or some other similar remain opened since the solutions are actually workarounds and the problem is not actually fixed? Just a thought...

**Comment by koying** [comment]
"Pause during refresh rate change" is the actual solution, there are no other.

**Comment by rfgamaral** [comment]
@koying So that's why I always had pass-through working and a few days ago it stopped working because I removed the delay during refresh rate change (cause I though it was unnecessary and didn't remember why it was set to 2 seconds). Didn't know that.

However, it feels weird that some users need 2.5s, others 3s or 4s...

**Comment by koying** [comment]
It all depends on your h/w setup. Some devices (TV and/or AVR) "come back" faster than others...

**Comment by lammerz** [comment]
But it wasn't needed until the latest NV update, and my hardware hasn't changed. NV changed something and it has caused this issue regardless of whether it was an issue in the past too.  I'm seeing people asking the same pass-through questions elsewhere, and in each case it's after the 5.0.2 update.  Perhaps they've screwed up some driver code?

**Comment by koying** [comment]
I *always* had a delay set, if anything to avoid the movie going on while the TV is still showing a black screen, so cannot comment whether it was needed for PT before or not.
