### ISSUE TITLE
I get a SPMC has crashed Notification everytime I close SPMC on Nexus Player

### ISSUE THREAD

**Issue by Wordstar1981** [koying/SPMC#747]
Hi Koying, 

Ive been using my Nexus Player again for a couple of Weeks now and i have this problem that everytime i close SPMC i get a Android Message that SPMC has crashed. Im on the newest Version of Nexus Player and it makes no difference what SPMC Version i use. Ive tried the finals and the betas but i always get this crash when i close the programm. 

Edit: Sunday 12 Feb 2017 

Since the issue has occured again i have provided the log files in here:

[spmc.txt](https://github.com/koying/SPMC/files/769249/spmc.txt)

[spmc.old.txt](https://github.com/koying/SPMC/files/769250/spmc.old.txt)

**Comment by ronniehd** [comment]
Hello, you should provide debug log but your problem may be related to an addon, usually "3rth party addon". Make a backup of your setuop, the whole .SPMC folder (its hidden) and then try just adding the library databases and the default addons that automatically install, what something then normally exit the app and see if it keeps crashing. 
With the debug log you can find the addon or the reason why SPMC crash.

**Comment by agoMiST** [comment]
I'm getting the same issue on the Shield TV, this includes a fresh install after a factory reset. I think I've narrowed it down to Super Favourites. Disabling SF seems to get rid of the crash upon exit pop up.

[spmc.old.log.txt](https://github.com/koying/SPMC/files/768732/spmc.old.log.txt)

[spmc.log.txt](https://github.com/koying/SPMC/files/768734/spmc.log.txt)

The attached logs are a successful exit and a crash upon exit (uploaded here manually as the log uploader in spmc isn't working for me)

**Comment by agoMiST** [comment]
It continued to crash even after both disabling and uninstalling Super Favourites.

So...I factory reset again. Updated all preinstalled Shield apps and then installed SPMC fresh with minimal bloat: adjusted settings to my usual preferences, minimal addons (screensaver, weather, movie scraper, Trakt and Next Aired) and added sources (but didn't scan anything in)...and the crash still occurs; although it isn't necessarily everytime I exit, it's still often enough to be irritating.

Here's another log, this time I remembered to switch debug logging on ;o)

[spmc.log.txt](https://github.com/koying/SPMC/files/768789/spmc.log.txt)

**Comment by Wordstar1981** [comment]
The Crashes on close have nothing to do with extra addons since i dont use any addons with spmc i only stream from my NAS and use the standard spmc... I will try to replicate the crashes and upload a log theese days but it doesnt happen all the time. There are more threads with this problem.

**Comment by Wordstar1981** [comment]
Since the issue has occured again i have provided the log files in here:

[spmc.txt](https://github.com/koying/SPMC/files/769249/spmc.txt)

[spmc.old.txt](https://github.com/koying/SPMC/files/769250/spmc.old.txt)

**Comment by Wordstar1981** [comment]
Ill leave a push here for Koying.

**Comment by Wordstar1981** [comment]
Maybe the crash has something to do with playback hapening before the close of the app. Because it seems like it doesnt happen if i just enter spmc without doing anything and then leaving.

**Comment by Wordstar1981** [comment]
Newest Version fixed the issue... Thanks Koying
