### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by paul111111** [koying/SPMC#758]
Why are the downloads so slow and also getting Failed - Forbidden, and failed network error? I have a 70 meg connection .

**Comment by koying** [comment]
Download of what?

**Comment by paul111111** [comment]
trying to download the SPMC builds.

**Comment by koying** [comment]
And from where?

**Comment by paul111111** [comment]
from this site

**Comment by koying** [comment]
Then ask github. I'm just using their service.
