### ISSUE TITLE
nVidia Shield - Passthrough not working with Television anymore

### ISSUE THREAD

**Issue by Wordstar1981** [koying/SPMC#76]
Hi Koying,
Eversince the Kodi Passthrough test releases i bumped into an issue wich prevented me from using theese releases and now the same with SPMC.

I am using an nvidia Shield with a LG 47LM660 TV... Between those two i have a Yamaha RX-V475 5.1 AMP. Everything is one HDMI Chain - Shield ->Yamaha Amp->LG TV

In all the official Kodi releases i have passthrough enabled for Dolby Digital and DTS and get sound from the Television. When i turn on my amp the sound switches from tv to the amp and i get proper DD and DTS passthough with the logos lighting up on the amp. And when i leave the amp of my tv has no problem putting out the passthough and i get proper sound.

With all the passthrough versions and SPMC i dont get any sound from the tv as soon as i activate the passthrough options of DD or DTS. My Amp has no problem putting out the sound as above. Just my tv does not take the signal of your Kodi versions. Note that i am not even talking about HD sound formats. Just using the normal DD and DTS results in my tv putting nothing out.

Since i often use Kodi without turning my 5.1 amp on since my kids dont nessesarily need 5.1 Audio it would be awesome to get the sound out of my tv again. Like i said all normal kodi versions never had issues. Even youre V17 test builds didnt have the issue.

If you need a debug log i can look into getting you one even though i dont think kodi reports anything about it. Must be my tv not liking something about the DD and DTS signal.

Thank you very much for all help and work.

**Comment by koying** [comment]
Well, my guess is that your AVR just doesn't do PT while off.
In plain Kodi, PT is not real PT: It's PCM (=normal sound, WAV), pre-encoded (IEC). It relies on the AVR (or your TV) to "guess" it's PT and decoding it. If it doesn't, you get the well known "screeching" sound.

Anyway, I'll add a setting to use "PCM" mode for use cases like yours.

**Comment by Wordstar1981** [comment]
Ok i sort of get what your saying. But if you say normal Kodis PT is not real PT howcome my reciever shows prober Dolby Digital Logo and DTS Logos? Are you saying that my AVR recognizes the PCM Passthrough as DD and DTS? 

Eitherway that would be so awesome if you can make that option for the normal Kodi method. Thank you so much :-*

**Comment by koying** [comment]
> Are you saying that my AVR recognizes the PCM Passthrough as DD and DTS?

Yep, exactly

**Comment by Wordstar1981** [comment]
ok.. then this either makes it a smart avr or a dumb avr :-D 
Regardless i thank you for impementing the standard kodi passthrough in your future builds...
Your the best!

**Comment by Wordstar1981** [comment]
Will you make a nightly for this feature? Or will it take for a bigger release?

**Comment by koying** [comment]
I hope to be able to do weekly releases, if applicable

**Comment by koying** [comment]
Should be fixed in 16.1.2.
You'll be able to choose the kind of passthrough by selecting a different passthrough device.
Test and check which one works for you
