### ISSUE TITLE
Some flv/wmp movies not playing in SPMC

### ISSUE THREAD

**Issue by nexusV2** [koying/SPMC#770]
Hello. I recognised that some single flv/wmp movies are not playing in spmc (16.5.5/AndroidTV 5.1), although they do in VLC Player.
Is there a way to expand the videocodec base for SPMC, or might it have other reasons?

**Comment by koying** [comment]
Sample, please

**Comment by nexusV2** [comment]
This are not the kind of movies I like to share ;-) but thank you for trying to help!
