### ISSUE TITLE
16.5.5 Can't Pause video, go to ATV Home screen, and return to paused video

### ISSUE THREAD

**Issue by SaxonRix** [koying/SPMC#774]
I'm using Nvidia Shield TV V1. 

In previous versions of SPMC I was able to pause playback of a video, go to the Android TV Home screen to do something (usually enable 'twilight' for night time viewing), and then return back to SPMC and continue watching. 

However now when I come back into SPMC the video is no longer loaded and I have to select it again.

**Comment by Gertbucket** [comment]
I wouldn't consider this a particularly big deal, but I notice Kodi 17 does the same thing. Meanwhile, MrMC recommences play if you pause, hit home, then return to the app.

**Comment by SaxonRix** [comment]
16.6.0 seems to fix this with the new background play feature.
