### ISSUE TITLE
[Feature Request] Context Features/Launcher

### ISSUE THREAD

**Issue by ErAzOr2k** [koying/SPMC#78]
Hi,

I already posted it in the thread in kodie forum. But I think here is a better place:

Is it possible to add these features?
-Add possible to stop running (Android) App by context menu when selecting specific App 
-Add Possible to uninstall/delete (Android) Apps by context menu
-Possibility to run SPMC as launcher

**Comment by koying** [comment]
Launcher is on the TODO.
You other requests requires the app to be a system one, I think, so not possible.
