### ISSUE TITLE
CANT INSTALL SPMC ON MY DONGEL MINI TV ANDROID 4.4

### ISSUE THREAD

**Issue by zydns** [koying/SPMC#781]
hi
can you help me please?i have dongel mini tv that have android 4.4 and i cant install spmc 16.5.0 and up
in app store i find only  the old version 14 .
can someone tell me how can i install the new version?

**Comment by koying** [comment]
See http://spmc.semperpax.com/

> Note 1: As of 16.5.0, Android lollipop (API 21) is required

**Comment by zydns** [comment]
so what the last version that i can install on my dongel and it is working?
