### ISSUE TITLE
Why can Shield close running SPMC after I have quit SPMC?

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#792]
I don't know whether this is a Shield or SPMC/Kodi problem... and this is also an issue with Kodi 17....

I have a shortcut to quit SPMC/Kodi on my main menu. This invokes <action>Quit</action> which I believe should kill the SPMC/Kodi program, not just minimize it.

With Shield Experience 5.x, you can now see running programs and manually close them by pressing menu twice. And I still see SPMC running and can close it manually even though I previously used the quit command.

**Comment by koying** [comment]
Yeah, a bit of a mystery. Always been, though, and not sure what the remnants are, probably some java stuff.
The actual SPMC/Kodi is gone, though. IIRC, if you "recall" SPMC from the task list, you'll see that it actually restart from scratch

**Comment by JFG90** [comment]
I've also noticed this along with settings running when if i open the task manager on start up, been having some Pixelation and picture breaking up every now and then on live streams, and i believe the settings running in the background was causing it as after closing it on start up then loading a live stream on spmc i no longer get it anymore or at least haven't been so far I've noticed.
