### ISSUE TITLE
DTS-HD

### ISSUE THREAD

**Issue by il2510** [koying/SPMC#805]
hi
i have nvidia shield 2017 with spmc 16.5.5
the nvidia shield connected to the reciver via hdmi
i setup  the sound menue on spmc as recomended here.
when i play a file with dts-hd format i hear the sound well but when i pause the playing i got  some kind of distortion noise that stop only when i stop playing the file, so i  cant pause it and keep play.
how can i fix it?

thanks

**Comment by classicjazz** [comment]
Try installing 16.6 and using the recommended IEC audio settings.

**Comment by il2510** [comment]
i upgrade to 16.6 and its all fine now.
thanks  a lot for your help
