### ISSUE TITLE
SPMC autolaunch Internet issue

### ISSUE THREAD

**Issue by Grencola** [koying/SPMC#825]
Found a bug where on a fresh boot of android, with no other apps in the background, if you autolaunch SPMC It won't snag an IP address until you go to android via either quitting and reloading spmc, launching an app, or simply just alt-tabbing to the recent apps screen and quickly returning back to spmc - even a 1 second flick without the app restsrting. Literally anything outside of SPMC  will quickly trigger Android to grab an IP.  Found this bug on both with wifi and ethernet, and tested it on multiple AML boxes and achieved the same result. Tried using both spmc-launcher.apk and spmc from the Playstore with xbmclauncher. You're just stuck in spmc with no Internet until you do anything outside of the app. 

I recorded it happening, the video is pretty bad, but if you look closely the ip is blank and when I alt tab it instantly gets one and viewing online content can begin.  https://youtu.be/xJ-fo86xVzg

It's just frustrating for if I setup a new box for someone with little knowledge and they plug it in and spmc auto launches they won't have Internet and nothing will load and they won't really know what to do except for hopefully quitting and reloading but usually I don't even put a quit menu on the main screen as it just auto-reloads spmc anyway.

**Comment by timefrancesco** [comment]
+1 
It's happening to me as well.

**Comment by 5l1p** [comment]
Having this problem on my firetv2 too. Using Launcher apk with rbox tools. Bug appears after 16.4.2 Hope it can be fixed!

**Comment by booyakafoo** [comment]
Tried this? 

https://github.com/koying/SPMC/wiki/How-to-wait-for-network-to-be-active-before-starting-SPMC%3F

**Comment by Grencola** [comment]
Thanks, Scott! This is a wonderful fix, it works great :)
