### ISSUE TITLE
Passthrough not working - Shield TV still on Lollipop

### ISSUE THREAD

**Issue by cesarious** [koying/SPMC#83]
Hi Koying, 
       I've installed tonight your latest version: SPMC-armeabi-v7a_16.1.1.apk

Worked as usual for AC3 and DTS, but, for some reason, when enabling passthrough in system/audio options, only appears passthrough DTS and AC3 options. There are no True HD, Dolby+ or DTS HD options available.

In parallel I keep running your old version kodi-20160121-0a9c10f-adddroidPT-armeabi-v7a.apk that, so far, it has been the most stable in my set up, and the one that reproduces every different audio format - file container.

Environment: Nvidia Shield TV (still on lollipop; firmware 2.1), connected through HDMI to a Denon 4308 and HDMI to TV.

Any idea? anything I should try?.

Thanks,
     Cesar.

**Comment by ghost** [comment]
You haven't enabled expert settings and the latest hacked V16 build is this one:

http://mirrors.kodi.tv/test-builds/android/arm/kodi-20160308-b881949-adddroidPT-armeabi-v7a.apk

**Comment by koying** [comment]
Note to self: 
Re-enable RAW passthrough on Shield 2.1.
Way-to-go: Pseudo-passthrough devices for PCM/RAW/IEC

**Comment by cesarious** [comment]
Thanks Koying!, I'll wait for that release!.

**Comment by koying** [comment]
Will be in 16.1.2
