### ISSUE TITLE
Generic issue with Android < 4.4

### ISSUE THREAD

**Issue by wujunran** [koying/SPMC#84]
When I open SPMC 16.1 , It crashed. But SPMC 15.0 and KODI 16.1 is OK.

System info from SPMC:
CPU : ARMV7 Processor rev1(V7I)
GPU : Mail-450MP
System : Android 4.3.0 API Level18 (kernel:linux 3.1.10)
OpenGL vendor : ARM
OpenGl version :OpenGL ES2.0

**Comment by koying** [comment]
Note to self:
Issue with < 4.4 ?

**Comment by koying** [comment]
http://spmclogs.semperpax.com/pjei98dzz

**Comment by koying** [comment]
Please test http://download.semperpax.com/spmc/android-arm/SPMC-20160317-29f5ca3-fix_document_api17-armeabi-v7a.apk

**Comment by pjg-pigeon** [comment]
Success . the app has started. You're the man ☺

Will let you know if anything else shows up.

Cheers

Pete

**Comment by mjbxx** [comment]
I can confirm that this test SPMC APK does indeed fully launch on a rooted Fire TV with OS 3. Will test further tomorrow. Thanks for this. But what I and many other users really want is the vaunted and popular SPMC Launcher that functioned extremely well in the past. We know it will be showing up soon. Thanks again!

**Comment by khimmy17** [comment]
pls help..black screen after the loading screen..
