### ISSUE TITLE
Passthrough not working on 16.6 with Shield 5.1

### ISSUE THREAD

**Issue by giladgaron** [koying/SPMC#840]
After upgrading to version 16.6 and following the instructions in the wiki (https://github.com/koying/SPMC/wiki/Recommended-passthrough-audio-settings-for-SPMC,-NVIDIA-Shield-TV-and-AV-Receivers), Passthrough is not working.
I cannot output DTS. DD, DTS HD and DD HD.

I've tried uninstalling SPMC and installing it from scratch but that didn't help.
To note, I also have Kodi 17 installed on my shield and with Kodi the passthrough works with all formats

Any ideas?

**Comment by RobertoKodi** [comment]
check audio pass through settings if you have it set to "IEC"or raw .. probably on IEC , if so change it to RAW

**Comment by giladgaron** [comment]
Thanks,
I've tried both IEC and RAW, same effect

**Comment by cesarious** [comment]
Check Android RAW Passthrough on the second option on expert sound setting and enable the options supported by your receiver. It still works in my case with v16.6 and Shield Tv on firmware v3.2.

**Comment by giladgaron** [comment]
Thanks, but I had no issues with v3.2

**Comment by audiomixer** [comment]
As per the wiki, IEC is the correct setting.
Updated as of Shield Experience 5.1 and SPMC 16.6

After you have upgraded to Shield Experience 5.1 and SPMC 16.6, you should switch your audio passthrough settings to IEC, as described below. Similarly, we recommend that you adjust your display refresh rate = on start / stop, and pause during refresh change = 3.0 seconds to avoid related passthrough audio issues

**Comment by classicjazz** [comment]
Unlike Kodi 17, RAW still works in SPMC 16.6. But, for the same reasons that Kodi 17 uses IEC exclusively, it is preferable to use IEC with Shield 5.1. 

Since Kodi 17 uses IEC and is working, it would be helpful to backtrace what settings are different between Kodi and SPMC. Also, it would be helpful to know what cabling method: HDMI (and what version) or optical and what AVR brand+firmware you are using.

**Comment by giladgaron** [comment]
I've manged to identify the culprit, it's the auto refresh rate. If I use "on start / stop" the passthrough doesn't work, if I disable it , the passthrough work.
It's also worth mentioning that I've tried adjusting the "pause during refresh rate change" from 0 seconds to 3 seconds (with 0.5 seconds interval) but it doesn't seem to have any effect.
Plus, the refresh rate remains at 60hz even if auto refresh rate is enabled, so it seems broken on my setup

@classicjazz 
My setup:

- TV: Samsung 55F6400 (FHD), Using HDMI port 2 , ver 1.4 (worth mentioning that this port supports ARC while I don't use ARC)
- AVR Denon x1300w , firmware  3600-0916-8022, HDMI 2.0a
- Shield 2015, firmware 5.1

Shield is connected to the AVR via an HDMI 1.4 cable, TV is is connected to the AVR via an HDMI 1.4 cable.

**Comment by giladgaron** [comment]
After a few minutes of investigation, it seems that the Shield is the issue here due to an HDCP 2.2 handshake issue (if I understand correctly) , details are here: https://forums.geforce.com/default/topic/901911/shield-tv/auto-refresh-rate-switching-not-working/12/

Thank you for your help!
