### ISSUE TITLE
SPMC16.6.0, windows (win32) build!!???

### ISSUE THREAD

**Issue by circle-dev** [koying/SPMC#855]
Guys, is there any reason for not having a win32 build release?? Can someone share latest SPMC16.6.0, windows (win32) build?? Thanks

**Comment by sammarbella** [comment]
Win32 16.6.0?

The latest win32 SPMC i can download is 16.5.x Dec 27 build.

I guess Koying is mainly focused on Android versions and specifically in Shield TV SPMC performance and features.

**Comment by circle-dev** [comment]
Hi sammarbella, thanks for your response. I understand SPMC focused on android but i have been running it on windows for a while with no issues. its just that i like the "boost center channel" option on SPMC where it is not available in official kodi.
