### ISSUE TITLE
SPMC and KODI can not be installed to USBDisk at the same time

### ISSUE THREAD

**Issue by bylderup** [koying/SPMC#86]
On firetv1 FW 5.05 (lollipop) SPMC an KODI can not both be installed to USBDISK

**Comment by koying** [comment]
Yep.
(note to self: rename xbmc_env.properties to spmc_env.properties)

**Comment by koying** [comment]
As of 16.1.2, you can add an spmc_env.properties specifically for SPMC.
If one is not found, it will fall back to xbmc_enc.properties, as before

**Comment by fritzboyle** [comment]
I apologize if this is not the right thread, but I am not seeing the issue elsewhere - I am trying to install SPMC for the first time on my Nvidia Shield TV. I currently have Kodi 16 installed. (I was going to install them in parallel to assess your build in comparison). when I try to install from the Google Play store, I get an error (I believe it was 506) saying that it cannot be installed. is this related to this issue? does the installation not work if there is already a xbmc/kodi app installed on the device?
