### ISSUE TITLE
Audiobooks not playing

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#90]
**SPMC 16.1.1 / Nvidia Shield TV (6.1)**

SPMC seems to have trouble playing audio files which are either mono or below 44,100kHz - the problem doesn't exist in Kodi (16.0) so it seems to be SPMC specific

this is the log when playing such files: http://xbmclogs.com/p3pgx7ozo

Following formats I've attempted: 
- MP3 / 22050 Hz / mono / 64 kbps
- MP3 / 22050 Hz / mono / 160 kbps
- AAC / 22050 Hz / mono / 63 kbps

**Comment by koying** [comment]
I'd need samples of those for tests

**Comment by ghost** [comment]
samples: http://ovh.to/Z4egBN3

**Comment by koying** [comment]
Fixed in 16.1.2
