### ISSUE TITLE
Is SPMC vulnerable to this hack? 

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#910]
http://uk.pcmag.com/security-4/89487/news/hackers-can-use-subtitles-to-infect-your-devices

**Comment by sammarbella** [comment]
Aren't two threads with the same subject enough?:

https://github.com/koying/SPMC/issues/905

https://github.com/koying/SPMC/issues/908

**Comment by ghost** [comment]
Sorry, didn't see them.
