### ISSUE TITLE
Crash Alert every Time I start SPMC

### ISSUE THREAD

**Issue by nexusV2** [koying/SPMC#918]
Hello, I´m using SPMC on AndroidTV. My issue is, that every time I start the TV and then SPMC I get this annoying alerts "Well this is emberassing ....." or "SPMC was closed.....OK" and then I have to start SPMC again and everything runs fine and stable until I shut down the TV.
This behaviour first showed up a few month ago.
It would be very kind if you could help.

**Comment by BigOkie** [comment]
How about posting a log?

**Comment by nexusV2** [comment]
Solved. It seems that an USB-stick was responsible, that was not recognised properly after the AndroidTV Marshmallow update anymore. In cause of that, there was an unvalid path to the USB-stick in SMPC.
With attaching a new stick, this issue disappeared.
