### ISSUE TITLE
Very Persistent black screen on spmc

### ISSUE THREAD

**Issue by Parke81** [koying/SPMC#924]
I have a very persistent black screen when opening spmc 16.7.  I have 2 nvidia shields that i just purchased and was hoping to get kodi loaded originally.  However, after i get a build installed, i will get a couple of reboots done, then it will come up with a black screen on the 3rd or 4th reboot.  To try and resolve this issue, i obviously started with clearing the cache, which sometimes works, but it always reappears.  I eventually switched to spmc, and have tried multiple builds, but still get this issue.  I am using the aarch version of spmc 16.7.  I always close spmc using the power/quit button if possible.  This happens on both my brand new shields, so it is unlikely it is a hardware issue.  I don't know where to go from here.  Can anyone help me?

**Comment by Parke81** [comment]
Here is the crash report link-  http://paste.semperpax.com/p5tfdidoh

I have searched through this and many other forums to find a solution.  I even tried installing the rmdroidlauncher, although it appears to be for s different software version, but it fails to install, saying the file is corrupt.

**Comment by BigOkie** [comment]
This looks more related to Android I think given the messages just before the crash.  The Shield always wants to write a driectory to network attached storage to the shield called Android.  It appears you may  have the storage drives set to read only.  I stopped mapping drives using the Shield some time ago and started letting SPMC do that.

06-09 09:20:47.164  3468  6321 W ContextImpl: Failed to ensure /storage/PARKE-PC/SuperComputer/Android/data/com.semperpax.spmc16/files: -1
06-09 09:22:07.194  3468  6321 W ContextImpl: Failed to ensure /storage/PARKE-PC/Users/Android/data/com.semperpax.spmc16/files: -1
06-09 09:23:27.194  3468  6321 W ContextImpl: Failed to ensure /storage/PARKE-PC/Video Games/Android/data/com.semperpax.spmc16/files: -1
06-09 09:24:47.214  3468  6321 W ContextImpl: Failed to ensure /storage/PARKE-PC/TV/Android/data/com.semperpax.spmc16/files: -1
06-09 09:26:07.244  3468  6321 W ContextImpl: Failed to ensure /storage/PARKE-PC/X/Android/data/com.semperpax.spmc16/files: -1

If you have no need for mapping network storage using the Shield OS, I would drop that and use SPMC directly.  If you need to then you need to ensure that the Shield has write access to the share.

**Comment by Parke81** [comment]
Worked like a charm.  I turned off network sharing and it has booted up every time since.  Thank you so much!!
