### ISSUE TITLE
SPMC Krypton v17

### ISSUE THREAD

**Issue by xodidox** [koying/SPMC#925]
Is there any rough release date for SPMC Krypton v17?

**Comment by oOflyeyesOo** [comment]
He has been pushing commits everyday again, can just tell it is getting
closer. He fixed some files to build it, as it probably wasn't compiling right. Could mean super soon.

**Comment by janolapin2016** [comment]
I read everywhere that Jarvis are BETTER than Krypton which is a slut dumbass...
