### ISSUE TITLE
USB write permission

### ISSUE THREAD

**Issue by xodidox** [koying/SPMC#946]
Hi Koying,

@koying Could you add the feature to request the write permission for the whole USB drive at first start for SPMC, just like what the ES File Explorer does? The USB drive write permission in Android 5 and later is a headache. We have to save all data to the /Android/data/com.semperpax.spmc17 folder, which is not easy to organize and also very ugly. Thank you very much!

Kind regards

**Comment by ghost** [comment]
> We have to save all data to the /Android/data/com.semperpax.spmc17 folder, which is not easy to organize and also very ugly.

Maybe [this](https://github.com/koying/SPMC/wiki/How-to-specify-the-location-of-SPMC-data%3F) helps for storing your SPMC data somewhere else?

**Comment by xodidox** [comment]
I'm currently using this, but you still have to save all data to the "/Android/data/com.semperpax.spmc17" folder, this is the only place in the USB drive that SPMC has write permission to.
