### ISSUE TITLE
H.264 MVC (stereoscopic 3D) MKV and MP4 files on Nvidia Tegra

### ISSUE THREAD

**Issue by Hedda** [koying/SPMC#95]
Please try to add hardware accelerated video decoding support for stereoscopic 3D playback of H.264 MVC ("Multiview Video Coding") MKV and MP4 files on the newer Nvidia Tegra SoC/SoCs that support it, (like example the Nvidia Shield TV).

**Comment by koying** [comment]
No MVC decoding on Shield, currently, not sure where you got that impression ;)
Don't worry, as soon as nvidia enables it, it'll be in

**Comment by Maya73** [comment]
I want to buy an android box. I would prefer to choose the Nvidia Shield (then the Q10pro) but it don't play MVC 3D.
Do you think one day Nvidia will be able to play MVC 3D files?

Thanks for your help.
