### ISSUE TITLE
no audio at sport 365 live streams 

### ISSUE THREAD

**Issue by michaelamsterdam** [koying/SPMC#96]
streaming from sport 365 gives video but no audio. problem only occurs under spmc tried clean install and did a survey in ouer xvbmc Facebook group for larger scale testing.

**Comment by koying** [comment]
I'll not do any addon support.

**Comment by michaelamsterdam** [comment]
but it is not ADDON related it seems to have something to do with the audio decoding on some live streams it is not addon related.  it seems to be spmc related

Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Chris Browet notifications@github.com
Datum: 17-03-2016  14:16  (GMT+01:00)
Aan: koying/SPMC SPMC@noreply.github.com
Cc: michaelamsterdam michaelamsterdam@hotmail.com
Onderwerp: Re: [SPMC] no audio at sport 365 live streams  (#96)

I'll not do any addon support.

---

**Comment by koying** [comment]
How do you play "365 live streams", then?
Anyway, I cannot guess anything without a debug log.

**Comment by michaelamsterdam** [comment]
there are several Addons zem tv and awesome streams.  but video plays fine but with a lack of audio I  kodi 16.1 no problem. Kan send you the spmc. log in a while

Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Chris Browet notifications@github.com
Datum: 17-03-2016  14:20  (GMT+01:00)
Aan: koying/SPMC SPMC@noreply.github.com
Cc: michaelamsterdam michaelamsterdam@hotmail.com
Onderwerp: Re: [SPMC] no audio at sport 365 live streams  (#96)

How do you play "365 live streams", then?
Anyway, I cannot guess anything without a debug log.

---

**Comment by spursgalea** [comment]
I have this issue as well.I have a ms8+ android box and some videos work with sound and others dont.the same online videos work on kodi on the ms8+ box and on my Nexus 7 spmc but not on the ms8+ box.i will post a log tomorrow if needed

**Comment by spursgalea** [comment]
I have this issue as well.I have a ms8+ android box and some videos work with sound and others dont.the same online videos work on kodi on the ms8+ box and on my Nexus 7 spmc but not on the ms8+ box.i will post a log tomorrow if needed

**Comment by spursgalea** [comment]
I have this issue as well.I have a ms8+ android box and some videos work with sound and others dont.the same online videos work on kodi on the ms8+ box and on my Nexus 7 spmc but not on the ms8+ box.i will post a log tomorrow if needed

**Comment by spursgalea** [comment]
I have this issue as well.I have a ms8+ android box and some videos work with sound and others dont.the same online videos work on kodi on the ms8+ box and on my Nexus 7 spmc but not on the ms8+ box.i will post a log tomorrow if needed

**Comment by spursgalea** [comment]
I have this issue as well.I have a ms8+ android box and some videos work with sound and others dont.the same online videos work on kodi on the ms8+ box and on my Nexus 7 spmc but not on the ms8+ box.i will post a log tomorrow if needed
