### ISSUE TITLE
[SPMC17] No HDR

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#962]
Bonjour
With SPMC-spmc-krypton-5e3c0fc-armeabi-v7a , there is no HDR ( same as Kodi 18) .
It is necessery to set autoframerate OFF but movies become inlookable because there are a lot of shakes.

On Nvidia Shield

**Comment by CLFNole** [comment]
I am also in the Nvidia Shield and can also confirm the latest release is no longer engaging HDR. The last version of 17.3 (July 3rd release) worked fine though.

**Comment by 99rook99** [comment]
I'm sure that @koying, wants logs with issues, since it works for him imagine or he wouldn't have released it.

**Comment by CLFNole** [comment]
These are "test" builds and Koying is just one person so I highly doubt he is able to test every aspect before release.

**Comment by CLFNole** [comment]
I went back to the previous July 3rd version and it engaged HDR for all 4K HDR movies in various addons but the newest version does not.

**Comment by ziggy73701** [comment]
HDR with NVidia shield working OK for me... ensure 

allow hardware acceleration - Mediacodec (Surface) = on
allow hardware acceleration - Mediacodec = on

**Comment by CLFNole** [comment]
Ziggy you are using the 7/24 release?  My settings are the same as yours and the 7/24 release would not engage HDR but the 7/3 version would.

**Comment by ziggy73701** [comment]
Yeah and just tested again to be sure!

**Comment by CLFNole** [comment]
Reason I asked is because both show up as version 17.4 RC1 when I check system info.

**Comment by CLFNole** [comment]
Thought perhaps you hadn't updated to the one that came out a couple of days ago.

**Comment by JGrana01** [comment]
Thanks Ziggy73701. Running 17.4 RC1 Git20170723-5e3c0f on NVidia Shield 2015
I had Mediacodec (Surface) = off.    No HDR triggered
Set Mediacodec (Surface) to on and also made sure Mediacodec = on.
Good news, HDR triggerd for the known HDR demo videos I played.
Looks good!

**Comment by ghost** [comment]
Hello thanks to Ziggy , CLFNole and JGrana .
Can you tell me if autoframerate is on or off ??
With Git20170723-5e3c0f on NVidia Shield 2015 ,Mediacodec (Surface) = on,Mediacodec = on and autoframe = on => no HDR.
With autoframerate = off , HDR ok but 4K files are very bad and i can't see it.

**Comment by ghost** [comment]
Houppss!!!

**Comment by CLFNole** [comment]
I will have to check the auto frame rate but it looks like Koying will also be testing this since he has it marked now.

**Comment by koying** [comment]
I confirm that HDR works without auto-refresh but is reset if auto-refresh is enabled.
Workaround seem to long-press to exit fullscreen, then re-enter, and HDR pops in for me.

**Comment by CLFNole** [comment]
Appreciate you checking this out.

**Comment by ziggy73701** [comment]
The ability to set a delay on the auto refresh seems to have gone.. if auto refresh is on.. HDR is 50/50 as to if it engages
