### ISSUE TITLE
[SPMC17] Latest build SPMC-spmc-krypton-5e3c0fc-armeabi-v7a crashes when start on Fire TV 2nd gen

### ISSUE THREAD

**Issue by xodidox** [koying/SPMC#963]
Seems samba4 is not present in the system.

E/art     (21960): dlopen("/data/app/com.semperpax.spmc17-1/lib/arm/libspmc.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "state_path" referenced by "libsmbregistry-samba4.so"...

D/AndroidRuntime(21960): Shutting down VM

--------- beginning of crash

E/AndroidRuntime(21960): FATAL EXCEPTION: main

E/AndroidRuntime(21960): Process: com.semperpax.spmc17, PID: 21960

E/AndroidRuntime(21960): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "state_path" referenced by "libsmbregistry-samba4.so"...

E/AndroidRuntime(21960): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)

E/AndroidRuntime(21960): 	at java.lang.System.loadLibrary(System.java:988)

E/AndroidRuntime(21960): 	at com.semperpax.spmc17.Main.onCreate(Main.java:271)

E/AndroidRuntime(21960): 	at android.app.Activity.performCreate(Activity.java:6010)

E/AndroidRuntime(21960): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)

E/AndroidRuntime(21960): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)

E/AndroidRuntime(21960): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435)

E/AndroidRuntime(21960): 	at android.app.ActivityThread.access$800(ActivityThread.java:160)

E/AndroidRuntime(21960): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)

E/AndroidRuntime(21960): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(21960): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(21960): 	at android.app.ActivityThread.main(ActivityThread.java:5484)

E/AndroidRuntime(21960): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(21960): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(21960): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)

E/AndroidRuntime(21960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

I/AndroidRuntime(21960): To Report FATAL to activityManagerService

I/ActivityManager(  514): handleApplicationCrash

W/ActivityManager(  514):   Force finishing activity 1 com.semperpax.spmc17/.Main

I/AndroidRuntime(21960): Finished reporting FATAL to activityManagerService

**Comment by koying** [comment]
Thanks for the logcat. 
Will look into it

**Comment by koying** [comment]
Yep: https://github.com/google/samba-documents-provider/issues/13
Will have to try to build libsmbclient dependencies statically...

**Comment by Dmac220** [comment]
So that's what causing the crashing issues on my phone and my Android box.

**Comment by aas88keyz** [comment]
SPMC 17.4 RC1 crashing when attempting to start on FireTV 2. previous RC's open succesfully here is the logcat. Thanks
[SendLog.zip](https://github.com/koying/SPMC/files/1175151/SendLog.zip)

**Comment by koying** [comment]
Coud you try http://download.semperpax.com/spmc/android-arm/SPMC-spmc-krypton-1f5c175-armeabi-v7a.apk please

**Comment by xodidox** [comment]
Thank you! Works great! :)

EDIT: A small issue, the inputstream.adaptive seems missing from this build.
