### ISSUE TITLE
[SPMC17][Estuary] Minor Improvement Suggestion for Branding

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#968]
Since I do really like the new branding, especially the logo, I'd suggest to also change two files here:

`/addons/skin.estuary/media/icons/`:

- `logo.png`, like this:
![logo](https://user-images.githubusercontent.com/16990469/28688458-5328a37c-7312-11e7-8b29-2f2fcb36e49a.png)

- `logo-text.png`, like this:
![logo-text](https://user-images.githubusercontent.com/16990469/28688533-82515536-7312-11e7-9d97-107be1ebad3d.png)

:)

PS: I don't use Estouchy so I didn't (es)touch anything there but I suppose something similar could be achieved for this other default skin. ;)

**Comment by koying** [comment]
Deal !
Thanks :)
