### ISSUE TITLE
Blackscreen

### ISSUE THREAD

**Issue by pjg-pigeon** [koying/SPMC#97]
Installed 16.1.1 to mx2 Android box, I see the first time run screen and the progress bar then it goes blank. 

Any suggestions? Also I am willing to assist you if you need me to do anything, like submitting logs or stuff

**Comment by koying** [comment]
Probable duplicate of #84 
Do you confirm you your box is Android 4.3?

**Comment by pjg-pigeon** [comment]
Thanks for the prompt reply.

No it's 4.2.2, is that the problem?
I sideloaded it, without checking if there were limitations.

**Comment by koying** [comment]
Probably. I've received lots of feedback that < 4.4 gets black screen.
I'll close this one ank keep the other.

**Comment by koying** [comment]
Please test http://download.semperpax.com/spmc/android-arm/SPMC-20160317-29f5ca3-fix_document_api17-armeabi-v7a.apk
