### ISSUE TITLE
[SPMC17][SPMC16] No Enable Dolby Digital (AC3) transcoding option

### ISSUE THREAD

**Issue by dar7man** [koying/SPMC#970]
Hello,

I'm using latest SPMC 17 on Sony Android TV and I don't see "Enable Dolby Digital (AC3) transcoding" option in sound menu (expert level)? I'm sure it was there sometime ago. Same issue with SPMC 16 latest version. Is this by purpose or something is wrong?

Thanks in advance,
Konrad

**Comment by 2WhlWzrd** [comment]
@mad366 
"Number of channels" must be set to 2.0 to see "Enable Dolby Digital (AC3) transcoding"

**Comment by dar7man** [comment]
You're right. I'm idiot. Thank you very much.
