### ISSUE TITLE
4k GUI 16.1.1 Nvidia Shield Tv

### ISSUE THREAD

**Issue by kirky84** [koying/SPMC#98]
Just updated to your new version and it's saying my screen is 1920x1080 but on 15.0 it said 3840x2160. Is it something I'm doing wrong? Thanks

**Comment by koying** [comment]
Got Settings-System-Video and set GUI size limiter to "unlimited"

Note to self:
Cretae a FAQ entry for this

**Comment by kirky84** [comment]
Yes just checked.

**Comment by koying** [comment]
Please upload a log a log, then.

**Comment by kirky84** [comment]
ID phkd65ixy
URL:http://spmclogs.semperpax.com/phkd65ixy 

Thanks

**Comment by koying** [comment]
Don't know.
Be sure that your AVR and/or TV is on when booting the shield, though (known shield issue).

**Comment by kirky84** [comment]
Simple as that. Just restarted the shield and it's displaying as it should. Thanks for your help
