### ISSUE TITLE
[SPMC 17] Next up service notification crashes SPMC

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#982]
Steps to reproduce:

* SPMC 17 alpha 8
* Enable Next up service notification plugin
* Disable postplay screen in next up service notification configuration.
* Watch a TV show. When the countdown hits zero, SPMC crashes rather than plays the next TV episode.
* I am using Hitcher's FTV skin for Krypton.

**Comment by ghost** [comment]
I'm running Nextup in a similar fashion but usually "unskinned" with a slightly changed Estuary and had no issues with 17a8 (yet). Just tried it skinned with a Mimic variant and it worked too. May point towards FTV on 17a8 being a special case.

**Comment by classicjazz** [comment]
@koying 

I emailed you the debug logs. Hoping that they help diagnose the issue.

**Comment by koying** [comment]
Nothing obvious in the log.
Does a logcat show a crash?

**Comment by classicjazz** [comment]
@koying 

I just sent a logcat via email.

**Comment by koying** [comment]
Thanks. You confirm the crash happens at end of playlist, right? Or even after the first play of a playlist? 

I might not have much time to test, so could you confirm playing a playlist w/o nextup works, please

**Comment by classicjazz** [comment]
I will check it with your race fix when you release the next build. 

I don't use playlists. Though perhaps you are saying that Nextup uses them behind the curtains?

**Comment by classicjazz** [comment]
I think you fixed it with the race condition commit.
