### ISSUE TITLE
[SPMC 17] selecting more ">>" for plot in FTV skin freezes SPMC

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#993]
Happens frequently but not every time:

Steps to reproduce:
* Select the >> (more) in Hitcher's FTV skin to see beyond 2 lines of plot details (pulls up a plot dialog box).
* SPMC becomes completely unresponsive. No further keystrokes are recognized in SPMC.
* If you exit to Leanback Launcher, it says that SPMC has crashed.

Logs sent  to your email.

**Comment by koying** [comment]
Seems to work for me in a couple of tests, and the log says nothing of relevance
Is the crash dependent on the movie for which you press the >>

**Comment by 2WhlWzrd** [comment]
Not sure if it is relevant or not, but running SPMC17a8 with the same skin, it works for me also.
But running Kodi17.4rc1 and the same skin, I get a "ToolBox Script error".

log:
[kodi17.4rc1 toolbox script error](https://pastebin.com/2fRJ4SSU)
