### ISSUE TITLE
SPMC 17 a8 not autostart on boot

### ISSUE THREAD

**Issue by Nanomani** [koying/SPMC#997]
xbmc.autostart=yes don't works yet for SPMC 17

perhaps it is normal at this step of dev ?

If yes, please close this issue. 

It is not a big deal. 
Otherwise SPMC 17 a8 works for my need like a charm.

Thanks a lot for your works and your time for us.

Nvidia Shield 16 Go 2015
SPMC a8
Aeon MQ 7 2.0.7.5

**Comment by koying** [comment]
It sure does work for me...
You use xbmc_env and not spmc_env, I suppose? Maybe something broken there...

**Comment by Nanomani** [comment]
Yep your are right.
I always use  xbmc_env
But with spmc_env all is ok for me too.
Thanks

**Comment by koying** [comment]
To be clear, you had both spmc_env and xbmc_env, and the autostart was only in xbmc_env, right?
If so, it works as designed, as xbmc_env is ignored if there is a spmc_env

**Comment by Nanomani** [comment]
to be clear : 

before my post, I have 1 file under  /sdcard 

`xbmc_env.properties` with `xbmc.autostart=yes`

and now I have deleted the file `xbmc_env.properties` 

I have always only 1 file under  /sdcard 

`spmc_env.properties` with `spmc.autostart=yes`

i hope this helps you ...

**Comment by koying** [comment]
Ah, thanks for the clarification.
Not sure yet if it's a feature or a bug ;)
